In [ ]:
import pandas as pd
import numpy as np
import json
import os

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
import os

print("Files available in Colab:")
for file in os.listdir("/content"):
    print(file)

Files available in Colab:
.config
products.csv
customers.json
sales 1.csv
sample_data

In [ ]:
with open("/content/customers.json", "r", encoding="utf-8") as file:
    customer_data = json.load(file)

customers = pd.DataFrame(customer_data)

print("Customer data loaded successfully.")
print("Rows:", customers.shape[0])
print("Columns:", customers.shape[1])

customers.head()

Customer data loaded successfully.
Rows: 1100
Columns: 6

  CustomerID FirstName LastName Gender      Region          SSN
0      C0001   Gregory   Miller      M        Ohho    082573197
1      C0002    Marvin     None   male  california  309-6256-21
2      C0003   Gregory    Smith   Male   New Yorkk    407071725
3      C0004    Edward    Davis   male        Ohho  948.18.5740
4      C0005  Reginald   Dawson   male       Texas  975.72.3056

In [ ]:
sales = pd.read_csv("/content/sales 1.csv")

print("Sales data loaded successfully.")
print("Rows:", sales.shape[0])
print("Columns:", sales.shape[1])

sales.head()

Sales data loaded successfully.
Rows: 10000
Columns: 6

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09T20:21:00
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28T05:01:00
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13T00:36:00
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,NaN,50.0,2024-07-06T23:39:00
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08T19:58:00

In [ ]:
products = pd.read_csv("/content/products.csv")

print("Product data loaded successfully.")
print("Rows:", products.shape[0])
print("Columns:", products.shape[1])

products.head()

Product data loaded successfully.
Rows: 50
Columns: 3

   ProductID      ProductName         Category
0       1000  Washing Machine  Home Appliances
1       1001     Refrigerator  Home Appliances
2       1002          Blender  Home Appliances
3       1003        Microwave  Home Appliances
4       1004   Vacuum Cleaner  Home Appliances

In [ ]:
print("========== DATASET OVERVIEW ==========")

print("\nCUSTOMER DATA")
print("Rows:", customers.shape[0])
print("Columns:", customers.shape[1])

print("\nSALES DATA")
print("Rows:", sales.shape[0])
print("Columns:", sales.shape[1])

print("\nPRODUCT DATA")
print("Rows:", products.shape[0])
print("Columns:", products.shape[1])

========== DATASET OVERVIEW ==========

CUSTOMER DATA
Rows: 1100
Columns: 6

SALES DATA
Rows: 10000
Columns: 6

PRODUCT DATA
Rows: 50
Columns: 3

In [ ]:
print("Customer Columns:")
print(customers.columns.tolist())

print("\nSales Columns:")
print(sales.columns.tolist())

print("\nProduct Columns:")
print(products.columns.tolist())

Customer Columns:
['CustomerID', 'FirstName', 'LastName', 'Gender', 'Region', 'SSN']

Sales Columns:
['SaleID', 'ProductID', 'CustomerID', 'SalesAmount', 'Quantity', 'Timestamp']

Product Columns:
['ProductID', 'ProductName', 'Category']

In [ ]:
print("========== CUSTOMER DATA TYPES ==========")
print(customers.dtypes)

print("\n========== SALES DATA TYPES ==========")
print(sales.dtypes)

print("\n========== PRODUCT DATA TYPES ==========")
print(products.dtypes)

========== CUSTOMER DATA TYPES ==========
CustomerID    object
FirstName     object
LastName      object
Gender        object
Region        object
SSN           object
dtype: object

========== SALES DATA TYPES ==========
SaleID          object
ProductID        int64
CustomerID      object
SalesAmount    float64
Quantity       float64
Timestamp       object
dtype: object

========== PRODUCT DATA TYPES ==========
ProductID       int64
ProductName    object
Category       object
dtype: object

In [ ]:
print("========== CUSTOMER MISSING VALUES ==========")
print(customers.isnull().sum())

print("\n========== SALES MISSING VALUES ==========")
print(sales.isnull().sum())

print("\n========== PRODUCT MISSING VALUES ==========")
print(products.isnull().sum())

========== CUSTOMER MISSING VALUES ==========
CustomerID      0
FirstName       0
LastName      320
Gender          0
Region         69
SSN             0
dtype: int64

========== SALES MISSING VALUES ==========
SaleID           0
ProductID        0
CustomerID       0
SalesAmount    497
Quantity       113
Timestamp        0
dtype: int64

========== PRODUCT MISSING VALUES ==========
ProductID      0
ProductName    0
Category       0
dtype: int64

In [ ]:
def missing_summary(df):
    summary = pd.DataFrame({
        "Missing Count": df.isnull().sum(),
        "Missing Percentage": (df.isnull().mean() * 100).round(2)
    })

    return summary.sort_values(
        by="Missing Percentage",
        ascending=False
    )


print("========== CUSTOMER DATA ==========")
display(missing_summary(customers))

print("\n========== SALES DATA ==========")
display(missing_summary(sales))

print("\n========== PRODUCT DATA ==========")
display(missing_summary(products))

========== CUSTOMER DATA ==========

            Missing Count  Missing Percentage
LastName              320               29.09
Region                 69                6.27
FirstName               0                0.00
CustomerID              0                0.00
Gender                  0                0.00
SSN                     0                0.00

========== SALES DATA ==========

             Missing Count  Missing Percentage
SalesAmount            497                4.97
Quantity               113                1.13
ProductID                0                0.00
SaleID                   0                0.00
CustomerID               0                0.00
Timestamp                0                0.00

========== PRODUCT DATA ==========

             Missing Count  Missing Percentage
ProductID                0                 0.0
ProductName              0                 0.0
Category                 0                 0.0

In [ ]:
print("========== DUPLICATE RECORD CHECK ==========")

print("\nCustomer duplicate rows:")
print(customers.duplicated().sum())

print("\nSales duplicate rows:")
print(sales.duplicated().sum())

print("\nProduct duplicate rows:")
print(products.duplicated().sum())

========== DUPLICATE RECORD CHECK ==========

Customer duplicate rows:
100

Sales duplicate rows:
0

Product duplicate rows:
0

In [ ]:
print("========== PRIMARY KEY UNIQUENESS CHECK ==========")

# CustomerID
print("\nCustomerID:")
print("Unique:", customers["CustomerID"].is_unique)
print("Duplicate Count:", customers["CustomerID"].duplicated().sum())

# SaleID
print("\nSaleID:")
print("Unique:", sales["SaleID"].is_unique)
print("Duplicate Count:", sales["SaleID"].duplicated().sum())

# ProductID
print("\nProductID:")
print("Unique:", products["ProductID"].is_unique)
print("Duplicate Count:", products["ProductID"].duplicated().sum())

========== PRIMARY KEY UNIQUENESS CHECK ==========

CustomerID:
Unique: False
Duplicate Count: 100

SaleID:
Unique: True
Duplicate Count: 0

ProductID:
Unique: True
Duplicate Count: 0

In [ ]:
print("========== DUPLICATE CUSTOMER RECORDS ==========")

duplicate_customers = customers[
    customers["CustomerID"].duplicated(keep=False)
].sort_values("CustomerID")

print("Number of rows involved:", len(duplicate_customers))
print("Number of duplicated CustomerIDs:",
      duplicate_customers["CustomerID"].nunique())

display(duplicate_customers.head(30))

========== DUPLICATE CUSTOMER RECORDS ==========
Number of rows involved: 200
Number of duplicated CustomerIDs: 100

     CustomerID FirstName   LastName  Gender       Region          SSN
22        C0023     Grant   Bartlett    male         Ohio  914-9819-50
1000      C0023     Grant   Bartlett    male         Ohio  914-9819-50
25        C0026     Jesse  Wilkerson    male           NY  929/20/0753
1001      C0026     Jesse  Wilkerson    male           NY  929/20/0753
46        C0047      Seth       Hess    Male        Texas    075643618
1002      C0047      Seth       Hess    Male        Texas    075643618
47        C0048     Frank       Ross       M         Ohho  466.83.1539
1003      C0048     Frank       Ross       M         Ohho  466.83.1539
49        C0050  Kimberly     Wright  female      Nw York  556/57/7221
1004      C0050  Kimberly     Wright  female      Nw York  556/57/7221
1005      C0051     David       None    Male         None  709.24.5509
50        C0051     David       None    Male         None  709.24.5509
62        C0063    Latoya       None  female         Ohho  575-57-9346
1006      C0063    Latoya       None  female         Ohho  575-57-9346
1007      C0067      Eric     Morris    male           NY  192-18-1825
66        C0067      Eric     Morris    male           NY  192-18-1825
1008      C0127     Frank     Turner    Male         None  817-84-4697
126       C0127     Frank     Turner    Male         None  817-84-4697
1009      C0128      Tina       None  Female         Ohio  387/15/2762
127       C0128      Tina       None  Female         Ohio  387/15/2762
1010      C0133     Kevin       None    Male         None  294/23/8712
132       C0133     Kevin       None    Male         None  294/23/8712
137       C0138   William      Boone    male         None  499-81-2161
1011      C0138   William      Boone    male         None  499-81-2161
152       C0153   Gregory    Krueger       M  Californiya  274.65.4231
1012      C0153   Gregory    Krueger       M  Californiya  274.65.4231
163       C0164   Theresa      Davis  Female        Texaz  816.34.7228
1013      C0164   Theresa      Davis  Female        Texaz  816.34.7228
175       C0176    Edward       Bell       M     New York  381-9101-40
1014      C0176    Edward       Bell       M     New York  381-9101-40

In [ ]:
print("========== EXACT DUPLICATE CUSTOMER ID CHECK ==========")

# Keep all rows belonging to duplicated CustomerIDs
duplicate_customers = customers[
    customers["CustomerID"].duplicated(keep=False)
].copy()

# Check whether each duplicated CustomerID has only one unique
# combination of the remaining customer attributes
attribute_columns = [
    "FirstName",
    "LastName",
    "Gender",
    "Region",
    "SSN"
]

duplicate_consistency = (
    duplicate_customers
    .groupby("CustomerID")[attribute_columns]
    .nunique(dropna=False)
)

# A value of 1 in every attribute means the duplicate records
# contain the same customer information
exact_duplicates = duplicate_consistency.eq(1).all(axis=1)

print("Duplicated CustomerIDs:", len(duplicate_consistency))
print("Exact duplicate CustomerIDs:", exact_duplicates.sum())
print("Conflicting CustomerIDs:", (~exact_duplicates).sum())

print("\n========== CONFLICTING CUSTOMER IDs ==========")
display(duplicate_consistency[~exact_duplicates])

========== EXACT DUPLICATE CUSTOMER ID CHECK ==========
Duplicated CustomerIDs: 100
Exact duplicate CustomerIDs: 100
Conflicting CustomerIDs: 0

========== CONFLICTING CUSTOMER IDs ==========

Empty DataFrame
Columns: [FirstName, LastName, Gender, Region, SSN]
Index: []

In [ ]:
print("========== CUSTOMER DEDUPLICATION IMPACT ==========")

original_customer_count = len(customers)

deduplicated_customers = customers.drop_duplicates(
    subset="CustomerID",
    keep="first"
).copy()

deduplicated_customer_count = len(deduplicated_customers)

print("Original customer rows:", original_customer_count)
print("Rows after deduplication:", deduplicated_customer_count)
print("Duplicate rows removed:",
      original_customer_count - deduplicated_customer_count)

print("\nUnique CustomerIDs before:", customers["CustomerID"].nunique())
print("Unique CustomerIDs after:", deduplicated_customers["CustomerID"].nunique())

========== CUSTOMER DEDUPLICATION IMPACT ==========
Original customer rows: 1100
Rows after deduplication: 1000
Duplicate rows removed: 100

Unique CustomerIDs before: 1000
Unique CustomerIDs after: 1000

In [ ]:
print("========== SALES REFERENTIAL INTEGRITY CHECK ==========")

# Use the deduplicated customer dataset
valid_customer_ids = set(deduplicated_customers["CustomerID"])
valid_product_ids = set(products["ProductID"])

# Check Sales → Customer
sales_customer_ids = set(sales["CustomerID"])
missing_customer_ids = sales_customer_ids - valid_customer_ids

print("\nSales → Customer:")
print("Unique CustomerIDs in Sales:", len(sales_customer_ids))
print("CustomerIDs missing from Customer data:", len(missing_customer_ids))

if missing_customer_ids:
    print("Missing CustomerIDs:")
    print(sorted(missing_customer_ids))

# Check Sales → Product
sales_product_ids = set(sales["ProductID"])
missing_product_ids = sales_product_ids - valid_product_ids

print("\nSales → Product:")
print("Unique ProductIDs in Sales:", len(sales_product_ids))
print("ProductIDs missing from Product data:", len(missing_product_ids))

if missing_product_ids:
    print("Missing ProductIDs:")
    print(sorted(missing_product_ids))

========== SALES REFERENTIAL INTEGRITY CHECK ==========

Sales → Customer:
Unique CustomerIDs in Sales: 1000
CustomerIDs missing from Customer data: 0

Sales → Product:
Unique ProductIDs in Sales: 50
ProductIDs missing from Product data: 0

In [ ]:
print("========== SALES NUMERIC DATA QUALITY ==========")

# SalesAmount checks
print("\nSalesAmount:")
print("Negative values:", (sales["SalesAmount"] < 0).sum())
print("Zero values:", (sales["SalesAmount"] == 0).sum())
print("Minimum:", sales["SalesAmount"].min())
print("Maximum:", sales["SalesAmount"].max())

# Quantity checks
print("\nQuantity:")
print("Negative values:", (sales["Quantity"] < 0).sum())
print("Zero values:", (sales["Quantity"] == 0).sum())
print("Minimum:", sales["Quantity"].min())
print("Maximum:", sales["Quantity"].max())

# Integer check for non-missing Quantity values
non_null_quantity = sales["Quantity"].dropna()

print("\nQuantity integer-value check:")
print(
    "Non-integer values:",
    (non_null_quantity % 1 != 0).sum()
)

========== SALES NUMERIC DATA QUALITY ==========

SalesAmount:
Negative values: 0
Zero values: 0
Minimum: 50.18
Maximum: 79783.4

Quantity:
Negative values: 0
Zero values: 0
Minimum: 1.0
Maximum: 50.0

Quantity integer-value check:
Non-integer values: 0

In [ ]:
print("========== TIMESTAMP DATA QUALITY ==========")

# Convert to datetime temporarily for validation
timestamp_check = pd.to_datetime(
    sales["Timestamp"],
    errors="coerce"
)

print("Invalid timestamp values:", timestamp_check.isna().sum())

print("\nMinimum timestamp:", timestamp_check.min())
print("Maximum timestamp:", timestamp_check.max())

print("\nMissing timestamp values:", sales["Timestamp"].isnull().sum())

========== TIMESTAMP DATA QUALITY ==========
Invalid timestamp values: 0

Minimum timestamp: 2024-06-01 10:03:00
Maximum timestamp: 2024-11-28 09:38:00

Missing timestamp values: 0

In [ ]:
print("========== PRODUCT DATA CONSISTENCY ==========")

print("Total product rows:", len(products))
print("Unique ProductIDs:", products["ProductID"].nunique())
print("Unique ProductNames:", products["ProductName"].nunique())
print("Unique Categories:", products["Category"].nunique())

print("\n========== PRODUCT NAME + CATEGORY DUPLICATES ==========")

product_duplicates = products[
    products.duplicated(
        subset=["ProductName", "Category"],
        keep=False
    )
]

print("Duplicate ProductName + Category rows:",
      len(product_duplicates))

if len(product_duplicates) > 0:
    display(product_duplicates)

========== PRODUCT DATA CONSISTENCY ==========
Total product rows: 50
Unique ProductIDs: 50
Unique ProductNames: 50
Unique Categories: 4

========== PRODUCT NAME + CATEGORY DUPLICATES ==========
Duplicate ProductName + Category rows: 0

In [ ]:
print("========== CUSTOMER CATEGORICAL VALUE PROFILE ==========")

print("\n========== GENDER VALUES ==========")
print(deduplicated_customers["Gender"].value_counts(dropna=False))

print("\n========== REGION VALUES ==========")
print(deduplicated_customers["Region"].value_counts(dropna=False))

print("\n========== FIRST NAME UNIQUE VALUES ==========")
print("Unique FirstNames:", deduplicated_customers["FirstName"].nunique())

print("\n========== LAST NAME MISSING ==========")
print("Missing LastNames:",
      deduplicated_customers["LastName"].isnull().sum())

========== CUSTOMER CATEGORICAL VALUE PROFILE ==========

========== GENDER VALUES ==========
Gender
M         285
male      249
Male      249
F          80
female     75
Female     62
Name: count, dtype: int64

========== REGION VALUES ==========
Region
Texaz          102
NY             102
Californiya    102
New York        96
Ohho            94
Nw York         92
Texas           92
california      90
New Yorkk       87
Ohio            81
None            62
Name: count, dtype: int64

========== FIRST NAME UNIQUE VALUES ==========
Unique FirstNames: 318

========== LAST NAME MISSING ==========
Missing LastNames: 290

In [ ]:
print("========== SALES DISTRIBUTION PROFILE ==========")

print("\n========== SALES AMOUNT ==========")
display(sales["SalesAmount"].describe())

print("\n========== QUANTITY ==========")
display(sales["Quantity"].describe())

print("\n========== PRODUCT ID DISTRIBUTION ==========")
print("Unique ProductIDs:", sales["ProductID"].nunique())
print("Minimum ProductID:", sales["ProductID"].min())
print("Maximum ProductID:", sales["ProductID"].max())

print("\n========== CUSTOMER ID DISTRIBUTION ==========")
print("Unique CustomerIDs:", sales["CustomerID"].nunique())
print("Total Sales Rows:", len(sales))

========== SALES DISTRIBUTION PROFILE ==========

========== SALES AMOUNT ==========

count     9503.000000
mean      1436.999871
std       4874.463101
min         50.180000
25%        534.470000
50%       1015.070000
75%       1517.140000
max      79783.400000
Name: SalesAmount, dtype: float64

========== QUANTITY ==========

count    9887.000000
mean       25.231617
std        14.363280
min         1.000000
25%        13.000000
50%        25.000000
75%        38.000000
max        50.000000
Name: Quantity, dtype: float64

========== PRODUCT ID DISTRIBUTION ==========
Unique ProductIDs: 50
Minimum ProductID: 1000
Maximum ProductID: 1049

========== CUSTOMER ID DISTRIBUTION ==========
Unique CustomerIDs: 1000
Total Sales Rows: 10000

In [ ]:
print("========== SALES AMOUNT OUTLIER CHECK ==========")

sales_amount = sales["SalesAmount"].dropna()

Q1 = sales_amount.quantile(0.25)
Q3 = sales_amount.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = sales[
    (sales["SalesAmount"] < lower_bound) |
    (sales["SalesAmount"] > upper_bound)
]

print("Q1:", round(Q1, 2))
print("Q3:", round(Q3, 2))
print("IQR:", round(IQR, 2))

print("\nLower Bound:", round(lower_bound, 2))
print("Upper Bound:", round(upper_bound, 2))

print("\nNumber of potential outliers:", len(outliers))

print("\n========== TOP SALES AMOUNT VALUES ==========")
display(
    sales[["SaleID", "ProductID", "CustomerID", "SalesAmount", "Quantity"]]
    .sort_values("SalesAmount", ascending=False)
    .head(10)
)

========== SALES AMOUNT OUTLIER CHECK ==========
Q1: 534.47
Q3: 1517.14
IQR: 982.67

Lower Bound: -939.54
Upper Bound: 2991.15

Number of potential outliers: 79

========== TOP SALES AMOUNT VALUES ==========

,SaleID,ProductID,CustomerID,SalesAmount,Quantity
8092,e393ce9b-3714-4473-bf79-aba0b9432aa4,1027,C0422,79783.40,28.0
2981,b96dedf9-6a35-442c-9692-ec3835604939,1043,C0983,78319.28,31.0
9937,56aa51cf-b202-4a01-8f5e-5b5a335cebaf,1039,C0051,77834.11,46.0
9927,bae96876-7a12-489a-91d3-3d8792b91c3e,1030,C0269,76993.72,22.0
6364,b94c6ecf-a1b2-41fa-ba2a-f7ccde59c98b,1033,C0435,76454.10,39.0
5358,a668fecf-2ae1-4b3b-b320-1d7782175124,1037,C0278,75195.85,25.0
4757,af1948f7-0eee-4614-88bc-0f9be8e519aa,1018,C0957,74975.93,39.0
9258,7f683157-8328-4890-bb5a-a6120cbb71f2,1003,C0555,73591.77,33.0
3761,4daed08b-7582-4598-af56-0aa8c9d5cd1b,1039,C0162,73408.15,29.0
9077,87c6ffc9-2dad-43c5-becb-e59dc15635c5,1047,C0793,72481.55,6.0

In [ ]:
print("========== SALES AMOUNT OUTLIER ANALYSIS ==========")

# Add ProductName and Category to the outlier records
outlier_analysis = outliers.merge(
    products[["ProductID", "ProductName", "Category"]],
    on="ProductID",
    how="left"
)

print("Potential outlier transactions:", len(outlier_analysis))

print("\n========== OUTLIERS BY CATEGORY ==========")

category_outliers = (
    outlier_analysis["Category"]
    .value_counts()
    .rename_axis("Category")
    .reset_index(name="Outlier Count")
)

display(category_outliers)

print("\n========== OUTLIER SALES BY PRODUCT ==========")

product_outliers = (
    outlier_analysis
    .groupby(
        ["ProductID", "ProductName", "Category"],
        as_index=False
    )
    .agg(
        OutlierTransactions=("SaleID", "count"),
        TotalOutlierSales=("SalesAmount", "sum"),
        MaxSalesAmount=("SalesAmount", "max")
    )
    .sort_values("TotalOutlierSales", ascending=False)
)

display(product_outliers.head(15))

========== SALES AMOUNT OUTLIER ANALYSIS ==========
Potential outlier transactions: 79

========== OUTLIERS BY CATEGORY ==========

          Category  Outlier Count
0             Toys             39
1      Electronics             27
2        Furniture              9
3  Home Appliances              4

========== OUTLIER SALES BY PRODUCT ==========

,ProductID,ProductName,Category,OutlierTransactions,TotalOutlierSales,MaxSalesAmount
23,1030,Action Figure,Toys,8,442183.47,76993.72
30,1037,Stuffed Animal,Toys,4,210943.95,75195.85
38,1047,Swing,Toys,4,200449.44,72481.55
24,1031,Board Game,Toys,3,187417.04,72139.19
4,1006,Table,Furniture,3,186998.94,65364.17
25,1032,Doll,Toys,3,164131.06,68188.38
34,1041,Toy Train,Toys,4,151592.49,63960.01
32,1039,Kite,Toys,2,151242.26,77834.11
1,1003,Microwave,Home Appliances,2,143811.69,73591.77
16,1020,Keyboard,Electronics,2,140108.67,71218.31
22,1029,Smart Glasses,Electronics,3,137835.68,57392.45
10,1014,Camera,Electronics,3,134857.82,71457.75
12,1016,Bluetooth Speaker,Electronics,3,132760.01,63242.95
6,1008,Bed,Furniture,2,123671.85,65514.97
20,1027,Drone,Electronics,2,119485.55,79783.40

In [ ]:
print("========== SALES AMOUNT vs QUANTITY CHECK ==========")

sales_relationship = sales[
    ["SalesAmount", "Quantity"]
].dropna()

print("Valid records analyzed:", len(sales_relationship))

print("\n========== CORRELATION ==========")
print(
    "SalesAmount-Quantity correlation:",
    round(
        sales_relationship["SalesAmount"]
        .corr(sales_relationship["Quantity"]),
        3
    )
)

print("\n========== HIGH-VALUE TRANSACTIONS ==========")

high_value_sales = sales[
    sales["SalesAmount"] > 10000
][["SaleID", "ProductID", "CustomerID", "SalesAmount", "Quantity"]]

print("Transactions with SalesAmount > 10,000:",
      len(high_value_sales))

display(
    high_value_sales
    .sort_values("SalesAmount", ascending=False)
    .head(15)
)

========== SALES AMOUNT vs QUANTITY CHECK ==========
Valid records analyzed: 9397

========== CORRELATION ==========
SalesAmount-Quantity correlation: -0.002

========== HIGH-VALUE TRANSACTIONS ==========
Transactions with SalesAmount > 10,000: 79

,SaleID,ProductID,CustomerID,SalesAmount,Quantity
8092,e393ce9b-3714-4473-bf79-aba0b9432aa4,1027,C0422,79783.40,28.0
2981,b96dedf9-6a35-442c-9692-ec3835604939,1043,C0983,78319.28,31.0
9937,56aa51cf-b202-4a01-8f5e-5b5a335cebaf,1039,C0051,77834.11,46.0
9927,bae96876-7a12-489a-91d3-3d8792b91c3e,1030,C0269,76993.72,22.0
6364,b94c6ecf-a1b2-41fa-ba2a-f7ccde59c98b,1033,C0435,76454.10,39.0
5358,a668fecf-2ae1-4b3b-b320-1d7782175124,1037,C0278,75195.85,25.0
4757,af1948f7-0eee-4614-88bc-0f9be8e519aa,1018,C0957,74975.93,39.0
9258,7f683157-8328-4890-bb5a-a6120cbb71f2,1003,C0555,73591.77,33.0
3761,4daed08b-7582-4598-af56-0aa8c9d5cd1b,1039,C0162,73408.15,29.0
9077,87c6ffc9-2dad-43c5-becb-e59dc15635c5,1047,C0793,72481.55,6.0
2642,3679409a-cb93-4f90-8f7d-0fd509a3dbe8,1031,C0570,72139.19,32.0
2028,f52998ed-6755-4b09-92cf-8ef3dcd0bfd4,1014,C0909,71457.75,39.0
1001,3dcfbd1d-196e-41c3-82e8-c4402e57a32b,1020,C0864,71218.31,22.0
7409,1113dce0-f1e9-49db-aa3a-7d59a89ce3be,1003,C0352,70219.92,27.0
1078,b45152d3-17f4-4314-a3a0-b38517e2ea66,1020,C0089,68890.36,5.0

In [ ]:
print("========== CUSTOMER ID FORMAT CHECK ==========")

customer_ids = deduplicated_customers["CustomerID"].astype(str)

# Expected format: C followed by exactly 4 digits
valid_customer_id_format = customer_ids.str.match(r"^C\d{4}$")

print("Total CustomerIDs:", len(customer_ids))
print("Valid C#### format:", valid_customer_id_format.sum())
print("Invalid CustomerID formats:",
      (~valid_customer_id_format).sum())

if (~valid_customer_id_format).sum() > 0:
    print("\nInvalid CustomerIDs:")
    display(
        deduplicated_customers.loc[
            ~valid_customer_id_format,
            ["CustomerID"]
        ]
    )

print("\n========== CUSTOMER ID RANGE ==========")

numeric_customer_ids = pd.to_numeric(
    customer_ids.str.replace("C", "", regex=False),
    errors="coerce"
)

print("Minimum numeric CustomerID:", numeric_customer_ids.min())
print("Maximum numeric CustomerID:", numeric_customer_ids.max())
print("Invalid numeric conversions:", numeric_customer_ids.isna().sum())

========== CUSTOMER ID FORMAT CHECK ==========
Total CustomerIDs: 1000
Valid C#### format: 1000
Invalid CustomerID formats: 0

========== CUSTOMER ID RANGE ==========
Minimum numeric CustomerID: 1
Maximum numeric CustomerID: 1000
Invalid numeric conversions: 0

In [ ]:
print("========== PRODUCT ID FORMAT & RANGE CHECK ==========")

print("Total ProductIDs:", len(products))
print("Unique ProductIDs:", products["ProductID"].nunique())

# Check whether all ProductIDs are integer-valued
integer_product_ids = (
    pd.to_numeric(products["ProductID"], errors="coerce")
    .notna()
    &
    (products["ProductID"] % 1 == 0)
)

print("Integer-valued ProductIDs:", integer_product_ids.sum())
print("Invalid ProductIDs:", (~integer_product_ids).sum())

print("\n========== PRODUCT ID RANGE ==========")
print("Minimum ProductID:", products["ProductID"].min())
print("Maximum ProductID:", products["ProductID"].max())

print("\n========== EXPECTED PRODUCT ID RANGE CHECK ==========")

expected_product_ids = set(range(1000, 1050))
actual_product_ids = set(products["ProductID"])

missing_product_ids = expected_product_ids - actual_product_ids
unexpected_product_ids = actual_product_ids - expected_product_ids

print("Missing IDs from expected 1000–1049:",
      len(missing_product_ids))
print("Unexpected IDs outside expected range:",
      len(unexpected_product_ids))

if missing_product_ids:
    print("Missing:", sorted(missing_product_ids))

if unexpected_product_ids:
    print("Unexpected:", sorted(unexpected_product_ids))

========== PRODUCT ID FORMAT & RANGE CHECK ==========
Total ProductIDs: 50
Unique ProductIDs: 50
Integer-valued ProductIDs: 50
Invalid ProductIDs: 0

========== PRODUCT ID RANGE ==========
Minimum ProductID: 1000
Maximum ProductID: 1049

========== EXPECTED PRODUCT ID RANGE CHECK ==========
Missing IDs from expected 1000–1049: 0
Unexpected IDs outside expected range: 0

In [ ]:
print("========== SALES CUSTOMER ID FORMAT CHECK ==========")

sales_customer_ids = sales["CustomerID"].astype(str)

# Expected format: C followed by exactly 4 digits
valid_sales_customer_id_format = sales_customer_ids.str.match(
    r"^C\d{4}$"
)

print("Total Sales CustomerID values:", len(sales_customer_ids))
print("Valid C#### format:", valid_sales_customer_id_format.sum())
print(
    "Invalid CustomerID formats:",
    (~valid_sales_customer_id_format).sum()
)

if (~valid_sales_customer_id_format).sum() > 0:
    print("\nInvalid Sales CustomerIDs:")
    display(
        sales.loc[
            ~valid_sales_customer_id_format,
            ["SaleID", "CustomerID"]
        ].head(20)
    )

print("\n========== SALES CUSTOMER ID RANGE ==========")

numeric_sales_customer_ids = pd.to_numeric(
    sales_customer_ids.str.replace("C", "", regex=False),
    errors="coerce"
)

print(
    "Minimum numeric CustomerID:",
    numeric_sales_customer_ids.min()
)
print(
    "Maximum numeric CustomerID:",
    numeric_sales_customer_ids.max()
)
print(
    "Invalid numeric conversions:",
    numeric_sales_customer_ids.isna().sum()
)

print("\n========== SALES vs CUSTOMER ID COVERAGE ==========")

customer_numeric_ids = set(
    pd.to_numeric(
        deduplicated_customers["CustomerID"]
        .astype(str)
        .str.replace("C", "", regex=False),
        errors="coerce"
    )
)

sales_numeric_ids = set(numeric_sales_customer_ids)

missing_from_customer = sales_numeric_ids - customer_numeric_ids

print(
    "Unique CustomerIDs in Sales:",
    len(sales_numeric_ids)
)
print(
    "Sales CustomerIDs missing from Customer table:",
    len(missing_from_customer)
)

if missing_from_customer:
    print(
        "Missing numeric CustomerIDs:",
        sorted(missing_from_customer)
    )

========== SALES CUSTOMER ID FORMAT CHECK ==========
Total Sales CustomerID values: 10000
Valid C#### format: 10000
Invalid CustomerID formats: 0

========== SALES CUSTOMER ID RANGE ==========
Minimum numeric CustomerID: 1
Maximum numeric CustomerID: 1000
Invalid numeric conversions: 0

========== SALES vs CUSTOMER ID COVERAGE ==========
Unique CustomerIDs in Sales: 1000
Sales CustomerIDs missing from Customer table: 0

In [ ]:
print("========== SALES PRODUCT ID CHECK ==========")

sales_product_ids = pd.to_numeric(
    sales["ProductID"],
    errors="coerce"
)

print("Total Sales ProductID values:", len(sales_product_ids))
print("Invalid ProductID conversions:", sales_product_ids.isna().sum())

# Check integer-valued ProductIDs
valid_integer_product_ids = (
    sales_product_ids.notna()
    &
    (sales_product_ids % 1 == 0)
)

print(
    "Integer-valued ProductIDs:",
    valid_integer_product_ids.sum()
)
print(
    "Non-integer ProductIDs:",
    (~valid_integer_product_ids).sum()
)

print("\n========== SALES PRODUCT ID RANGE ==========")

print("Minimum ProductID:", sales_product_ids.min())
print("Maximum ProductID:", sales_product_ids.max())

print("\n========== SALES vs PRODUCT ID COVERAGE ==========")

sales_product_id_set = set(
    sales_product_ids.dropna().astype(int)
)

product_id_set = set(
    products["ProductID"].astype(int)
)

missing_from_product = sales_product_id_set - product_id_set

print(
    "Unique ProductIDs in Sales:",
    len(sales_product_id_set)
)
print(
    "ProductIDs in Sales missing from Product table:",
    len(missing_from_product)
)

if missing_from_product:
    print(
        "Missing ProductIDs:",
        sorted(missing_from_product)
    )

========== SALES PRODUCT ID CHECK ==========
Total Sales ProductID values: 10000
Invalid ProductID conversions: 0
Integer-valued ProductIDs: 10000
Non-integer ProductIDs: 0

========== SALES PRODUCT ID RANGE ==========
Minimum ProductID: 1000
Maximum ProductID: 1049

========== SALES vs PRODUCT ID COVERAGE ==========
Unique ProductIDs in Sales: 50
ProductIDs in Sales missing from Product table: 0

In [ ]:
import re

print("========== SALE ID VALIDATION ==========")

sale_ids = sales["SaleID"].astype(str)

# Standard UUID pattern
uuid_pattern = (
    r"^[0-9a-fA-F]{8}-"
    r"[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{12}$"
)

valid_uuid_format = sale_ids.str.match(uuid_pattern)

print("Total SaleIDs:", len(sale_ids))
print("Unique SaleIDs:", sale_ids.nunique())
print("Duplicate SaleIDs:", sale_ids.duplicated().sum())

print("\n========== UUID FORMAT ==========")

print("Valid UUID format:", valid_uuid_format.sum())
print("Invalid UUID format:", (~valid_uuid_format).sum())

if (~valid_uuid_format).sum() > 0:
    print("\nInvalid SaleIDs:")
    display(
        sales.loc[
            ~valid_uuid_format,
            ["SaleID"]
        ].head(20)
    )

print("\n========== SALE ID NULL CHECK ==========")

print("Missing SaleIDs:", sales["SaleID"].isna().sum())

print("\n========== SALE ID UNIQUENESS CHECK ==========")

if sales["SaleID"].is_unique:
    print("Result: SaleID is unique and suitable as a source transaction identifier.")
else:
    print("Result: Duplicate SaleIDs require investigation.")

========== SALE ID VALIDATION ==========
Total SaleIDs: 10000
Unique SaleIDs: 10000
Duplicate SaleIDs: 0

========== UUID FORMAT ==========
Valid UUID format: 10000
Invalid UUID format: 0

========== SALE ID NULL CHECK ==========
Missing SaleIDs: 0

========== SALE ID UNIQUENESS CHECK ==========
Result: SaleID is unique and suitable as a source transaction identifier.

In [ ]:
print("========== SALES DATE/TIME PROFILE ==========")

sales_timestamp = pd.to_datetime(
    sales["Timestamp"],
    errors="coerce"
)

print("Total timestamps:", len(sales_timestamp))
print("Missing timestamps:", sales_timestamp.isna().sum())

print("\n========== DATE RANGE ==========")

print("Earliest transaction:", sales_timestamp.min())
print("Latest transaction:", sales_timestamp.max())

print("\n========== UNIQUE DATES ==========")

print("Unique transaction dates:",
      sales_timestamp.dt.date.nunique())

print("\n========== SALES BY MONTH ==========")

monthly_sales_count = (
    sales_timestamp
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

display(
    monthly_sales_count.rename("Transaction Count").to_frame()
)

print("\n========== SALES BY DAY OF WEEK ==========")

weekday_counts = (
    sales_timestamp
    .dt.day_name()
    .value_counts()
)

weekday_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

weekday_counts = weekday_counts.reindex(weekday_order)

display(
    weekday_counts.rename("Transaction Count").to_frame()
)

========== SALES DATE/TIME PROFILE ==========
Total timestamps: 10000
Missing timestamps: 0

========== DATE RANGE ==========
Earliest transaction: 2024-06-01 10:03:00
Latest transaction: 2024-11-28 09:38:00

========== UNIQUE DATES ==========
Unique transaction dates: 181

========== SALES BY MONTH ==========

           Transaction Count
Timestamp
2024-06                 1641
2024-07                 1729
2024-08                 1729
2024-09                 1676
2024-10                 1720
2024-11                 1505

========== SALES BY DAY OF WEEK ==========

           Transaction Count
Timestamp
Monday                  1413
Tuesday                 1477
Wednesday               1469
Thursday                1417
Friday                  1347
Saturday                1463
Sunday                  1414

In [ ]:
print("========== CUSTOMER DEMOGRAPHIC PROFILE ==========")

print("\n========== GENDER ==========")

gender_profile = (
    deduplicated_customers["Gender"]
    .fillna("Missing")
    .astype(str)
    .value_counts()
)

display(
    gender_profile.rename("Customer Count").to_frame()
)

print("\n========== REGION ==========")

region_profile = (
    deduplicated_customers["Region"]
    .fillna("Missing")
    .astype(str)
    .value_counts()
)

display(
    region_profile.rename("Customer Count").to_frame()
)

print("\n========== CUSTOMER NAME COMPLETENESS ==========")

print(
    "Missing FirstName:",
    deduplicated_customers["FirstName"].isna().sum()
)

print(
    "Missing LastName:",
    deduplicated_customers["LastName"].isna().sum()
)

print(
    "Complete names:",
    (
        deduplicated_customers["FirstName"].notna()
        &
        deduplicated_customers["LastName"].notna()
    ).sum()
)

print("\n========== UNIQUE CUSTOMER DEMOGRAPHICS ==========")

print(
    "Unique Gender values:",
    deduplicated_customers["Gender"].nunique()
)

print(
    "Unique Region values:",
    deduplicated_customers["Region"].nunique()
)

print(
    "Unique FirstName values:",
    deduplicated_customers["FirstName"].nunique()
)

========== CUSTOMER DEMOGRAPHIC PROFILE ==========

========== GENDER ==========

        Customer Count
Gender
M                  285
male               249
Male               249
F                   80
female              75
Female              62

========== REGION ==========

             Customer Count
Region
Texaz                   102
NY                      102
Californiya             102
New York                 96
Ohho                     94
Nw York                  92
Texas                    92
california               90
New Yorkk                87
Ohio                     81
Missing                  62

========== CUSTOMER NAME COMPLETENESS ==========
Missing FirstName: 0
Missing LastName: 290
Complete names: 710

========== UNIQUE CUSTOMER DEMOGRAPHICS ==========
Unique Gender values: 6
Unique Region values: 10
Unique FirstName values: 318

In [ ]:
print("========== CUSTOMER VALUE STANDARDIZATION PROFILE ==========")

print("\n========== GENDER VALUES ==========")

gender_values = (
    deduplicated_customers["Gender"]
    .astype(str)
    .value_counts()
    .sort_index()
)

display(
    gender_values.rename("Count").to_frame()
)

print("\n========== REGION VALUES ==========")

region_values = (
    deduplicated_customers["Region"]
    .fillna("Missing")
    .astype(str)
    .value_counts()
    .sort_index()
)

display(
    region_values.rename("Count").to_frame()
)

print("\n========== REGION NORMALIZATION GROUPS ==========")

region_normalization_groups = {
    "Ohio": ["Ohio", "Ohho"],
    "Texas": ["Texas", "Texaz"],
    "California": ["california", "Californiya"],
    "New York": ["NY", "New York", "Nw York", "New Yorkk"]
}

for standard_region, variants in region_normalization_groups.items():
    total_count = sum(
        region_values.get(variant, 0)
        for variant in variants
    )

    print(
        f"{standard_region}: "
        f"{variants} -> {total_count} customers"
    )

print("\n========== MISSING REGION ==========")

print(
    "Missing Region:",
    deduplicated_customers["Region"].isna().sum()
)

========== CUSTOMER VALUE STANDARDIZATION PROFILE ==========

========== GENDER VALUES ==========

        Count
Gender
F          80
Female     62
M         285
Male      249
female     75
male      249

========== REGION VALUES ==========

             Count
Region
Californiya    102
Missing         62
NY             102
New York        96
New Yorkk       87
Nw York         92
Ohho            94
Ohio            81
Texas           92
Texaz          102
california      90

========== REGION NORMALIZATION GROUPS ==========
Ohio: ['Ohio', 'Ohho'] -> 175 customers
Texas: ['Texas', 'Texaz'] -> 194 customers
California: ['california', 'Californiya'] -> 192 customers
New York: ['NY', 'New York', 'Nw York', 'New Yorkk'] -> 377 customers

========== MISSING REGION ==========
Missing Region: 62

In [ ]:
print("========== DUPLICATE CUSTOMER CONSISTENCY CHECK ==========")

customer_duplicate_groups = (
    customers.groupby("CustomerID")
    .agg(
        RecordCount=("CustomerID", "size"),
        UniqueFirstName=("FirstName", "nunique"),
        UniqueLastName=("LastName", "nunique"),
        UniqueGender=("Gender", "nunique"),
        UniqueRegion=("Region", "nunique"),
        UniqueSSN=("SSN", "nunique")
    )
    .reset_index()
)

duplicate_customer_groups = customer_duplicate_groups[
    customer_duplicate_groups["RecordCount"] > 1
].copy()

print(
    "CustomerIDs with duplicate records:",
    len(duplicate_customer_groups)
)

print(
    "Duplicate groups with FirstName conflicts:",
    (duplicate_customer_groups["UniqueFirstName"] > 1).sum()
)

print(
    "Duplicate groups with LastName conflicts:",
    (duplicate_customer_groups["UniqueLastName"] > 1).sum()
)

print(
    "Duplicate groups with Gender conflicts:",
    (duplicate_customer_groups["UniqueGender"] > 1).sum()
)

print(
    "Duplicate groups with Region conflicts:",
    (duplicate_customer_groups["UniqueRegion"] > 1).sum()
)

print(
    "Duplicate groups with SSN conflicts:",
    (duplicate_customer_groups["UniqueSSN"] > 1).sum()
)

print("\n========== DUPLICATE GROUP SUMMARY ==========")

display(
    duplicate_customer_groups.head(10)
)

========== DUPLICATE CUSTOMER CONSISTENCY CHECK ==========
CustomerIDs with duplicate records: 100
Duplicate groups with FirstName conflicts: 0
Duplicate groups with LastName conflicts: 0
Duplicate groups with Gender conflicts: 0
Duplicate groups with Region conflicts: 0
Duplicate groups with SSN conflicts: 0

========== DUPLICATE GROUP SUMMARY ==========

,CustomerID,RecordCount,UniqueFirstName,UniqueLastName,UniqueGender,UniqueRegion,UniqueSSN
22,C0023,2,1,1,1,1,1
25,C0026,2,1,1,1,1,1
46,C0047,2,1,1,1,1,1
47,C0048,2,1,1,1,1,1
49,C0050,2,1,1,1,1,1
50,C0051,2,1,0,1,0,1
62,C0063,2,1,0,1,1,1
66,C0067,2,1,1,1,1,1
126,C0127,2,1,1,1,0,1
127,C0128,2,1,0,1,1,1

In [ ]:
print("========== SALES MISSING-VALUE PATTERN ==========")

sales_amount_missing = sales["SalesAmount"].isna()
quantity_missing = sales["Quantity"].isna()

both_missing = sales_amount_missing & quantity_missing
amount_only_missing = sales_amount_missing & ~quantity_missing
quantity_only_missing = quantity_missing & ~sales_amount_missing
neither_missing = ~sales_amount_missing & ~quantity_missing

print("Total Sales rows:", len(sales))

print("\n========== MISSING VALUE COMBINATIONS ==========")

print(
    "Both SalesAmount and Quantity missing:",
    both_missing.sum()
)

print(
    "Only SalesAmount missing:",
    amount_only_missing.sum()
)

print(
    "Only Quantity missing:",
    quantity_only_missing.sum()
)

print(
    "Neither missing:",
    neither_missing.sum()
)

print("\n========== PERCENTAGE OF SALES ROWS ==========")

print(
    "Both missing: {:.2f}%".format(
        both_missing.mean() * 100
    )
)

print(
    "Only SalesAmount missing: {:.2f}%".format(
        amount_only_missing.mean() * 100
    )
)

print(
    "Only Quantity missing: {:.2f}%".format(
        quantity_only_missing.mean() * 100
    )
)

print("\n========== MISSING SALES RECORDS SAMPLE ==========")

missing_sales = sales[
    sales_amount_missing | quantity_missing
].copy()

display(
    missing_sales[
        [
            "SaleID",
            "ProductID",
            "CustomerID",
            "SalesAmount",
            "Quantity",
            "Timestamp"
        ]
    ].head(20)
)

========== SALES MISSING-VALUE PATTERN ==========
Total Sales rows: 10000

========== MISSING VALUE COMBINATIONS ==========
Both SalesAmount and Quantity missing: 7
Only SalesAmount missing: 490
Only Quantity missing: 106
Neither missing: 9397

========== PERCENTAGE OF SALES ROWS ==========
Both missing: 0.07%
Only SalesAmount missing: 4.90%
Only Quantity missing: 1.06%

========== MISSING SALES RECORDS SAMPLE ==========

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,NaN,50.0,2024-07-06T23:39:00
7,f5953c0c-e9bc-489a-9333-1e0c0a81d873,1027,C0019,1635.15,NaN,2024-08-30T19:07:00
24,ea120dd2-45d7-4ad7-8368-b0467279d9d9,1003,C0422,NaN,35.0,2024-06-19T23:12:00
52,182d4630-5e13-47ca-8047-172d8bb80d9b,1036,C0484,NaN,44.0,2024-07-09T12:50:00
67,cfc48ad9-4630-44e4-8348-b6651673df95,1007,C0482,NaN,10.0,2024-09-08T22:43:00
96,7e9f0322-ab86-47f5-a766-3ca0eac9e622,1047,C0798,NaN,7.0,2024-07-20T01:19:00
124,58475ef3-15ef-4fd6-b2e0-a7c6db4fcce4,1023,C1000,620.28,NaN,2024-09-12T11:51:00
190,40ea2216-7874-4a56-b703-37295861e5af,1024,C0136,1862.32,NaN,2024-07-04T15:41:00
215,ffbbb1d8-599a-4aab-b582-86d3d3ee5037,1029,C0878,NaN,28.0,2024-08-02T12:59:00
225,fa171b13-bdb8-426b-a555-b44e6adf39ad,1041,C0858,NaN,45.0,2024-10-26T13:40:00
238,ab5d7adb-cede-4dd5-b830-4a8d1e58a604,1041,C0307,1424.05,NaN,2024-10-12T22:26:00
242,625f9ab4-53a0-45b7-9e88-9f13127e8db7,1031,C0205,NaN,45.0,2024-09-03T08:01:00
261,815c4d88-a254-44c8-afec-67573870eeee,1033,C0125,NaN,22.0,2024-08-17T09:20:00
275,dc8b7d00-98f9-4f4e-99c9-7c652387674a,1012,C0668,NaN,28.0,2024-07-19T02:11:00
280,8ee802bb-52eb-4c19-951e-d54680a6300e,1041,C0377,1333.88,NaN,2024-10-13T11:44:00
281,271d7efa-c09c-4aef-b9f6-653d276c5a63,1016,C0515,NaN,34.0,2024-09-15T15:07:00
295,c3d80a3d-844e-410d-9f56-7a864f330fd7,1043,C0690,NaN,27.0,2024-09-06T09:56:00
296,d22273cb-1282-496c-afc2-81aa1181a10e,1034,C0821,1492.62,NaN,2024-08-20T20:50:00
316,1dcd719e-1541-47fe-b08c-7103a777400c,1031,C0533,NaN,NaN,2024-10-05T14:58:00
347,aef952e1-8c80-42b1-bad4-14941ceda93c,1047,C0678,NaN,21.0,2024-07-24T15:08:00

In [ ]:
print("========== MISSING SALES DATA BY PRODUCT ==========")

missing_sales = sales[
    sales["SalesAmount"].isna() | sales["Quantity"].isna()
].copy()

product_missing_profile = (
    missing_sales
    .groupby("ProductID")
    .agg(
        MissingSalesAmount=("SalesAmount", lambda x: x.isna().sum()),
        MissingQuantity=("Quantity", lambda x: x.isna().sum()),
        TotalMissingRows=("ProductID", "size")
    )
    .reset_index()
    .sort_values("TotalMissingRows", ascending=False)
)

print(
    "Products affected by missing SalesAmount or Quantity:",
    len(product_missing_profile)
)

display(product_missing_profile.head(20))

print("\n========== MISSINGNESS PERCENTAGE BY PRODUCT ==========")

product_total_counts = (
    sales["ProductID"]
    .value_counts()
    .rename("TotalSalesRows")
    .reset_index()
    .rename(columns={"index": "ProductID"})
)

product_missing_profile = product_missing_profile.merge(
    product_total_counts,
    on="ProductID",
    how="left"
)

product_missing_profile["MissingRowPercentage"] = (
    product_missing_profile["TotalMissingRows"]
    / product_missing_profile["TotalSalesRows"]
    * 100
)

display(
    product_missing_profile
    .sort_values("MissingRowPercentage", ascending=False)
    .head(20)
)

========== MISSING SALES DATA BY PRODUCT ==========
Products affected by missing SalesAmount or Quantity: 50

    ProductID  MissingSalesAmount  MissingQuantity  TotalMissingRows
32       1032                  17                3                20
10       1010                  16                2                18
25       1025                  17                1                18
41       1041                  11                8                18
5        1005                  15                2                17
0        1000                  13                3                16
26       1026                  11                4                15
8        1008                  15                0                15
4        1004                  13                2                15
1        1001                  13                1                14
16       1016                  11                3                14
18       1018                  13                1                14
19       1019                  11                2                13
36       1036                  12                1                13
33       1033                  12                1                13
12       1012                  12                1                13
6        1006                  13                0                13
44       1044                  10                4                13
47       1047                  10                3                13
2        1002                  10                2                12

========== MISSINGNESS PERCENTAGE BY PRODUCT ==========

,ProductID,MissingSalesAmount,MissingQuantity,TotalMissingRows,TotalSalesRows,MissingRowPercentage
2,1025,17,1,18,186,9.677419
3,1041,11,8,18,191,9.424084
4,1005,15,2,17,196,8.673469
0,1032,17,3,20,232,8.620690
1,1010,16,2,18,212,8.490566
6,1026,11,4,15,196,7.653061
5,1000,13,3,16,210,7.619048
12,1019,11,2,13,174,7.471264
10,1016,11,3,14,188,7.446809
17,1044,10,4,13,178,7.303371
7,1008,15,0,15,208,7.211538
8,1004,13,2,15,210,7.142857
9,1001,13,1,14,197,7.106599
11,1018,13,1,14,198,7.070707
13,1036,12,1,13,188,6.914894
15,1012,12,1,13,195,6.666667
24,1028,10,2,12,180,6.666667
21,1049,10,3,12,187,6.417112
35,1023,6,5,11,174,6.321839
16,1006,13,0,13,207,6.280193

In [ ]:
print("========== MISSING SALES DATA BY CUSTOMER ==========")

customer_missing_profile = (
    missing_sales
    .groupby("CustomerID")
    .agg(
        MissingSalesAmount=("SalesAmount", lambda x: x.isna().sum()),
        MissingQuantity=("Quantity", lambda x: x.isna().sum()),
        TotalMissingRows=("CustomerID", "size")
    )
    .reset_index()
    .sort_values("TotalMissingRows", ascending=False)
)

print(
    "Customers affected by missing SalesAmount or Quantity:",
    len(customer_missing_profile)
)

display(
    customer_missing_profile.head(20)
)

print("\n========== MISSINGNESS PERCENTAGE BY CUSTOMER ==========")

customer_total_counts = (
    sales["CustomerID"]
    .value_counts()
    .rename("TotalSalesRows")
    .reset_index()
    .rename(columns={"index": "CustomerID"})
)

customer_missing_profile = customer_missing_profile.merge(
    customer_total_counts,
    on="CustomerID",
    how="left"
)

customer_missing_profile["MissingRowPercentage"] = (
    customer_missing_profile["TotalMissingRows"]
    / customer_missing_profile["TotalSalesRows"]
    * 100
)

display(
    customer_missing_profile
    .sort_values(
        "MissingRowPercentage",
        ascending=False
    )
    .head(20)
)

========== MISSING SALES DATA BY CUSTOMER ==========
Customers affected by missing SalesAmount or Quantity: 446

    CustomerID  MissingSalesAmount  MissingQuantity  TotalMissingRows
372      C0837                   3                3                 4
236      C0515                   2                2                 4
9        C0023                   4                0                 4
106      C0235                   2                2                 4
160      C0345                   4                0                 4
303      C0678                   3                0                 3
44       C0111                   3                0                 3
349      C0792                   1                2                 3
339      C0769                   2                1                 3
253      C0559                   2                1                 3
260      C0586                   3                0                 3
286      C0640                   2                1                 3
211      C0446                   3                0                 3
172      C0378                   3                0                 3
173      C0380                   3                0                 3
198      C0422                   3                0                 3
179      C0390                   2                1                 3
152      C0331                   3                0                 3
143      C0313                   2                1                 3
118      C0256                   3                0                 3

========== MISSINGNESS PERCENTAGE BY CUSTOMER ==========

,CustomerID,MissingSalesAmount,MissingQuantity,TotalMissingRows,TotalSalesRows,MissingRowPercentage
15,C0422,3,0,3,5,60.000000
118,C0088,2,0,2,4,50.000000
20,C0271,3,0,3,7,42.857143
117,C0311,2,0,2,5,40.000000
101,C0410,2,0,2,5,40.000000
75,C0664,2,0,2,5,40.000000
69,C0701,1,1,2,6,33.333333
444,C0035,1,0,1,3,33.333333
365,C0789,0,1,1,3,33.333333
419,C0926,1,0,1,3,33.333333
321,C0740,1,0,1,3,33.333333
260,C0258,1,0,1,3,33.333333
77,C0584,2,0,2,6,33.333333
9,C0559,2,1,3,9,33.333333
54,C0961,2,0,2,6,33.333333
90,C0487,2,0,2,6,33.333333
23,C0152,1,2,3,10,30.000000
10,C0586,3,0,3,10,30.000000
7,C0792,1,2,3,10,30.000000
5,C0678,3,0,3,10,30.000000

In [ ]:
print("========== CUSTOMER SALES COVERAGE ==========")

customer_sales_profile = (
    sales.groupby("CustomerID")
    .agg(
        TotalTransactions=("SaleID", "count"),
        TotalQuantity=("Quantity", "sum"),
        TotalSalesAmount=("SalesAmount", "sum")
    )
    .reset_index()
)

print("Customers in Customer table:",
      deduplicated_customers["CustomerID"].nunique())

print("Customers with at least one sale:",
      customer_sales_profile["CustomerID"].nunique())

print(
    "Customers with no sales:",
    deduplicated_customers["CustomerID"].nunique()
    - customer_sales_profile["CustomerID"].nunique()
)

print("\n========== TRANSACTION DISTRIBUTION PER CUSTOMER ==========")

print(
    customer_sales_profile["TotalTransactions"].describe()
)

print("\n========== TOP CUSTOMERS BY TRANSACTION COUNT ==========")

display(
    customer_sales_profile
    .sort_values("TotalTransactions", ascending=False)
    .head(20)
)

========== CUSTOMER SALES COVERAGE ==========
Customers in Customer table: 1000
Customers with at least one sale: 1000
Customers with no sales: 0

========== TRANSACTION DISTRIBUTION PER CUSTOMER ==========
count    1000.000000
mean       10.000000
std         4.437532
min         1.000000
25%         7.000000
50%         9.000000
75%        12.000000
max        28.000000
Name: TotalTransactions, dtype: float64

========== TOP CUSTOMERS BY TRANSACTION COUNT ==========

    CustomerID  TotalTransactions  TotalQuantity  TotalSalesAmount
516      C0517                 28          788.0          26160.66
964      C0965                 27          774.0          88483.71
779      C0780                 26          508.0          29914.33
834      C0835                 25          700.0          22793.11
741      C0742                 25          527.0          23809.89
399      C0400                 24          564.0          21639.92
467      C0468                 24          721.0          20280.91
317      C0318                 24          597.0          20714.40
514      C0515                 24          526.0          25161.82
260      C0261                 24          652.0          19860.67
694      C0695                 24          691.0          25925.24
734      C0735                 24          623.0          21524.29
186      C0187                 24          573.0          24768.55
218      C0219                 24          560.0          25589.33
988      C0989                 24          530.0          23340.99
639      C0640                 24          636.0          79226.89
198      C0199                 23          624.0          24028.59
132      C0133                 23          642.0          19732.21
554      C0555                 23          626.0          96522.37
708      C0709                 23          513.0          22268.48

In [ ]:
print("========== PRODUCT SALES COVERAGE ==========")

product_sales_profile = (
    sales.groupby("ProductID")
    .agg(
        TotalTransactions=("SaleID", "count"),
        TotalQuantity=("Quantity", "sum"),
        TotalSalesAmount=("SalesAmount", "sum")
    )
    .reset_index()
)

print("Products in Product table:",
      products["ProductID"].nunique())

print("Products with at least one sale:",
      product_sales_profile["ProductID"].nunique())

print(
    "Products with no sales:",
    products["ProductID"].nunique()
    - product_sales_profile["ProductID"].nunique()
)

print("\n========== TRANSACTION DISTRIBUTION PER PRODUCT ==========")

print(
    product_sales_profile["TotalTransactions"].describe()
)

print("\n========== TOP PRODUCTS BY TRANSACTION COUNT ==========")

display(
    product_sales_profile
    .sort_values("TotalTransactions", ascending=False)
    .head(20)
)

print("\n========== PRODUCTS WITH NO SALES ==========")

products_without_sales = products.loc[
    ~products["ProductID"].isin(product_sales_profile["ProductID"]),
    ["ProductID", "ProductName", "Category"]
]

display(products_without_sales)

========== PRODUCT SALES COVERAGE ==========
Products in Product table: 50
Products with at least one sale: 50
Products with no sales: 0

========== TRANSACTION DISTRIBUTION PER PRODUCT ==========
count     50.0000
mean     200.0000
std       13.5481
min      174.0000
25%      191.2500
50%      198.5000
75%      210.0000
max      232.0000
Name: TotalTransactions, dtype: float64

========== TOP PRODUCTS BY TRANSACTION COUNT ==========

    ProductID  TotalTransactions  TotalQuantity  TotalSalesAmount
32       1032                232         5770.0         384252.42
27       1027                228         5679.0         348233.06
31       1031                219         5676.0         393984.96
33       1033                219         5573.0         286367.91
2        1002                219         5375.0         207770.26
47       1047                214         5569.0         403402.83
9        1009                214         5517.0         262536.75
30       1030                213         5164.0         647238.46
7        1007                212         5597.0         327688.39
10       1010                212         5113.0         311833.16
13       1013                211         5113.0         208142.02
38       1038                210         5405.0         221022.00
45       1045                210         5131.0         255708.01
0        1000                210         5265.0         208776.03
4        1004                210         5125.0         265083.78
46       1046                210         5594.0         246945.24
8        1008                208         5281.0         308985.33
11       1011                207         4649.0         307591.77
6        1006                207         5169.0         373000.63
48       1048                204         5026.0         225559.28

========== PRODUCTS WITH NO SALES ==========

Empty DataFrame
Columns: [ProductID, ProductName, Category]
Index: []

In [ ]:
print("========== REGIONAL SALES & CUSTOMER PROFILE ==========")

# Create a working copy so the original customer data is not modified
customer_region_profile = deduplicated_customers[
    ["CustomerID", "Region", "Gender"]
].copy()

# Normalize region values for profiling only
customer_region_profile["Region_Normalized"] = (
    customer_region_profile["Region"]
    .astype("string")
    .str.strip()
    .str.lower()
)

region_map = {
    "ohio": "Ohio",
    "ohho": "Ohio",
    "texas": "Texas",
    "texaz": "Texas",
    "california": "California",
    "californiya": "California",
    "ny": "New York",
    "new york": "New York",
    "nw york": "New York",
    "new yorkk": "New York"
}

customer_region_profile["Region_Normalized"] = (
    customer_region_profile["Region_Normalized"]
    .map(region_map)
    .fillna("Missing")
)

# Merge sales with customer region
regional_sales = sales.merge(
    customer_region_profile[
        ["CustomerID", "Region_Normalized"]
    ],
    on="CustomerID",
    how="left"
)

region_summary = (
    regional_sales.groupby("Region_Normalized")
    .agg(
        Customers=("CustomerID", "nunique"),
        Transactions=("SaleID", "count"),
        TotalQuantity=("Quantity", "sum"),
        TotalSalesAmount=("SalesAmount", "sum")
    )
    .reset_index()
    .sort_values("TotalSalesAmount", ascending=False)
)

print("========== REGION SUMMARY ==========")
display(region_summary)

print("\n========== REGION CUSTOMER COVERAGE ==========")

print(
    "Unique regions after normalization:",
    customer_region_profile["Region_Normalized"].nunique()
)

print(
    "Customers with missing region:",
    (
        customer_region_profile["Region_Normalized"]
        == "Missing"
    ).sum()
)

print("\n========== SALES BY REGION ==========")

display(
    region_summary[
        [
            "Region_Normalized",
            "Customers",
            "Transactions",
            "TotalQuantity",
            "TotalSalesAmount"
        ]
    ]
)

========== REGIONAL SALES & CUSTOMER PROFILE ==========
========== REGION SUMMARY ==========

  Region_Normalized  Customers  Transactions  TotalQuantity  TotalSalesAmount
2          New York        377          3799        94402.0        5247211.77
4             Texas        194          1876        46690.0        2655131.48
3              Ohio        175          1785        44218.0        2427709.79
0        California        192          1894        47891.0        2410565.36
1           Missing         62           646        16264.0         915191.37

========== REGION CUSTOMER COVERAGE ==========
Unique regions after normalization: 5
Customers with missing region: 62

========== SALES BY REGION ==========

  Region_Normalized  Customers  Transactions  TotalQuantity  TotalSalesAmount
2          New York        377          3799        94402.0        5247211.77
4             Texas        194          1876        46690.0        2655131.48
3              Ohio        175          1785        44218.0        2427709.79
0        California        192          1894        47891.0        2410565.36
1           Missing         62           646        16264.0         915191.37

In [ ]:
print("========== MONTHLY SALES PERFORMANCE ==========")

# Convert Timestamp to datetime for analysis
sales_date_profile = sales.copy()

sales_date_profile["Timestamp"] = pd.to_datetime(
    sales_date_profile["Timestamp"],
    errors="coerce"
)

# Create monthly period
sales_date_profile["YearMonth"] = (
    sales_date_profile["Timestamp"]
    .dt.to_period("M")
    .astype(str)
)

monthly_sales = (
    sales_date_profile
    .groupby("YearMonth")
    .agg(
        Transactions=("SaleID", "count"),
        TotalQuantity=("Quantity", "sum"),
        TotalSalesAmount=("SalesAmount", "sum")
    )
    .reset_index()
)

# Calculate average transaction value
monthly_sales["AverageTransactionValue"] = (
    monthly_sales["TotalSalesAmount"]
    / monthly_sales["Transactions"]
)

print("========== MONTHLY SALES SUMMARY ==========")

display(monthly_sales)

print("\n========== HIGHEST SALES MONTH ==========")

highest_sales_month = monthly_sales.loc[
    monthly_sales["TotalSalesAmount"].idxmax()
]

display(highest_sales_month.to_frame().T)

print("\n========== LOWEST SALES MONTH ==========")

lowest_sales_month = monthly_sales.loc[
    monthly_sales["TotalSalesAmount"].idxmin()
]

display(lowest_sales_month.to_frame().T)

print("\n========== MONTHLY COVERAGE ==========")

print("Number of months:", monthly_sales["YearMonth"].nunique())
print("First month:", monthly_sales["YearMonth"].min())
print("Last month:", monthly_sales["YearMonth"].max())

========== MONTHLY SALES PERFORMANCE ==========
========== MONTHLY SALES SUMMARY ==========

,YearMonth,Transactions,TotalQuantity,TotalSalesAmount,AverageTransactionValue
0,2024-06,1641,41782.0,2044776.94,1246.055417
1,2024-07,1729,42673.0,2212950.47,1279.901949
2,2024-08,1729,43616.0,2688782.43,1555.108404
3,2024-09,1676,41553.0,2102306.85,1254.359696
4,2024-10,1720,43127.0,2319876.14,1348.765198
5,2024-11,1505,36714.0,2287116.94,1519.679030

========== HIGHEST SALES MONTH ==========

,YearMonth,Transactions,TotalQuantity,TotalSalesAmount,AverageTransactionValue
2,2024-08,1729,43616.0,2688782.43,1555.108404

========== LOWEST SALES MONTH ==========

,YearMonth,Transactions,TotalQuantity,TotalSalesAmount,AverageTransactionValue
0,2024-06,1641,41782.0,2044776.94,1246.055417

========== MONTHLY COVERAGE ==========
Number of months: 6
First month: 2024-06
Last month: 2024-11

In [ ]:
print("========== OVERALL SALES & DATA COMPLETENESS ==========")

total_rows = len(sales)

sales_amount_missing = sales["SalesAmount"].isna().sum()
quantity_missing = sales["Quantity"].isna().sum()

valid_sales_amount = sales["SalesAmount"].notna().sum()
valid_quantity = sales["Quantity"].notna().sum()

print("Total sales transactions:", total_rows)

print("\n========== SALES AMOUNT ==========")
print("Valid SalesAmount:", valid_sales_amount)
print("Missing SalesAmount:", sales_amount_missing)
print(
    "SalesAmount completeness:",
    round((valid_sales_amount / total_rows) * 100, 2), "%"
)

print("\n========== QUANTITY ==========")
print("Valid Quantity:", valid_quantity)
print("Missing Quantity:", quantity_missing)
print(
    "Quantity completeness:",
    round((valid_quantity / total_rows) * 100, 2), "%"
)

print("\n========== CUSTOMER DATA ==========")
print("Unique customers:", deduplicated_customers["CustomerID"].nunique())
print(
    "Customers with missing LastName:",
    deduplicated_customers["LastName"].isna().sum()
)
print(
    "Customers with missing Region:",
    deduplicated_customers["Region"].isna().sum()
)

print("\n========== PRODUCT DATA ==========")
print("Unique products:", products["ProductID"].nunique())
print("Unique categories:", products["Category"].nunique())

print("\n========== SALES TOTALS ==========")

print(
    "Total SalesAmount (excluding missing):",
    round(sales["SalesAmount"].sum(), 2)
)

print(
    "Total Quantity (excluding missing):",
    round(sales["Quantity"].sum(), 2)
)

print(
    "Average SalesAmount:",
    round(sales["SalesAmount"].mean(), 2)
)

print(
    "Average Quantity:",
    round(sales["Quantity"].mean(), 2)
)

========== OVERALL SALES & DATA COMPLETENESS ==========
Total sales transactions: 10000

========== SALES AMOUNT ==========
Valid SalesAmount: 9503
Missing SalesAmount: 497
SalesAmount completeness: 95.03 %

========== QUANTITY ==========
Valid Quantity: 9887
Missing Quantity: 113
Quantity completeness: 98.87 %

========== CUSTOMER DATA ==========
Unique customers: 1000
Customers with missing LastName: 290
Customers with missing Region: 62

========== PRODUCT DATA ==========
Unique products: 50
Unique categories: 4

========== SALES TOTALS ==========
Total SalesAmount (excluding missing): 13655809.77
Total Quantity (excluding missing): 249465.0
Average SalesAmount: 1437.0
Average Quantity: 25.23

In [ ]:
print("========== FINAL CROSS-TABLE CONSISTENCY CHECK ==========")

# ---------- SALES ↔ CUSTOMER ----------
sales_customer_ids = set(sales["CustomerID"].dropna().unique())
customer_ids = set(deduplicated_customers["CustomerID"].dropna().unique())

missing_customers = sales_customer_ids - customer_ids
extra_customers = customer_ids - sales_customer_ids

print("========== SALES ↔ CUSTOMER ==========")
print("Unique CustomerIDs in Sales:", len(sales_customer_ids))
print("Unique CustomerIDs in Customer table:", len(customer_ids))
print("Sales CustomerIDs missing from Customer table:",
      len(missing_customers))
print("CustomerIDs with no sales:",
      len(extra_customers))


# ---------- SALES ↔ PRODUCT ----------
sales_product_ids = set(sales["ProductID"].dropna().unique())
product_ids = set(products["ProductID"].dropna().unique())

missing_products = sales_product_ids - product_ids
extra_products = product_ids - sales_product_ids

print("\n========== SALES ↔ PRODUCT ==========")
print("Unique ProductIDs in Sales:", len(sales_product_ids))
print("Unique ProductIDs in Product table:", len(product_ids))
print("Sales ProductIDs missing from Product table:",
      len(missing_products))
print("Products with no sales:",
      len(extra_products))


# ---------- SALES NUMERIC VALIDITY ----------
negative_sales = (sales["SalesAmount"] < 0).sum()
zero_sales = (sales["SalesAmount"] == 0).sum()

negative_quantity = (sales["Quantity"] < 0).sum()
zero_quantity = (sales["Quantity"] == 0).sum()

print("\n========== NUMERIC BUSINESS VALIDATION ==========")
print("Negative SalesAmount:", negative_sales)
print("Zero SalesAmount:", zero_sales)
print("Negative Quantity:", negative_quantity)
print("Zero Quantity:", zero_quantity)


# ---------- TIMESTAMP ----------
invalid_timestamps = pd.to_datetime(
    sales["Timestamp"],
    errors="coerce"
).isna().sum()

print("\n========== TIMESTAMP VALIDATION ==========")
print("Invalid / unreadable timestamps:", invalid_timestamps)


# ---------- PRODUCT MASTER ----------
duplicate_product_ids = products["ProductID"].duplicated().sum()
duplicate_product_names = products["ProductName"].duplicated().sum()

print("\n========== PRODUCT MASTER VALIDATION ==========")
print("Duplicate ProductIDs:", duplicate_product_ids)
print("Duplicate ProductNames:", duplicate_product_names)


# ---------- CUSTOMER MASTER ----------
duplicate_customer_ids = deduplicated_customers["CustomerID"].duplicated().sum()

print("\n========== CUSTOMER MASTER VALIDATION ==========")
print("Duplicate CustomerIDs after deduplication:",
      duplicate_customer_ids)


# ---------- FINAL STATUS ----------
all_checks_passed = (
    len(missing_customers) == 0
    and len(extra_customers) == 0
    and len(missing_products) == 0
    and len(extra_products) == 0
    and negative_sales == 0
    and zero_sales == 0
    and negative_quantity == 0
    and zero_quantity == 0
    and invalid_timestamps == 0
    and duplicate_product_ids == 0
    and duplicate_product_names == 0
    and duplicate_customer_ids == 0
)

print("\n========== FINAL PHASE 1 VALIDATION STATUS ==========")

if all_checks_passed:
    print("PASS: Cross-table and business consistency checks passed.")
else:
    print("REVIEW REQUIRED: One or more consistency checks need attention.")

========== FINAL CROSS-TABLE CONSISTENCY CHECK ==========
========== SALES ↔ CUSTOMER ==========
Unique CustomerIDs in Sales: 1000
Unique CustomerIDs in Customer table: 1000
Sales CustomerIDs missing from Customer table: 0
CustomerIDs with no sales: 0

========== SALES ↔ PRODUCT ==========
Unique ProductIDs in Sales: 50
Unique ProductIDs in Product table: 50
Sales ProductIDs missing from Product table: 0
Products with no sales: 0

========== NUMERIC BUSINESS VALIDATION ==========
Negative SalesAmount: 0
Zero SalesAmount: 0
Negative Quantity: 0
Zero Quantity: 0

========== TIMESTAMP VALIDATION ==========
Invalid / unreadable timestamps: 0

========== PRODUCT MASTER VALIDATION ==========
Duplicate ProductIDs: 0
Duplicate ProductNames: 0

========== CUSTOMER MASTER VALIDATION ==========
Duplicate CustomerIDs after deduplication: 0

========== FINAL PHASE 1 VALIDATION STATUS ==========
PASS: Cross-table and business consistency checks passed.

In [ ]:
print("========== UPDATED DATA PREVIEW ==========")

print("\n========== CUSTOMERS ==========")
print("Rows:", len(deduplicated_customers))
print("Columns:", list(deduplicated_customers.columns))
display(deduplicated_customers.head(20))

print("\n========== SALES ==========")
print("Rows:", len(sales))
print("Columns:", list(sales.columns))
display(sales.head(20))

print("\n========== PRODUCTS ==========")
print("Rows:", len(products))
print("Columns:", list(products.columns))
display(products.head(20))

========== UPDATED DATA PREVIEW ==========

========== CUSTOMERS ==========
Rows: 1000
Columns: ['CustomerID', 'FirstName', 'LastName', 'Gender', 'Region', 'SSN']

   CustomerID FirstName   LastName  Gender       Region          SSN
0       C0001   Gregory     Miller       M         Ohho    082573197
1       C0002    Marvin       None    male   california  309-6256-21
2       C0003   Gregory      Smith    Male    New Yorkk    407071725
3       C0004    Edward      Davis    male         Ohho  948.18.5740
4       C0005  Reginald     Dawson    male        Texas  975.72.3056
5       C0006  Virginia     Bryant  Female         Ohio  981/72/7452
6       C0007  Benjamin   Shepherd    Male         Ohho    048008736
7       C0008    Robert     Pierce    Male     New York  009/01/2352
8       C0009    Samuel  Mcconnell    male  Californiya  007-3486-87
9       C0010     Jason       None    Male           NY  785/76/9341
10      C0011     Jason    Morales    male         None  325-2353-01
11      C0012   Charles       None    Male     New York  239.14.0962
12      C0013   Brandon       None       M         Ohio  573-3595-11
13      C0014   Jeffery    Cabrera       M    New Yorkk  705.13.1809
14      C0015   William   Gonzalez    male     New York  058-13-1272
15      C0016       Joe    Barnett       M         Ohho  995/87/4707
16      C0017    Angela   Cantrell  Female        Texas  648-61-0422
17      C0018    Mariah     Wilson       F           NY  108/82/5602
18      C0019   Michael       None    male    New Yorkk  018-10-5442
19      C0020    Robert       None    Male           NY  029-4166-39

========== SALES ==========
Rows: 10000
Columns: ['SaleID', 'ProductID', 'CustomerID', 'SalesAmount', 'Quantity', 'Timestamp']

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09T20:21:00
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28T05:01:00
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13T00:36:00
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,NaN,50.0,2024-07-06T23:39:00
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08T19:58:00
5,d71733ac-4fc4-42e6-ae48-c2150c8a92ae,1016,C0709,1705.51,31.0,2024-11-15T12:24:00
6,b7475afb-27f7-46fe-8bcd-c099c178d17f,1047,C0929,1509.94,3.0,2024-08-28T05:43:00
7,f5953c0c-e9bc-489a-9333-1e0c0a81d873,1027,C0019,1635.15,NaN,2024-08-30T19:07:00
8,427c33bb-dff7-4332-8d29-954728c713b1,1020,C0983,1070.59,31.0,2024-10-22T15:17:00
9,812ad61f-2e80-4b95-ae02-a91976bd2baa,1006,C0536,1097.00,2.0,2024-06-20T09:59:00
10,a18dadb3-b2e6-476e-b2fb-b4a477721bf0,1005,C0164,683.83,38.0,2024-11-15T09:33:00
11,fb7031b8-6ea9-48f1-9a00-9bc178359f8d,1017,C0955,1187.22,26.0,2024-07-07T00:55:00
12,16380106-881a-4b17-b7a6-cdb1cb7b0310,1046,C0102,1660.55,37.0,2024-06-10T20:40:00
13,3b8b6be3-3531-4e99-bb88-f690abf80831,1039,C0246,1285.76,12.0,2024-10-31T22:31:00
14,1c2ea051-0ea9-4464-9328-f005529e49b0,1044,C0231,580.56,2.0,2024-10-30T09:54:00
15,385f4dc3-93d8-4aea-9448-9ae392f1c70f,1012,C0266,1729.19,38.0,2024-09-22T19:51:00
16,65286b1d-53a6-4935-a98a-1cb1876e571e,1018,C0558,1700.77,44.0,2024-09-28T12:04:00
17,a71af1cd-5827-45bc-9819-7b822084b056,1004,C0267,1685.47,20.0,2024-07-29T14:48:00
18,fc2fbc9b-7dd9-47f9-8c88-f4657b809fda,1023,C0647,960.80,37.0,2024-08-17T13:20:00
19,d5ffcbb0-4af7-471e-a978-8d26a139e065,1030,C0099,1220.63,5.0,2024-08-20T12:26:00

========== PRODUCTS ==========
Rows: 50
Columns: ['ProductID', 'ProductName', 'Category']

    ProductID        ProductName         Category
0        1000    Washing Machine  Home Appliances
1        1001       Refrigerator  Home Appliances
2        1002            Blender  Home Appliances
3        1003          Microwave  Home Appliances
4        1004     Vacuum Cleaner  Home Appliances
5        1005               Sofa        Furniture
6        1006              Table        Furniture
7        1007              Chair        Furniture
8        1008                Bed        Furniture
9        1009           Cupboard        Furniture
10       1010             Laptop      Electronics
11       1011         Smartphone      Electronics
12       1012         Headphones      Electronics
13       1013             Tablet      Electronics
14       1014             Camera      Electronics
15       1015         Smartwatch      Electronics
16       1016  Bluetooth Speaker      Electronics
17       1017                 TV      Electronics
18       1018            Monitor      Electronics
19       1019            Printer      Electronics

**PHASE 2**

In [ ]:
print("========== UPDATED DATA PREVIEW ==========")

print("\n========== CUSTOMERS ==========")
print("Rows:", len(deduplicated_customers))
print("Columns:", list(deduplicated_customers.columns))
display(deduplicated_customers.head(20))

print("\n========== SALES ==========")
print("Rows:", len(sales))
print("Columns:", list(sales.columns))
display(sales.head(20))

print("\n========== PRODUCTS ==========")
print("Rows:", len(products))
print("Columns:", list(products.columns))
display(products.head(20))

========== UPDATED DATA PREVIEW ==========

========== CUSTOMERS ==========
Rows: 1000
Columns: ['CustomerID', 'FirstName', 'LastName', 'Gender', 'Region', 'SSN']

   CustomerID FirstName   LastName  Gender       Region          SSN
0       C0001   Gregory     Miller       M         Ohho    082573197
1       C0002    Marvin       None    male   california  309-6256-21
2       C0003   Gregory      Smith    Male    New Yorkk    407071725
3       C0004    Edward      Davis    male         Ohho  948.18.5740
4       C0005  Reginald     Dawson    male        Texas  975.72.3056
5       C0006  Virginia     Bryant  Female         Ohio  981/72/7452
6       C0007  Benjamin   Shepherd    Male         Ohho    048008736
7       C0008    Robert     Pierce    Male     New York  009/01/2352
8       C0009    Samuel  Mcconnell    male  Californiya  007-3486-87
9       C0010     Jason       None    Male           NY  785/76/9341
10      C0011     Jason    Morales    male         None  325-2353-01
11      C0012   Charles       None    Male     New York  239.14.0962
12      C0013   Brandon       None       M         Ohio  573-3595-11
13      C0014   Jeffery    Cabrera       M    New Yorkk  705.13.1809
14      C0015   William   Gonzalez    male     New York  058-13-1272
15      C0016       Joe    Barnett       M         Ohho  995/87/4707
16      C0017    Angela   Cantrell  Female        Texas  648-61-0422
17      C0018    Mariah     Wilson       F           NY  108/82/5602
18      C0019   Michael       None    male    New Yorkk  018-10-5442
19      C0020    Robert       None    Male           NY  029-4166-39

========== SALES ==========
Rows: 10000
Columns: ['SaleID', 'ProductID', 'CustomerID', 'SalesAmount', 'Quantity', 'Timestamp']

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09T20:21:00
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28T05:01:00
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13T00:36:00
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,NaN,50.0,2024-07-06T23:39:00
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08T19:58:00
5,d71733ac-4fc4-42e6-ae48-c2150c8a92ae,1016,C0709,1705.51,31.0,2024-11-15T12:24:00
6,b7475afb-27f7-46fe-8bcd-c099c178d17f,1047,C0929,1509.94,3.0,2024-08-28T05:43:00
7,f5953c0c-e9bc-489a-9333-1e0c0a81d873,1027,C0019,1635.15,NaN,2024-08-30T19:07:00
8,427c33bb-dff7-4332-8d29-954728c713b1,1020,C0983,1070.59,31.0,2024-10-22T15:17:00
9,812ad61f-2e80-4b95-ae02-a91976bd2baa,1006,C0536,1097.00,2.0,2024-06-20T09:59:00
10,a18dadb3-b2e6-476e-b2fb-b4a477721bf0,1005,C0164,683.83,38.0,2024-11-15T09:33:00
11,fb7031b8-6ea9-48f1-9a00-9bc178359f8d,1017,C0955,1187.22,26.0,2024-07-07T00:55:00
12,16380106-881a-4b17-b7a6-cdb1cb7b0310,1046,C0102,1660.55,37.0,2024-06-10T20:40:00
13,3b8b6be3-3531-4e99-bb88-f690abf80831,1039,C0246,1285.76,12.0,2024-10-31T22:31:00
14,1c2ea051-0ea9-4464-9328-f005529e49b0,1044,C0231,580.56,2.0,2024-10-30T09:54:00
15,385f4dc3-93d8-4aea-9448-9ae392f1c70f,1012,C0266,1729.19,38.0,2024-09-22T19:51:00
16,65286b1d-53a6-4935-a98a-1cb1876e571e,1018,C0558,1700.77,44.0,2024-09-28T12:04:00
17,a71af1cd-5827-45bc-9819-7b822084b056,1004,C0267,1685.47,20.0,2024-07-29T14:48:00
18,fc2fbc9b-7dd9-47f9-8c88-f4657b809fda,1023,C0647,960.80,37.0,2024-08-17T13:20:00
19,d5ffcbb0-4af7-471e-a978-8d26a139e065,1030,C0099,1220.63,5.0,2024-08-20T12:26:00

========== PRODUCTS ==========
Rows: 50
Columns: ['ProductID', 'ProductName', 'Category']

    ProductID        ProductName         Category
0        1000    Washing Machine  Home Appliances
1        1001       Refrigerator  Home Appliances
2        1002            Blender  Home Appliances
3        1003          Microwave  Home Appliances
4        1004     Vacuum Cleaner  Home Appliances
5        1005               Sofa        Furniture
6        1006              Table        Furniture
7        1007              Chair        Furniture
8        1008                Bed        Furniture
9        1009           Cupboard        Furniture
10       1010             Laptop      Electronics
11       1011         Smartphone      Electronics
12       1012         Headphones      Electronics
13       1013             Tablet      Electronics
14       1014             Camera      Electronics
15       1015         Smartwatch      Electronics
16       1016  Bluetooth Speaker      Electronics
17       1017                 TV      Electronics
18       1018            Monitor      Electronics
19       1019            Printer      Electronics

In [ ]:
print("========== PHASE 2: ETL WORKING COPIES ==========")

# Create independent working copies
customers_etl = deduplicated_customers.copy()
sales_etl = sales.copy()
products_etl = products.copy()

print("Customers ETL rows:", len(customers_etl))
print("Sales ETL rows:", len(sales_etl))
print("Products ETL rows:", len(products_etl))

print("\n========== ETL COPY SHAPES ==========")

print("Customers ETL:", customers_etl.shape)
print("Sales ETL:", sales_etl.shape)
print("Products ETL:", products_etl.shape)

print("\n========== ORIGINAL DATA PRESERVED ==========")

print("Original customers rows:", len(customers))
print("Original sales rows:", len(sales))
print("Original products rows:", len(products))

print("\nPhase 2 ETL working copies created successfully.")

========== PHASE 2: ETL WORKING COPIES ==========
Customers ETL rows: 1000
Sales ETL rows: 10000
Products ETL rows: 50

========== ETL COPY SHAPES ==========
Customers ETL: (1000, 6)
Sales ETL: (10000, 6)
Products ETL: (50, 3)

========== ORIGINAL DATA PRESERVED ==========
Original customers rows: 1100
Original sales rows: 10000
Original products rows: 50

Phase 2 ETL working copies created successfully.

In [ ]:
print("========== PHASE 2: CUSTOMER ID TRANSFORMATION ==========")

# Convert CustomerID in Customer ETL table
customers_etl["CustomerID"] = (
    customers_etl["CustomerID"]
    .astype(str)
    .str.replace("C", "", regex=False)
    .astype(int)
)

# Convert CustomerID in Sales ETL table
sales_etl["CustomerID"] = (
    sales_etl["CustomerID"]
    .astype(str)
    .str.replace("C", "", regex=False)
    .astype(int)
)

print("========== CUSTOMER ID SAMPLE ==========")

display(
    customers_etl[["CustomerID"]].head(10)
)

print("\n========== SALES CUSTOMER ID SAMPLE ==========")

display(
    sales_etl[["CustomerID"]].head(10)
)

print("\n========== CUSTOMER ID RANGE ==========")

print(
    "Customer table min:",
    customers_etl["CustomerID"].min()
)

print(
    "Customer table max:",
    customers_etl["CustomerID"].max()
)

print(
    "Sales table min:",
    sales_etl["CustomerID"].min()
)

print(
    "Sales table max:",
    sales_etl["CustomerID"].max()
)

print("\n========== CUSTOMER ID TYPE ==========")

print(
    "Customer table dtype:",
    customers_etl["CustomerID"].dtype
)

print(
    "Sales table dtype:",
    sales_etl["CustomerID"].dtype
)

========== PHASE 2: CUSTOMER ID TRANSFORMATION ==========
========== CUSTOMER ID SAMPLE ==========

   CustomerID
0           1
1           2
2           3
3           4
4           5
5           6
6           7
7           8
8           9
9          10

========== SALES CUSTOMER ID SAMPLE ==========

   CustomerID
0         460
1         198
2         524
3         285
4         369
5         709
6         929
7          19
8         983
9         536

========== CUSTOMER ID RANGE ==========
Customer table min: 1
Customer table max: 1000
Sales table min: 1
Sales table max: 1000

========== CUSTOMER ID TYPE ==========
Customer table dtype: int64
Sales table dtype: int64

In [ ]:
print("========== PHASE 2: CUSTOMER CATEGORY STANDARDIZATION ==========")

# -----------------------------
# STANDARDIZE GENDER
# -----------------------------

gender_map = {
    "M": "Male",
    "male": "Male",
    "Male": "Male",
    "F": "Female",
    "female": "Female",
    "Female": "Female"
}

customers_etl["Gender"] = (
    customers_etl["Gender"]
    .astype("string")
    .str.strip()
    .map(gender_map)
)

# -----------------------------
# STANDARDIZE REGION
# -----------------------------

region_map = {
    "Texaz": "Texas",
    "Texas": "Texas",
    "california": "California",
    "Californiya": "California",
    "Ohho": "Ohio",
    "Ohio": "Ohio",
    "NY": "New York",
    "New York": "New York",
    "Nw York": "New York",
    "New Yorkk": "New York"
}

customers_etl["Region"] = (
    customers_etl["Region"]
    .astype("string")
    .str.strip()
    .map(region_map)
    .fillna("Unknown")
)

# -----------------------------
# DISPLAY UPDATED CUSTOMER DATA
# -----------------------------

print("========== UPDATED CUSTOMER DATA ==========")

display(
    customers_etl.head(20)
)

# -----------------------------
# CHECK STANDARDIZED GENDER
# -----------------------------

print("\n========== STANDARDIZED GENDER ==========")

display(
    customers_etl["Gender"]
    .value_counts(dropna=False)
    .rename_axis("Gender")
    .reset_index(name="CustomerCount")
)

# -----------------------------
# CHECK STANDARDIZED REGION
# -----------------------------

print("\n========== STANDARDIZED REGION ==========")

display(
    customers_etl["Region"]
    .value_counts(dropna=False)
    .rename_axis("Region")
    .reset_index(name="CustomerCount")
)

# -----------------------------
# FINAL CATEGORY CHECK
# -----------------------------

print("\n========== UNIQUE VALUES AFTER STANDARDIZATION ==========")

print("Unique Gender values:",
      customers_etl["Gender"].nunique(dropna=False))

print("Unique Region values:",
      customers_etl["Region"].nunique(dropna=False))

========== PHASE 2: CUSTOMER CATEGORY STANDARDIZATION ==========
========== UPDATED CUSTOMER DATA ==========

    CustomerID FirstName   LastName  Gender      Region          SSN
0            1   Gregory     Miller    Male        Ohio    082573197
1            2    Marvin       None    Male  California  309-6256-21
2            3   Gregory      Smith    Male    New York    407071725
3            4    Edward      Davis    Male        Ohio  948.18.5740
4            5  Reginald     Dawson    Male       Texas  975.72.3056
5            6  Virginia     Bryant  Female        Ohio  981/72/7452
6            7  Benjamin   Shepherd    Male        Ohio    048008736
7            8    Robert     Pierce    Male    New York  009/01/2352
8            9    Samuel  Mcconnell    Male  California  007-3486-87
9           10     Jason       None    Male    New York  785/76/9341
10          11     Jason    Morales    Male     Unknown  325-2353-01
11          12   Charles       None    Male    New York  239.14.0962
12          13   Brandon       None    Male        Ohio  573-3595-11
13          14   Jeffery    Cabrera    Male    New York  705.13.1809
14          15   William   Gonzalez    Male    New York  058-13-1272
15          16       Joe    Barnett    Male        Ohio  995/87/4707
16          17    Angela   Cantrell  Female       Texas  648-61-0422
17          18    Mariah     Wilson  Female    New York  108/82/5602
18          19   Michael       None    Male    New York  018-10-5442
19          20    Robert       None    Male    New York  029-4166-39

========== STANDARDIZED GENDER ==========

   Gender  CustomerCount
0    Male            783
1  Female            217

========== STANDARDIZED REGION ==========

       Region  CustomerCount
0    New York            377
1       Texas            194
2  California            192
3        Ohio            175
4     Unknown             62

========== UNIQUE VALUES AFTER STANDARDIZATION ==========
Unique Gender values: 2
Unique Region values: 5

In [ ]:
print("========== PHASE 2: CUSTOMER NAME STANDARDIZATION ==========")

# Standardize FirstName
customers_etl["FirstName"] = (
    customers_etl["FirstName"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Standardize LastName
customers_etl["LastName"] = (
    customers_etl["LastName"]
    .astype("string")
    .str.strip()
    .str.title()
)

# -----------------------------
# DISPLAY UPDATED CUSTOMER DATA
# -----------------------------

print("========== UPDATED CUSTOMER DATA ==========")

display(
    customers_etl.head(20)
)

# -----------------------------
# MISSING VALUE CHECK
# -----------------------------

print("\n========== NAME COMPLETENESS ==========")

print(
    "Missing FirstName:",
    customers_etl["FirstName"].isna().sum()
)

print(
    "Missing LastName:",
    customers_etl["LastName"].isna().sum()
)

print(
    "Complete names:",
    (
        customers_etl["FirstName"].notna()
        & customers_etl["LastName"].notna()
    ).sum()
)

# -----------------------------
# UNIQUE NAME COUNTS
# -----------------------------

print("\n========== UNIQUE NAME COUNTS ==========")

print(
    "Unique FirstNames:",
    customers_etl["FirstName"].nunique(dropna=True)
)

print(
    "Unique LastNames:",
    customers_etl["LastName"].nunique(dropna=True)
)

# -----------------------------
# CHECK DATA TYPES
# -----------------------------

print("\n========== CUSTOMER DATA TYPES ==========")

print(customers_etl.dtypes)

========== PHASE 2: CUSTOMER NAME STANDARDIZATION ==========
========== UPDATED CUSTOMER DATA ==========

    CustomerID FirstName   LastName  Gender      Region          SSN
0            1   Gregory     Miller    Male        Ohio    082573197
1            2    Marvin       <NA>    Male  California  309-6256-21
2            3   Gregory      Smith    Male    New York    407071725
3            4    Edward      Davis    Male        Ohio  948.18.5740
4            5  Reginald     Dawson    Male       Texas  975.72.3056
5            6  Virginia     Bryant  Female        Ohio  981/72/7452
6            7  Benjamin   Shepherd    Male        Ohio    048008736
7            8    Robert     Pierce    Male    New York  009/01/2352
8            9    Samuel  Mcconnell    Male  California  007-3486-87
9           10     Jason       <NA>    Male    New York  785/76/9341
10          11     Jason    Morales    Male     Unknown  325-2353-01
11          12   Charles       <NA>    Male    New York  239.14.0962
12          13   Brandon       <NA>    Male        Ohio  573-3595-11
13          14   Jeffery    Cabrera    Male    New York  705.13.1809
14          15   William   Gonzalez    Male    New York  058-13-1272
15          16       Joe    Barnett    Male        Ohio  995/87/4707
16          17    Angela   Cantrell  Female       Texas  648-61-0422
17          18    Mariah     Wilson  Female    New York  108/82/5602
18          19   Michael       <NA>    Male    New York  018-10-5442
19          20    Robert       <NA>    Male    New York  029-4166-39

========== NAME COMPLETENESS ==========
Missing FirstName: 0
Missing LastName: 290
Complete names: 710

========== UNIQUE NAME COUNTS ==========
Unique FirstNames: 318
Unique LastNames: 400

========== CUSTOMER DATA TYPES ==========
CustomerID             int64
FirstName     string[python]
LastName      string[python]
Gender                object
Region                object
SSN                   object
dtype: object

In [ ]:
print("========== PHASE 2: SSN STANDARDIZATION ==========")

# Convert SSN to string and remove common separators
customers_etl["SSN"] = (
    customers_etl["SSN"]
    .astype("string")
    .str.strip()
    .str.replace(r"[-./]", "", regex=True)
)

print("========== UPDATED CUSTOMER DATA ==========")

display(
    customers_etl.head(20)
)

# -----------------------------
# SSN COMPLETENESS
# -----------------------------

print("\n========== SSN COMPLETENESS ==========")

print(
    "Missing SSN:",
    customers_etl["SSN"].isna().sum()
)

print(
    "Non-missing SSN:",
    customers_etl["SSN"].notna().sum()
)

# -----------------------------
# SSN LENGTH CHECK
# -----------------------------

ssn_length = customers_etl["SSN"].str.len()

print("\n========== SSN LENGTH CHECK ==========")

print(
    "9-digit SSNs:",
    (ssn_length == 9).sum()
)

print(
    "Non-9-digit SSNs:",
    (ssn_length != 9).sum()
)

if (ssn_length != 9).sum() > 0:
    print("\nSSNs with unexpected length:")
    display(
        customers_etl.loc[
            ssn_length != 9,
            ["CustomerID", "SSN"]
        ]
    )

# -----------------------------
# DIGIT-ONLY CHECK
# -----------------------------

digit_only = customers_etl["SSN"].str.match(
    r"^\d{9}$",
    na=False
)

print("\n========== SSN FORMAT CHECK ==========")

print(
    "Valid 9-digit numeric SSNs:",
    digit_only.sum()
)

print(
    "Invalid SSN formats:",
    (~digit_only & customers_etl["SSN"].notna()).sum()
)

========== PHASE 2: SSN STANDARDIZATION ==========
========== UPDATED CUSTOMER DATA ==========

    CustomerID FirstName   LastName  Gender      Region        SSN
0            1   Gregory     Miller    Male        Ohio  082573197
1            2    Marvin       <NA>    Male  California  309625621
2            3   Gregory      Smith    Male    New York  407071725
3            4    Edward      Davis    Male        Ohio  948185740
4            5  Reginald     Dawson    Male       Texas  975723056
5            6  Virginia     Bryant  Female        Ohio  981727452
6            7  Benjamin   Shepherd    Male        Ohio  048008736
7            8    Robert     Pierce    Male    New York  009012352
8            9    Samuel  Mcconnell    Male  California  007348687
9           10     Jason       <NA>    Male    New York  785769341
10          11     Jason    Morales    Male     Unknown  325235301
11          12   Charles       <NA>    Male    New York  239140962
12          13   Brandon       <NA>    Male        Ohio  573359511
13          14   Jeffery    Cabrera    Male    New York  705131809
14          15   William   Gonzalez    Male    New York  058131272
15          16       Joe    Barnett    Male        Ohio  995874707
16          17    Angela   Cantrell  Female       Texas  648610422
17          18    Mariah     Wilson  Female    New York  108825602
18          19   Michael       <NA>    Male    New York  018105442
19          20    Robert       <NA>    Male    New York  029416639

========== SSN COMPLETENESS ==========
Missing SSN: 0
Non-missing SSN: 1000

========== SSN LENGTH CHECK ==========
9-digit SSNs: 1000
Non-9-digit SSNs: 0

========== SSN FORMAT CHECK ==========
Valid 9-digit numeric SSNs: 1000
Invalid SSN formats: 0

In [ ]:
print("========== PHASE 2: SALES TIMESTAMP STANDARDIZATION ==========")

# Convert Timestamp to datetime
sales_etl["Timestamp"] = pd.to_datetime(
    sales_etl["Timestamp"],
    errors="coerce"
)

print("========== UPDATED SALES DATA ==========")

display(
    sales_etl.head(20)
)

# -----------------------------
# TIMESTAMP VALIDATION
# -----------------------------

print("\n========== TIMESTAMP VALIDATION ==========")

print(
    "Missing timestamps:",
    sales_etl["Timestamp"].isna().sum()
)

print(
    "Valid timestamps:",
    sales_etl["Timestamp"].notna().sum()
)

# -----------------------------
# DATE RANGE
# -----------------------------

print("\n========== SALES DATE RANGE ==========")

print(
    "Earliest Timestamp:",
    sales_etl["Timestamp"].min()
)

print(
    "Latest Timestamp:",
    sales_etl["Timestamp"].max()
)

# -----------------------------
# DATA TYPE
# -----------------------------

print("\n========== TIMESTAMP DATA TYPE ==========")

print(
    "Timestamp dtype:",
    sales_etl["Timestamp"].dtype
)

========== PHASE 2: SALES TIMESTAMP STANDARDIZATION ==========
========== UPDATED SALES DATA ==========

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,460,1639.10,18.0,2024-08-09 20:21:00
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,198,186.11,42.0,2024-11-28 05:01:00
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,524,1712.72,49.0,2024-10-13 00:36:00
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,285,NaN,50.0,2024-07-06 23:39:00
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,369,66.36,21.0,2024-06-08 19:58:00
5,d71733ac-4fc4-42e6-ae48-c2150c8a92ae,1016,709,1705.51,31.0,2024-11-15 12:24:00
6,b7475afb-27f7-46fe-8bcd-c099c178d17f,1047,929,1509.94,3.0,2024-08-28 05:43:00
7,f5953c0c-e9bc-489a-9333-1e0c0a81d873,1027,19,1635.15,NaN,2024-08-30 19:07:00
8,427c33bb-dff7-4332-8d29-954728c713b1,1020,983,1070.59,31.0,2024-10-22 15:17:00
9,812ad61f-2e80-4b95-ae02-a91976bd2baa,1006,536,1097.00,2.0,2024-06-20 09:59:00
10,a18dadb3-b2e6-476e-b2fb-b4a477721bf0,1005,164,683.83,38.0,2024-11-15 09:33:00
11,fb7031b8-6ea9-48f1-9a00-9bc178359f8d,1017,955,1187.22,26.0,2024-07-07 00:55:00
12,16380106-881a-4b17-b7a6-cdb1cb7b0310,1046,102,1660.55,37.0,2024-06-10 20:40:00
13,3b8b6be3-3531-4e99-bb88-f690abf80831,1039,246,1285.76,12.0,2024-10-31 22:31:00
14,1c2ea051-0ea9-4464-9328-f005529e49b0,1044,231,580.56,2.0,2024-10-30 09:54:00
15,385f4dc3-93d8-4aea-9448-9ae392f1c70f,1012,266,1729.19,38.0,2024-09-22 19:51:00
16,65286b1d-53a6-4935-a98a-1cb1876e571e,1018,558,1700.77,44.0,2024-09-28 12:04:00
17,a71af1cd-5827-45bc-9819-7b822084b056,1004,267,1685.47,20.0,2024-07-29 14:48:00
18,fc2fbc9b-7dd9-47f9-8c88-f4657b809fda,1023,647,960.80,37.0,2024-08-17 13:20:00
19,d5ffcbb0-4af7-471e-a978-8d26a139e065,1030,99,1220.63,5.0,2024-08-20 12:26:00

========== TIMESTAMP VALIDATION ==========
Missing timestamps: 0
Valid timestamps: 10000

========== SALES DATE RANGE ==========
Earliest Timestamp: 2024-06-01 10:03:00
Latest Timestamp: 2024-11-28 09:38:00

========== TIMESTAMP DATA TYPE ==========
Timestamp dtype: datetime64[ns]

In [ ]:
print("========== PHASE 2: SALES NUMERIC TYPE STANDARDIZATION ==========")

# SalesAmount remains numeric for now.
# Missing values are intentionally preserved.
sales_etl["SalesAmount"] = pd.to_numeric(
    sales_etl["SalesAmount"],
    errors="coerce"
)

# Convert Quantity to nullable integer.
# This preserves missing values while making valid quantities integers.
sales_etl["Quantity"] = pd.to_numeric(
    sales_etl["Quantity"],
    errors="coerce"
).astype("Int64")

print("========== UPDATED SALES DATA ==========")

display(
    sales_etl.head(20)
)

# -----------------------------
# DATA TYPES
# -----------------------------

print("\n========== SALES DATA TYPES ==========")

print(
    sales_etl[
        ["ProductID", "CustomerID", "SalesAmount", "Quantity", "Timestamp"]
    ].dtypes
)

# -----------------------------
# MISSING VALUES
# -----------------------------

print("\n========== NUMERIC COMPLETENESS ==========")

print(
    "Missing SalesAmount:",
    sales_etl["SalesAmount"].isna().sum()
)

print(
    "Missing Quantity:",
    sales_etl["Quantity"].isna().sum()
)

# -----------------------------
# VALID VALUE RANGES
# -----------------------------

print("\n========== NUMERIC RANGES ==========")

print(
    "SalesAmount minimum:",
    sales_etl["SalesAmount"].min()
)

print(
    "SalesAmount maximum:",
    sales_etl["SalesAmount"].max()
)

print(
    "Quantity minimum:",
    sales_etl["Quantity"].min()
)

print(
    "Quantity maximum:",
    sales_etl["Quantity"].max()
)

========== PHASE 2: SALES NUMERIC TYPE STANDARDIZATION ==========
========== UPDATED SALES DATA ==========

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,460,1639.10,18,2024-08-09 20:21:00
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,198,186.11,42,2024-11-28 05:01:00
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,524,1712.72,49,2024-10-13 00:36:00
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,285,NaN,50,2024-07-06 23:39:00
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,369,66.36,21,2024-06-08 19:58:00
5,d71733ac-4fc4-42e6-ae48-c2150c8a92ae,1016,709,1705.51,31,2024-11-15 12:24:00
6,b7475afb-27f7-46fe-8bcd-c099c178d17f,1047,929,1509.94,3,2024-08-28 05:43:00
7,f5953c0c-e9bc-489a-9333-1e0c0a81d873,1027,19,1635.15,<NA>,2024-08-30 19:07:00
8,427c33bb-dff7-4332-8d29-954728c713b1,1020,983,1070.59,31,2024-10-22 15:17:00
9,812ad61f-2e80-4b95-ae02-a91976bd2baa,1006,536,1097.00,2,2024-06-20 09:59:00
10,a18dadb3-b2e6-476e-b2fb-b4a477721bf0,1005,164,683.83,38,2024-11-15 09:33:00
11,fb7031b8-6ea9-48f1-9a00-9bc178359f8d,1017,955,1187.22,26,2024-07-07 00:55:00
12,16380106-881a-4b17-b7a6-cdb1cb7b0310,1046,102,1660.55,37,2024-06-10 20:40:00
13,3b8b6be3-3531-4e99-bb88-f690abf80831,1039,246,1285.76,12,2024-10-31 22:31:00
14,1c2ea051-0ea9-4464-9328-f005529e49b0,1044,231,580.56,2,2024-10-30 09:54:00
15,385f4dc3-93d8-4aea-9448-9ae392f1c70f,1012,266,1729.19,38,2024-09-22 19:51:00
16,65286b1d-53a6-4935-a98a-1cb1876e571e,1018,558,1700.77,44,2024-09-28 12:04:00
17,a71af1cd-5827-45bc-9819-7b822084b056,1004,267,1685.47,20,2024-07-29 14:48:00
18,fc2fbc9b-7dd9-47f9-8c88-f4657b809fda,1023,647,960.80,37,2024-08-17 13:20:00
19,d5ffcbb0-4af7-471e-a978-8d26a139e065,1030,99,1220.63,5,2024-08-20 12:26:00

========== SALES DATA TYPES ==========
ProductID               int64
CustomerID              int64
SalesAmount           float64
Quantity                Int64
Timestamp      datetime64[ns]
dtype: object

========== NUMERIC COMPLETENESS ==========
Missing SalesAmount: 497
Missing Quantity: 113

========== NUMERIC RANGES ==========
SalesAmount minimum: 50.18
SalesAmount maximum: 79783.4
Quantity minimum: 1
Quantity maximum: 50

In [ ]:
print("========== PHASE 2: SALE ID TRANSFORMATION ==========")

# Preserve the original UUID for source-level traceability
sales_etl["SourceSaleID"] = sales_etl["SaleID"].copy()

# Create sequential integer SaleID for the warehouse
sales_etl["SaleID"] = range(1, len(sales_etl) + 1)

print("========== UPDATED SALES DATA ==========")

display(
    sales_etl[
        [
            "SaleID",
            "SourceSaleID",
            "ProductID",
            "CustomerID",
            "SalesAmount",
            "Quantity",
            "Timestamp"
        ]
    ].head(20)
)

# -----------------------------
# SALE ID VALIDATION
# -----------------------------

print("\n========== SALE ID VALIDATION ==========")

print(
    "Total SaleIDs:",
    sales_etl["SaleID"].count()
)

print(
    "Unique SaleIDs:",
    sales_etl["SaleID"].nunique()
)

print(
    "Duplicate SaleIDs:",
    sales_etl["SaleID"].duplicated().sum()
)

print(
    "Missing SaleIDs:",
    sales_etl["SaleID"].isna().sum()
)

print(
    "Minimum SaleID:",
    sales_etl["SaleID"].min()
)

print(
    "Maximum SaleID:",
    sales_etl["SaleID"].max()
)

# -----------------------------
# SOURCE UUID VALIDATION
# -----------------------------

print("\n========== SOURCE SALE ID VALIDATION ==========")

print(
    "SourceSaleID unique:",
    sales_etl["SourceSaleID"].nunique()
)

print(
    "Missing SourceSaleID:",
    sales_etl["SourceSaleID"].isna().sum()
)

# -----------------------------
# DATA TYPES
# -----------------------------

print("\n========== SALE ID DATA TYPES ==========")

print(
    sales_etl[
        ["SaleID", "SourceSaleID"]
    ].dtypes
)

========== PHASE 2: SALE ID TRANSFORMATION ==========
========== UPDATED SALES DATA ==========

,SaleID,SourceSaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,1,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,460,1639.10,18,2024-08-09 20:21:00
1,2,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,198,186.11,42,2024-11-28 05:01:00
2,3,8666f277-cc58-4fde-9d58-697da9e040f2,1012,524,1712.72,49,2024-10-13 00:36:00
3,4,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,285,NaN,50,2024-07-06 23:39:00
4,5,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,369,66.36,21,2024-06-08 19:58:00
5,6,d71733ac-4fc4-42e6-ae48-c2150c8a92ae,1016,709,1705.51,31,2024-11-15 12:24:00
6,7,b7475afb-27f7-46fe-8bcd-c099c178d17f,1047,929,1509.94,3,2024-08-28 05:43:00
7,8,f5953c0c-e9bc-489a-9333-1e0c0a81d873,1027,19,1635.15,<NA>,2024-08-30 19:07:00
8,9,427c33bb-dff7-4332-8d29-954728c713b1,1020,983,1070.59,31,2024-10-22 15:17:00
9,10,812ad61f-2e80-4b95-ae02-a91976bd2baa,1006,536,1097.00,2,2024-06-20 09:59:00
10,11,a18dadb3-b2e6-476e-b2fb-b4a477721bf0,1005,164,683.83,38,2024-11-15 09:33:00
11,12,fb7031b8-6ea9-48f1-9a00-9bc178359f8d,1017,955,1187.22,26,2024-07-07 00:55:00
12,13,16380106-881a-4b17-b7a6-cdb1cb7b0310,1046,102,1660.55,37,2024-06-10 20:40:00
13,14,3b8b6be3-3531-4e99-bb88-f690abf80831,1039,246,1285.76,12,2024-10-31 22:31:00
14,15,1c2ea051-0ea9-4464-9328-f005529e49b0,1044,231,580.56,2,2024-10-30 09:54:00
15,16,385f4dc3-93d8-4aea-9448-9ae392f1c70f,1012,266,1729.19,38,2024-09-22 19:51:00
16,17,65286b1d-53a6-4935-a98a-1cb1876e571e,1018,558,1700.77,44,2024-09-28 12:04:00
17,18,a71af1cd-5827-45bc-9819-7b822084b056,1004,267,1685.47,20,2024-07-29 14:48:00
18,19,fc2fbc9b-7dd9-47f9-8c88-f4657b809fda,1023,647,960.80,37,2024-08-17 13:20:00
19,20,d5ffcbb0-4af7-471e-a978-8d26a139e065,1030,99,1220.63,5,2024-08-20 12:26:00

========== SALE ID VALIDATION ==========
Total SaleIDs: 10000
Unique SaleIDs: 10000
Duplicate SaleIDs: 0
Missing SaleIDs: 0
Minimum SaleID: 1
Maximum SaleID: 10000

========== SOURCE SALE ID VALIDATION ==========
SourceSaleID unique: 10000
Missing SourceSaleID: 0

========== SALE ID DATA TYPES ==========
SaleID           int64
SourceSaleID    object
dtype: object

In [ ]:
print("========== PHASE 2: CUSTOMER ID FORMAT CORRECTION ==========")

# Convert CustomerID to a 4-digit string
customers_etl["CustomerID"] = (
    customers_etl["CustomerID"]
    .astype(int)
    .astype(str)
    .str.zfill(4)
)

sales_etl["CustomerID"] = (
    sales_etl["CustomerID"]
    .astype(int)
    .astype(str)
    .str.zfill(4)
)

print("========== UPDATED CUSTOMER DATA ==========")

display(
    customers_etl[
        ["CustomerID", "FirstName", "LastName", "Gender", "Region", "SSN"]
    ].head(20)
)

print("\n========== UPDATED SALES DATA ==========")

display(
    sales_etl[
        [
            "SaleID",
            "ProductID",
            "CustomerID",
            "SalesAmount",
            "Quantity",
            "Timestamp"
        ]
    ].head(20)
)

print("\n========== CUSTOMER ID RANGE ==========")

print(
    "Customer table minimum:",
    customers_etl["CustomerID"].min()
)

print(
    "Customer table maximum:",
    customers_etl["CustomerID"].max()
)

print(
    "Sales table minimum:",
    sales_etl["CustomerID"].min()
)

print(
    "Sales table maximum:",
    sales_etl["CustomerID"].max()
)

print("\n========== CUSTOMER ID LENGTH CHECK ==========")

print(
    "Customer IDs with 4 digits:",
    customers_etl["CustomerID"].str.len().eq(4).sum()
)

print(
    "Sales Customer IDs with 4 digits:",
    sales_etl["CustomerID"].str.len().eq(4).sum()
)

print(
    "Invalid Customer IDs:",
    (~customers_etl["CustomerID"].str.match(r"^\d{4}$")).sum()
)

print(
    "Invalid Sales Customer IDs:",
    (~sales_etl["CustomerID"].str.match(r"^\d{4}$")).sum()
)

print("\n========== DATA TYPES ==========")

print(
    "Customer table CustomerID dtype:",
    customers_etl["CustomerID"].dtype
)

print(
    "Sales table CustomerID dtype:",
    sales_etl["CustomerID"].dtype
)

========== PHASE 2: CUSTOMER ID FORMAT CORRECTION ==========
========== UPDATED CUSTOMER DATA ==========

   CustomerID FirstName   LastName  Gender      Region        SSN
0        0001   Gregory     Miller    Male        Ohio  082573197
1        0002    Marvin       <NA>    Male  California  309625621
2        0003   Gregory      Smith    Male    New York  407071725
3        0004    Edward      Davis    Male        Ohio  948185740
4        0005  Reginald     Dawson    Male       Texas  975723056
5        0006  Virginia     Bryant  Female        Ohio  981727452
6        0007  Benjamin   Shepherd    Male        Ohio  048008736
7        0008    Robert     Pierce    Male    New York  009012352
8        0009    Samuel  Mcconnell    Male  California  007348687
9        0010     Jason       <NA>    Male    New York  785769341
10       0011     Jason    Morales    Male     Unknown  325235301
11       0012   Charles       <NA>    Male    New York  239140962
12       0013   Brandon       <NA>    Male        Ohio  573359511
13       0014   Jeffery    Cabrera    Male    New York  705131809
14       0015   William   Gonzalez    Male    New York  058131272
15       0016       Joe    Barnett    Male        Ohio  995874707
16       0017    Angela   Cantrell  Female       Texas  648610422
17       0018    Mariah     Wilson  Female    New York  108825602
18       0019   Michael       <NA>    Male    New York  018105442
19       0020    Robert       <NA>    Male    New York  029416639

========== UPDATED SALES DATA ==========

    SaleID  ProductID CustomerID  SalesAmount  Quantity           Timestamp
0        1       1020       0460      1639.10        18 2024-08-09 20:21:00
1        2       1029       0198       186.11        42 2024-11-28 05:01:00
2        3       1012       0524      1712.72        49 2024-10-13 00:36:00
3        4       1016       0285          NaN        50 2024-07-06 23:39:00
4        5       1021       0369        66.36        21 2024-06-08 19:58:00
5        6       1016       0709      1705.51        31 2024-11-15 12:24:00
6        7       1047       0929      1509.94         3 2024-08-28 05:43:00
7        8       1027       0019      1635.15      <NA> 2024-08-30 19:07:00
8        9       1020       0983      1070.59        31 2024-10-22 15:17:00
9       10       1006       0536      1097.00         2 2024-06-20 09:59:00
10      11       1005       0164       683.83        38 2024-11-15 09:33:00
11      12       1017       0955      1187.22        26 2024-07-07 00:55:00
12      13       1046       0102      1660.55        37 2024-06-10 20:40:00
13      14       1039       0246      1285.76        12 2024-10-31 22:31:00
14      15       1044       0231       580.56         2 2024-10-30 09:54:00
15      16       1012       0266      1729.19        38 2024-09-22 19:51:00
16      17       1018       0558      1700.77        44 2024-09-28 12:04:00
17      18       1004       0267      1685.47        20 2024-07-29 14:48:00
18      19       1023       0647       960.80        37 2024-08-17 13:20:00
19      20       1030       0099      1220.63         5 2024-08-20 12:26:00

========== CUSTOMER ID RANGE ==========
Customer table minimum: 0001
Customer table maximum: 1000
Sales table minimum: 0001
Sales table maximum: 1000

========== CUSTOMER ID LENGTH CHECK ==========
Customer IDs with 4 digits: 1000
Sales Customer IDs with 4 digits: 10000
Invalid Customer IDs: 0
Invalid Sales Customer IDs: 0

========== DATA TYPES ==========
Customer table CustomerID dtype: object
Sales table CustomerID dtype: object

In [ ]:
print("========== PHASE 2: SALE ID TRANSFORMATION ==========")

# Preserve original UUID for source-level traceability
sales_etl["SourceSaleID"] = sales_etl["SaleID"].copy()

# Create a separate integer SaleID
sales_etl["SaleID"] = range(1, len(sales_etl) + 1)

print("========== UPDATED SALES DATA ==========")

display(
    sales_etl[
        [
            "SaleID",
            "SourceSaleID",
            "ProductID",
            "CustomerID",
            "SalesAmount",
            "Quantity",
            "Timestamp"
        ]
    ].head(20)
)

print("\n========== SALE ID VALIDATION ==========")

print("Total SaleIDs:", sales_etl["SaleID"].count())
print("Unique SaleIDs:", sales_etl["SaleID"].nunique())
print("Duplicate SaleIDs:", sales_etl["SaleID"].duplicated().sum())
print("Missing SaleIDs:", sales_etl["SaleID"].isna().sum())
print("Minimum SaleID:", sales_etl["SaleID"].min())
print("Maximum SaleID:", sales_etl["SaleID"].max())

print("\n========== SOURCE SALE ID VALIDATION ==========")

print("Unique SourceSaleIDs:", sales_etl["SourceSaleID"].nunique())
print("Missing SourceSaleIDs:", sales_etl["SourceSaleID"].isna().sum())

print("\n========== DATA TYPES ==========")

print(
    sales_etl[
        ["SaleID", "SourceSaleID", "CustomerID"]
    ].dtypes
)

========== PHASE 2: SALE ID TRANSFORMATION ==========
========== UPDATED SALES DATA ==========

,SaleID,SourceSaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,1,1,1020,0460,1639.10,18,2024-08-09 20:21:00
1,2,2,1029,0198,186.11,42,2024-11-28 05:01:00
2,3,3,1012,0524,1712.72,49,2024-10-13 00:36:00
3,4,4,1016,0285,NaN,50,2024-07-06 23:39:00
4,5,5,1021,0369,66.36,21,2024-06-08 19:58:00
5,6,6,1016,0709,1705.51,31,2024-11-15 12:24:00
6,7,7,1047,0929,1509.94,3,2024-08-28 05:43:00
7,8,8,1027,0019,1635.15,<NA>,2024-08-30 19:07:00
8,9,9,1020,0983,1070.59,31,2024-10-22 15:17:00
9,10,10,1006,0536,1097.00,2,2024-06-20 09:59:00
10,11,11,1005,0164,683.83,38,2024-11-15 09:33:00
11,12,12,1017,0955,1187.22,26,2024-07-07 00:55:00
12,13,13,1046,0102,1660.55,37,2024-06-10 20:40:00
13,14,14,1039,0246,1285.76,12,2024-10-31 22:31:00
14,15,15,1044,0231,580.56,2,2024-10-30 09:54:00
15,16,16,1012,0266,1729.19,38,2024-09-22 19:51:00
16,17,17,1018,0558,1700.77,44,2024-09-28 12:04:00
17,18,18,1004,0267,1685.47,20,2024-07-29 14:48:00
18,19,19,1023,0647,960.80,37,2024-08-17 13:20:00
19,20,20,1030,0099,1220.63,5,2024-08-20 12:26:00

========== SALE ID VALIDATION ==========
Total SaleIDs: 10000
Unique SaleIDs: 10000
Duplicate SaleIDs: 0
Missing SaleIDs: 0
Minimum SaleID: 1
Maximum SaleID: 10000

========== SOURCE SALE ID VALIDATION ==========
Unique SourceSaleIDs: 10000
Missing SourceSaleIDs: 0

========== DATA TYPES ==========
SaleID           int64
SourceSaleID     int64
CustomerID      object
dtype: object

In [ ]:
print("========== PHASE 2: RESTORE ORIGINAL SOURCE SALE ID ==========")

# Restore the original UUID directly from the untouched raw Sales data
sales_etl["SourceSaleID"] = sales["SaleID"].copy()

# Keep the warehouse SaleID as a separate integer key
sales_etl["SaleID"] = range(1, len(sales_etl) + 1)

print("========== UPDATED SALES DATA ==========")

display(
    sales_etl[
        [
            "SaleID",
            "SourceSaleID",
            "ProductID",
            "CustomerID",
            "SalesAmount",
            "Quantity",
            "Timestamp"
        ]
    ].head(20)
)

print("\n========== SALE ID VALIDATION ==========")

print("Warehouse SaleID dtype:",
      sales_etl["SaleID"].dtype)

print("Warehouse SaleID unique:",
      sales_etl["SaleID"].nunique())

print("Warehouse SaleID minimum:",
      sales_etl["SaleID"].min())

print("Warehouse SaleID maximum:",
      sales_etl["SaleID"].max())

print("\n========== SOURCE SALE ID VALIDATION ==========")

print("SourceSaleID dtype:",
      sales_etl["SourceSaleID"].dtype)

print("SourceSaleID unique:",
      sales_etl["SourceSaleID"].nunique())

print("Missing SourceSaleID:",
      sales_etl["SourceSaleID"].isna().sum())

print("\n========== ORIGINAL UUID SAMPLE ==========")

display(
    sales_etl[
        ["SaleID", "SourceSaleID"]
    ].head(10)
)

========== PHASE 2: RESTORE ORIGINAL SOURCE SALE ID ==========
========== UPDATED SALES DATA ==========

,SaleID,SourceSaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,1,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,0460,1639.10,18,2024-08-09 20:21:00
1,2,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,0198,186.11,42,2024-11-28 05:01:00
2,3,8666f277-cc58-4fde-9d58-697da9e040f2,1012,0524,1712.72,49,2024-10-13 00:36:00
3,4,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,0285,NaN,50,2024-07-06 23:39:00
4,5,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,0369,66.36,21,2024-06-08 19:58:00
5,6,d71733ac-4fc4-42e6-ae48-c2150c8a92ae,1016,0709,1705.51,31,2024-11-15 12:24:00
6,7,b7475afb-27f7-46fe-8bcd-c099c178d17f,1047,0929,1509.94,3,2024-08-28 05:43:00
7,8,f5953c0c-e9bc-489a-9333-1e0c0a81d873,1027,0019,1635.15,<NA>,2024-08-30 19:07:00
8,9,427c33bb-dff7-4332-8d29-954728c713b1,1020,0983,1070.59,31,2024-10-22 15:17:00
9,10,812ad61f-2e80-4b95-ae02-a91976bd2baa,1006,0536,1097.00,2,2024-06-20 09:59:00
10,11,a18dadb3-b2e6-476e-b2fb-b4a477721bf0,1005,0164,683.83,38,2024-11-15 09:33:00
11,12,fb7031b8-6ea9-48f1-9a00-9bc178359f8d,1017,0955,1187.22,26,2024-07-07 00:55:00
12,13,16380106-881a-4b17-b7a6-cdb1cb7b0310,1046,0102,1660.55,37,2024-06-10 20:40:00
13,14,3b8b6be3-3531-4e99-bb88-f690abf80831,1039,0246,1285.76,12,2024-10-31 22:31:00
14,15,1c2ea051-0ea9-4464-9328-f005529e49b0,1044,0231,580.56,2,2024-10-30 09:54:00
15,16,385f4dc3-93d8-4aea-9448-9ae392f1c70f,1012,0266,1729.19,38,2024-09-22 19:51:00
16,17,65286b1d-53a6-4935-a98a-1cb1876e571e,1018,0558,1700.77,44,2024-09-28 12:04:00
17,18,a71af1cd-5827-45bc-9819-7b822084b056,1004,0267,1685.47,20,2024-07-29 14:48:00
18,19,fc2fbc9b-7dd9-47f9-8c88-f4657b809fda,1023,0647,960.80,37,2024-08-17 13:20:00
19,20,d5ffcbb0-4af7-471e-a978-8d26a139e065,1030,0099,1220.63,5,2024-08-20 12:26:00

========== SALE ID VALIDATION ==========
Warehouse SaleID dtype: int64
Warehouse SaleID unique: 10000
Warehouse SaleID minimum: 1
Warehouse SaleID maximum: 10000

========== SOURCE SALE ID VALIDATION ==========
SourceSaleID dtype: object
SourceSaleID unique: 10000
Missing SourceSaleID: 0

========== ORIGINAL UUID SAMPLE ==========

   SaleID                          SourceSaleID
0       1  c0078cd1-3ddc-439a-b41d-7498e8e75e62
1       2  be8532af-16b7-432c-a13d-4c6e6836d12d
2       3  8666f277-cc58-4fde-9d58-697da9e040f2
3       4  383e0a2b-7e00-454e-a269-b2f73ecd33f2
4       5  d9a7f974-9572-48dd-aa36-3f96b280dfc7
5       6  d71733ac-4fc4-42e6-ae48-c2150c8a92ae
6       7  b7475afb-27f7-46fe-8bcd-c099c178d17f
7       8  f5953c0c-e9bc-489a-9333-1e0c0a81d873
8       9  427c33bb-dff7-4332-8d29-954728c713b1
9      10  812ad61f-2e80-4b95-ae02-a91976bd2baa

In [ ]:
print("========== PHASE 2: PRODUCT ETL VALIDATION ==========")

print("\n========== PRODUCT DATA ==========")

display(products_etl.head(20))

print("\n========== PRODUCT DATA TYPES ==========")
print(products_etl.dtypes)

print("\n========== PRODUCT ROW COUNT ==========")
print("Total rows:", len(products_etl))

print("\n========== PRODUCT ID VALIDATION ==========")

print("ProductID unique:", products_etl["ProductID"].nunique())
print("Duplicate ProductIDs:", products_etl["ProductID"].duplicated().sum())
print("Missing ProductIDs:", products_etl["ProductID"].isna().sum())
print("Minimum ProductID:", products_etl["ProductID"].min())
print("Maximum ProductID:", products_etl["ProductID"].max())

expected_product_ids = set(range(1000, 1050))
actual_product_ids = set(products_etl["ProductID"])

print(
    "Missing expected ProductIDs:",
    sorted(expected_product_ids - actual_product_ids)
)

print(
    "Unexpected ProductIDs:",
    sorted(actual_product_ids - expected_product_ids)
)

print("\n========== PRODUCT NAME VALIDATION ==========")

print("Missing ProductName:",
      products_etl["ProductName"].isna().sum())

print("Unique ProductNames:",
      products_etl["ProductName"].nunique())

print("Duplicate ProductNames:",
      products_etl["ProductName"].duplicated().sum())

print("\n========== CATEGORY VALIDATION ==========")

print("Missing Category:",
      products_etl["Category"].isna().sum())

print("Unique Categories:",
      products_etl["Category"].nunique())

print("\nCategory distribution:")
print(products_etl["Category"].value_counts())

print("\n========== FINAL PRODUCT CHECK ==========")

print("Duplicate ProductID + ProductName + Category rows:",
      products_etl.duplicated(
          subset=["ProductID", "ProductName", "Category"]
      ).sum())

========== PHASE 2: PRODUCT ETL VALIDATION ==========

========== PRODUCT DATA ==========

    ProductID        ProductName         Category
0        1000    Washing Machine  Home Appliances
1        1001       Refrigerator  Home Appliances
2        1002            Blender  Home Appliances
3        1003          Microwave  Home Appliances
4        1004     Vacuum Cleaner  Home Appliances
5        1005               Sofa        Furniture
6        1006              Table        Furniture
7        1007              Chair        Furniture
8        1008                Bed        Furniture
9        1009           Cupboard        Furniture
10       1010             Laptop      Electronics
11       1011         Smartphone      Electronics
12       1012         Headphones      Electronics
13       1013             Tablet      Electronics
14       1014             Camera      Electronics
15       1015         Smartwatch      Electronics
16       1016  Bluetooth Speaker      Electronics
17       1017                 TV      Electronics
18       1018            Monitor      Electronics
19       1019            Printer      Electronics

========== PRODUCT DATA TYPES ==========
ProductID       int64
ProductName    object
Category       object
dtype: object

========== PRODUCT ROW COUNT ==========
Total rows: 50

========== PRODUCT ID VALIDATION ==========
ProductID unique: 50
Duplicate ProductIDs: 0
Missing ProductIDs: 0
Minimum ProductID: 1000
Maximum ProductID: 1049
Missing expected ProductIDs: []
Unexpected ProductIDs: []

========== PRODUCT NAME VALIDATION ==========
Missing ProductName: 0
Unique ProductNames: 50
Duplicate ProductNames: 0

========== CATEGORY VALIDATION ==========
Missing Category: 0
Unique Categories: 4

Category distribution:
Category
Toys               20
Electronics        20
Furniture           5
Home Appliances     5
Name: count, dtype: int64

========== FINAL PRODUCT CHECK ==========
Duplicate ProductID + ProductName + Category rows: 0

In [ ]:
print("========== PHASE 2: SALES MISSING VALUE ANALYSIS ==========")

# Identify missing-value patterns
sales_missing_analysis = sales_etl.copy()

sales_missing_analysis["MissingSalesAmount"] = (
    sales_missing_analysis["SalesAmount"].isna()
)

sales_missing_analysis["MissingQuantity"] = (
    sales_missing_analysis["Quantity"].isna()
)

sales_missing_analysis["MissingPattern"] = "Complete"

sales_missing_analysis.loc[
    sales_missing_analysis["MissingSalesAmount"] &
    ~sales_missing_analysis["MissingQuantity"],
    "MissingPattern"
] = "SalesAmount Missing"

sales_missing_analysis.loc[
    ~sales_missing_analysis["MissingSalesAmount"] &
    sales_missing_analysis["MissingQuantity"],
    "MissingPattern"
] = "Quantity Missing"

sales_missing_analysis.loc[
    sales_missing_analysis["MissingSalesAmount"] &
    sales_missing_analysis["MissingQuantity"],
    "MissingPattern"
] = "Both Missing"


print("\n========== MISSING VALUE COUNTS ==========")

print(
    sales_missing_analysis["MissingPattern"]
    .value_counts()
)


print("\n========== MISSING VALUE PERCENTAGES ==========")

missing_pattern_summary = (
    sales_missing_analysis["MissingPattern"]
    .value_counts()
    .to_frame("Count")
)

missing_pattern_summary["Percentage"] = (
    missing_pattern_summary["Count"] /
    len(sales_missing_analysis) * 100
)

display(missing_pattern_summary)


print("\n========== TOTAL INCOMPLETE TRANSACTIONS ==========")

incomplete_mask = (
    sales_missing_analysis["SalesAmount"].isna() |
    sales_missing_analysis["Quantity"].isna()
)

print("Total sales transactions:",
      len(sales_missing_analysis))

print("Complete transactions:",
      (~incomplete_mask).sum())

print("Incomplete transactions:",
      incomplete_mask.sum())

print("Incomplete transaction percentage:",
      round(incomplete_mask.mean() * 100, 2))


print("\n========== INCOMPLETE TRANSACTION SAMPLE ==========")

display(
    sales_missing_analysis.loc[
        incomplete_mask,
        [
            "SaleID",
            "SourceSaleID",
            "ProductID",
            "CustomerID",
            "SalesAmount",
            "Quantity",
            "Timestamp",
            "MissingPattern"
        ]
    ].head(30)
)


print("\n========== IMPACT ON FINAL FACT TABLE ==========")

complete_sales = sales_missing_analysis[
    ~incomplete_mask
].copy()

print("Rows available for complete FactSales:",
      len(complete_sales))

print("Rows excluded if FactSales requires SalesAmount and Quantity:",
      len(sales_missing_analysis) - len(complete_sales))

print(
    "Percentage excluded:",
    round(
        (len(sales_missing_analysis) - len(complete_sales))
        / len(sales_missing_analysis) * 100,
        2
    )
)

========== PHASE 2: SALES MISSING VALUE ANALYSIS ==========

========== MISSING VALUE COUNTS ==========
MissingPattern
Complete               9397
SalesAmount Missing     490
Quantity Missing        106
Both Missing              7
Name: count, dtype: int64

========== MISSING VALUE PERCENTAGES ==========

                     Count  Percentage
MissingPattern
Complete              9397       93.97
SalesAmount Missing    490        4.90
Quantity Missing       106        1.06
Both Missing             7        0.07

========== TOTAL INCOMPLETE TRANSACTIONS ==========
Total sales transactions: 10000
Complete transactions: 9397
Incomplete transactions: 603
Incomplete transaction percentage: 6.03

========== INCOMPLETE TRANSACTION SAMPLE ==========

,SaleID,SourceSaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp,MissingPattern
3,4,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,0285,NaN,50,2024-07-06 23:39:00,SalesAmount Missing
7,8,f5953c0c-e9bc-489a-9333-1e0c0a81d873,1027,0019,1635.15,<NA>,2024-08-30 19:07:00,Quantity Missing
24,25,ea120dd2-45d7-4ad7-8368-b0467279d9d9,1003,0422,NaN,35,2024-06-19 23:12:00,SalesAmount Missing
52,53,182d4630-5e13-47ca-8047-172d8bb80d9b,1036,0484,NaN,44,2024-07-09 12:50:00,SalesAmount Missing
67,68,cfc48ad9-4630-44e4-8348-b6651673df95,1007,0482,NaN,10,2024-09-08 22:43:00,SalesAmount Missing
96,97,7e9f0322-ab86-47f5-a766-3ca0eac9e622,1047,0798,NaN,7,2024-07-20 01:19:00,SalesAmount Missing
124,125,58475ef3-15ef-4fd6-b2e0-a7c6db4fcce4,1023,1000,620.28,<NA>,2024-09-12 11:51:00,Quantity Missing
190,191,40ea2216-7874-4a56-b703-37295861e5af,1024,0136,1862.32,<NA>,2024-07-04 15:41:00,Quantity Missing
215,216,ffbbb1d8-599a-4aab-b582-86d3d3ee5037,1029,0878,NaN,28,2024-08-02 12:59:00,SalesAmount Missing
225,226,fa171b13-bdb8-426b-a555-b44e6adf39ad,1041,0858,NaN,45,2024-10-26 13:40:00,SalesAmount Missing
238,239,ab5d7adb-cede-4dd5-b830-4a8d1e58a604,1041,0307,1424.05,<NA>,2024-10-12 22:26:00,Quantity Missing
242,243,625f9ab4-53a0-45b7-9e88-9f13127e8db7,1031,0205,NaN,45,2024-09-03 08:01:00,SalesAmount Missing
261,262,815c4d88-a254-44c8-afec-67573870eeee,1033,0125,NaN,22,2024-08-17 09:20:00,SalesAmount Missing
275,276,dc8b7d00-98f9-4f4e-99c9-7c652387674a,1012,0668,NaN,28,2024-07-19 02:11:00,SalesAmount Missing
280,281,8ee802bb-52eb-4c19-951e-d54680a6300e,1041,0377,1333.88,<NA>,2024-10-13 11:44:00,Quantity Missing
281,282,271d7efa-c09c-4aef-b9f6-653d276c5a63,1016,0515,NaN,34,2024-09-15 15:07:00,SalesAmount Missing
295,296,c3d80a3d-844e-410d-9f56-7a864f330fd7,1043,0690,NaN,27,2024-09-06 09:56:00,SalesAmount Missing
296,297,d22273cb-1282-496c-afc2-81aa1181a10e,1034,0821,1492.62,<NA>,2024-08-20 20:50:00,Quantity Missing
316,317,1dcd719e-1541-47fe-b08c-7103a777400c,1031,0533,NaN,<NA>,2024-10-05 14:58:00,Both Missing
347,348,aef952e1-8c80-42b1-bad4-14941ceda93c,1047,0678,NaN,21,2024-07-24 15:08:00,SalesAmount Missing
365,366,2e1284e9-505a-409a-a3f5-cbfabadf5d18,1015,0633,NaN,7,2024-08-13 14:47:00,SalesAmount Missing
374,375,9244fca5-4b56-46a3-9516-37e3967c0a38,1008,0400,NaN,15,2024-06-11 21:29:00,SalesAmount Missing
380,381,3d8103fe-6740-43ba-8d2f-5b2e2d05cf3d,1004,0529,NaN,50,2024-06-03 03:28:00,SalesAmount Missing
387,388,42874ad3-8631-4ed4-9f9b-124cd2f6fd1f,1020,0323,NaN,42,2024-06-05 04:41:00,SalesAmount Missing
408,409,af07f679-3875-4fc0-b16e-663c842b127e,1048,0676,NaN,4,2024-09-12 09:59:00,SalesAmount Missing
423,424,a8bf0043-88f6-4d88-8541-365a6b72d33b,1009,0122,1638.24,<NA>,2024-06-21 05:24:00,Quantity Missing
424,425,1f250583-6cfb-4362-9f06-b3641421fd51,1046,0769,1315.97,<NA>,2024-11-25 12:42:00,Quantity Missing
431,432,9bf6675a-9744-453d-a63c-7d41a02a672e,1047,0500,459.30,<NA>,2024-10-22 02:59:00,Quantity Missing
433,434,77dbf1ad-1534-4d8c-85ad-6bcdc109ed4a,1048,0638,190.62,<NA>,2024-11-08 05:21:00,Quantity Missing
466,467,046535c6-ed5c-4e82-bd62-c4ae61202cde,1031,0629,NaN,41,2024-09-25 06:36:00,SalesAmount Missing

========== IMPACT ON FINAL FACT TABLE ==========
Rows available for complete FactSales: 9397
Rows excluded if FactSales requires SalesAmount and Quantity: 603
Percentage excluded: 6.03

In [ ]:
print("========== PHASE 2: CREATE COMPLETE FACT SALES CANDIDATE ==========")

# Keep all ETL records unchanged for traceability.
# Create a separate dataset for transactions eligible for FactSales.
fact_sales_etl = sales_etl[
    sales_etl["SalesAmount"].notna() &
    sales_etl["Quantity"].notna()
].copy()

print("\n========== FACT SALES CANDIDATE ==========")

print("Original Sales ETL rows:",
      len(sales_etl))

print("FactSales candidate rows:",
      len(fact_sales_etl))

print("Excluded incomplete rows:",
      len(sales_etl) - len(fact_sales_etl))


print("\n========== FACT SALES CANDIDATE DATA ==========")

display(
    fact_sales_etl[
        [
            "SaleID",
            "SourceSaleID",
            "ProductID",
            "CustomerID",
            "SalesAmount",
            "Quantity",
            "Timestamp"
        ]
    ].head(20)
)


print("\n========== NULL VALIDATION ==========")

print("Missing SaleID:",
      fact_sales_etl["SaleID"].isna().sum())

print("Missing SourceSaleID:",
      fact_sales_etl["SourceSaleID"].isna().sum())

print("Missing ProductID:",
      fact_sales_etl["ProductID"].isna().sum())

print("Missing CustomerID:",
      fact_sales_etl["CustomerID"].isna().sum())

print("Missing SalesAmount:",
      fact_sales_etl["SalesAmount"].isna().sum())

print("Missing Quantity:",
      fact_sales_etl["Quantity"].isna().sum())

print("Missing Timestamp:",
      fact_sales_etl["Timestamp"].isna().sum())


print("\n========== KEY VALIDATION ==========")

print("SaleID unique:",
      fact_sales_etl["SaleID"].nunique() == len(fact_sales_etl))

print("SourceSaleID unique:",
      fact_sales_etl["SourceSaleID"].nunique() == len(fact_sales_etl))

print("ProductID unique values:",
      fact_sales_etl["ProductID"].nunique())

print("CustomerID unique values:",
      fact_sales_etl["CustomerID"].nunique())


print("\n========== FACT SALES DATA TYPES ==========")

print(fact_sales_etl.dtypes)

========== PHASE 2: CREATE COMPLETE FACT SALES CANDIDATE ==========

========== FACT SALES CANDIDATE ==========
Original Sales ETL rows: 10000
FactSales candidate rows: 9397
Excluded incomplete rows: 603

========== FACT SALES CANDIDATE DATA ==========

,SaleID,SourceSaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp
0,1,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,0460,1639.10,18,2024-08-09 20:21:00
1,2,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,0198,186.11,42,2024-11-28 05:01:00
2,3,8666f277-cc58-4fde-9d58-697da9e040f2,1012,0524,1712.72,49,2024-10-13 00:36:00
4,5,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,0369,66.36,21,2024-06-08 19:58:00
5,6,d71733ac-4fc4-42e6-ae48-c2150c8a92ae,1016,0709,1705.51,31,2024-11-15 12:24:00
6,7,b7475afb-27f7-46fe-8bcd-c099c178d17f,1047,0929,1509.94,3,2024-08-28 05:43:00
8,9,427c33bb-dff7-4332-8d29-954728c713b1,1020,0983,1070.59,31,2024-10-22 15:17:00
9,10,812ad61f-2e80-4b95-ae02-a91976bd2baa,1006,0536,1097.00,2,2024-06-20 09:59:00
10,11,a18dadb3-b2e6-476e-b2fb-b4a477721bf0,1005,0164,683.83,38,2024-11-15 09:33:00
11,12,fb7031b8-6ea9-48f1-9a00-9bc178359f8d,1017,0955,1187.22,26,2024-07-07 00:55:00
12,13,16380106-881a-4b17-b7a6-cdb1cb7b0310,1046,0102,1660.55,37,2024-06-10 20:40:00
13,14,3b8b6be3-3531-4e99-bb88-f690abf80831,1039,0246,1285.76,12,2024-10-31 22:31:00
14,15,1c2ea051-0ea9-4464-9328-f005529e49b0,1044,0231,580.56,2,2024-10-30 09:54:00
15,16,385f4dc3-93d8-4aea-9448-9ae392f1c70f,1012,0266,1729.19,38,2024-09-22 19:51:00
16,17,65286b1d-53a6-4935-a98a-1cb1876e571e,1018,0558,1700.77,44,2024-09-28 12:04:00
17,18,a71af1cd-5827-45bc-9819-7b822084b056,1004,0267,1685.47,20,2024-07-29 14:48:00
18,19,fc2fbc9b-7dd9-47f9-8c88-f4657b809fda,1023,0647,960.80,37,2024-08-17 13:20:00
19,20,d5ffcbb0-4af7-471e-a978-8d26a139e065,1030,0099,1220.63,5,2024-08-20 12:26:00
20,21,0ca44dee-070d-4ba5-92f5-4294061c1b6a,1002,0152,415.25,29,2024-09-12 16:38:00
21,22,f97142ca-80a7-4ab5-8c96-7b0469fb88a5,1027,0036,1493.54,42,2024-09-09 02:48:00

========== NULL VALIDATION ==========
Missing SaleID: 0
Missing SourceSaleID: 0
Missing ProductID: 0
Missing CustomerID: 0
Missing SalesAmount: 0
Missing Quantity: 0
Missing Timestamp: 0

========== KEY VALIDATION ==========
SaleID unique: True
SourceSaleID unique: True
ProductID unique values: 50
CustomerID unique values: 1000

========== FACT SALES DATA TYPES ==========
SaleID                   int64
ProductID                int64
CustomerID              object
SalesAmount            float64
Quantity                 Int64
Timestamp       datetime64[ns]
SourceSaleID            object
dtype: object

In [ ]:
print("========== PHASE 2: STANDARDIZE PRODUCT ETL ==========")

# Standardize ProductID
products_etl["ProductID"] = pd.to_numeric(
    products_etl["ProductID"],
    errors="coerce"
).astype("Int64")

# Standardize ProductName
products_etl["ProductName"] = (
    products_etl["ProductName"]
    .astype("string")
    .str.strip()
)

# Standardize Category
products_etl["Category"] = (
    products_etl["Category"]
    .astype("string")
    .str.strip()
)

print("\n========== UPDATED PRODUCT DATA ==========")

display(products_etl.head(20))

print("\n========== PRODUCT DATA TYPES ==========")

print(products_etl.dtypes)

print("\n========== PRODUCT VALIDATION ==========")

print("Rows:", len(products_etl))
print("Missing ProductID:", products_etl["ProductID"].isna().sum())
print("Missing ProductName:", products_etl["ProductName"].isna().sum())
print("Missing Category:", products_etl["Category"].isna().sum())

print("Unique ProductIDs:", products_etl["ProductID"].nunique())
print("Unique ProductNames:", products_etl["ProductName"].nunique())
print("Unique Categories:", products_etl["Category"].nunique())

print("\n========== CATEGORY VALUES ==========")

print(
    products_etl["Category"]
    .value_counts()
)

========== PHASE 2: STANDARDIZE PRODUCT ETL ==========

========== UPDATED PRODUCT DATA ==========

    ProductID        ProductName         Category
0        1000    Washing Machine  Home Appliances
1        1001       Refrigerator  Home Appliances
2        1002            Blender  Home Appliances
3        1003          Microwave  Home Appliances
4        1004     Vacuum Cleaner  Home Appliances
5        1005               Sofa        Furniture
6        1006              Table        Furniture
7        1007              Chair        Furniture
8        1008                Bed        Furniture
9        1009           Cupboard        Furniture
10       1010             Laptop      Electronics
11       1011         Smartphone      Electronics
12       1012         Headphones      Electronics
13       1013             Tablet      Electronics
14       1014             Camera      Electronics
15       1015         Smartwatch      Electronics
16       1016  Bluetooth Speaker      Electronics
17       1017                 TV      Electronics
18       1018            Monitor      Electronics
19       1019            Printer      Electronics

========== PRODUCT DATA TYPES ==========
ProductID               Int64
ProductName    string[python]
Category       string[python]
dtype: object

========== PRODUCT VALIDATION ==========
Rows: 50
Missing ProductID: 0
Missing ProductName: 0
Missing Category: 0
Unique ProductIDs: 50
Unique ProductNames: 50
Unique Categories: 4

========== CATEGORY VALUES ==========
Category
Toys               20
Electronics        20
Furniture           5
Home Appliances     5
Name: count, dtype: Int64

In [ ]:
print("========== PHASE 2: STANDARDIZE CUSTOMER ETL ==========")

# CustomerID must remain a 4-digit string
customers_etl["CustomerID"] = (
    customers_etl["CustomerID"]
    .astype("string")
    .str.strip()
    .str.zfill(4)
)

# Standardize customer text fields
customers_etl["FirstName"] = (
    customers_etl["FirstName"]
    .astype("string")
    .str.strip()
)

customers_etl["LastName"] = (
    customers_etl["LastName"]
    .astype("string")
    .str.strip()
)

customers_etl["Gender"] = (
    customers_etl["Gender"]
    .astype("string")
    .str.strip()
)

customers_etl["Region"] = (
    customers_etl["Region"]
    .astype("string")
    .str.strip()
)

# SSN remains a string because leading zeros must be preserved
customers_etl["SSN"] = (
    customers_etl["SSN"]
    .astype("string")
    .str.strip()
)

print("\n========== UPDATED CUSTOMER DATA ==========")

display(
    customers_etl[
        [
            "CustomerID",
            "FirstName",
            "LastName",
            "Gender",
            "Region",
            "SSN"
        ]
    ].head(20)
)

print("\n========== CUSTOMER DATA TYPES ==========")

print(customers_etl.dtypes)

print("\n========== CUSTOMER VALIDATION ==========")

print("Rows:", len(customers_etl))

print("Unique CustomerIDs:",
      customers_etl["CustomerID"].nunique())

print("Duplicate CustomerIDs:",
      customers_etl["CustomerID"].duplicated().sum())

print("Missing CustomerIDs:",
      customers_etl["CustomerID"].isna().sum())

print("Invalid CustomerID length:",
      (customers_etl["CustomerID"].str.len() != 4).sum())

print("Missing FirstName:",
      customers_etl["FirstName"].isna().sum())

print("Missing LastName:",
      customers_etl["LastName"].isna().sum())

print("Missing Gender:",
      customers_etl["Gender"].isna().sum())

print("Missing Region:",
      customers_etl["Region"].isna().sum())

print("Missing SSN:",
      customers_etl["SSN"].isna().sum())

print("\n========== CUSTOMER CATEGORIES ==========")

print("Gender:")
print(customers_etl["Gender"].value_counts(dropna=False))

print("\nRegion:")
print(customers_etl["Region"].value_counts(dropna=False))

========== PHASE 2: STANDARDIZE CUSTOMER ETL ==========

========== UPDATED CUSTOMER DATA ==========

   CustomerID FirstName   LastName  Gender      Region        SSN
0        0001   Gregory     Miller    Male        Ohio  082573197
1        0002    Marvin       <NA>    Male  California  309625621
2        0003   Gregory      Smith    Male    New York  407071725
3        0004    Edward      Davis    Male        Ohio  948185740
4        0005  Reginald     Dawson    Male       Texas  975723056
5        0006  Virginia     Bryant  Female        Ohio  981727452
6        0007  Benjamin   Shepherd    Male        Ohio  048008736
7        0008    Robert     Pierce    Male    New York  009012352
8        0009    Samuel  Mcconnell    Male  California  007348687
9        0010     Jason       <NA>    Male    New York  785769341
10       0011     Jason    Morales    Male     Unknown  325235301
11       0012   Charles       <NA>    Male    New York  239140962
12       0013   Brandon       <NA>    Male        Ohio  573359511
13       0014   Jeffery    Cabrera    Male    New York  705131809
14       0015   William   Gonzalez    Male    New York  058131272
15       0016       Joe    Barnett    Male        Ohio  995874707
16       0017    Angela   Cantrell  Female       Texas  648610422
17       0018    Mariah     Wilson  Female    New York  108825602
18       0019   Michael       <NA>    Male    New York  018105442
19       0020    Robert       <NA>    Male    New York  029416639

========== CUSTOMER DATA TYPES ==========
CustomerID    string[python]
FirstName     string[python]
LastName      string[python]
Gender        string[python]
Region        string[python]
SSN           string[python]
dtype: object

========== CUSTOMER VALIDATION ==========
Rows: 1000
Unique CustomerIDs: 1000
Duplicate CustomerIDs: 0
Missing CustomerIDs: 0
Invalid CustomerID length: 0
Missing FirstName: 0
Missing LastName: 290
Missing Gender: 0
Missing Region: 0
Missing SSN: 0

========== CUSTOMER CATEGORIES ==========
Gender:
Gender
Male      783
Female    217
Name: count, dtype: Int64

Region:
Region
New York      377
Texas         194
California    192
Ohio          175
Unknown        62
Name: count, dtype: Int64

In [ ]:
print("========== PHASE 2: CREATE DATE DIMENSION ==========")

# Get the complete range of transaction dates
min_date = fact_sales_etl["Timestamp"].min().normalize()
max_date = fact_sales_etl["Timestamp"].max().normalize()

print("Minimum transaction date:", min_date.date())
print("Maximum transaction date:", max_date.date())

# Create continuous calendar date range
date_range = pd.date_range(
    start=min_date,
    end=max_date,
    freq="D"
)

dim_date = pd.DataFrame({
    "FullDate": date_range
})

# Date key in YYYYMMDD format
dim_date["DateKey"] = (
    dim_date["FullDate"]
    .dt.strftime("%Y%m%d")
    .astype(int)
)

# Calendar attributes
dim_date["Year"] = dim_date["FullDate"].dt.year
dim_date["MonthNumber"] = dim_date["FullDate"].dt.month
dim_date["MonthName"] = dim_date["FullDate"].dt.month_name()
dim_date["Quarter"] = (
    "Q" + dim_date["FullDate"].dt.quarter.astype(str)
)
dim_date["Day"] = dim_date["FullDate"].dt.day
dim_date["DayName"] = dim_date["FullDate"].dt.day_name()
dim_date["DayOfWeek"] = (
    dim_date["FullDate"].dt.dayofweek + 1
)

# Reorder columns
dim_date = dim_date[
    [
        "DateKey",
        "FullDate",
        "Year",
        "MonthNumber",
        "MonthName",
        "Quarter",
        "Day",
        "DayName",
        "DayOfWeek"
    ]
]

print("\n========== DATE DIMENSION SAMPLE ==========")

display(dim_date.head(15))

print("\n========== DATE DIMENSION END ==========")

display(dim_date.tail(15))

print("\n========== DATE DIMENSION VALIDATION ==========")

print("Total calendar dates:", len(dim_date))

print("Minimum DateKey:", dim_date["DateKey"].min())
print("Maximum DateKey:", dim_date["DateKey"].max())

print("Unique DateKeys:",
      dim_date["DateKey"].nunique())

print("Duplicate DateKeys:",
      dim_date["DateKey"].duplicated().sum())

print("Missing DateKeys:",
      dim_date["DateKey"].isna().sum())

print("Missing FullDate:",
      dim_date["FullDate"].isna().sum())

print("Years:",
      sorted(dim_date["Year"].unique()))

print("Months:",
      dim_date["MonthNumber"].nunique())

print("Quarters:",
      sorted(dim_date["Quarter"].unique()))

print("\n========== DATE COVERAGE CHECK ==========")

transaction_dates = fact_sales_etl["Timestamp"].dt.normalize()

missing_transaction_dates = set(transaction_dates) - set(dim_date["FullDate"])

print(
    "Transaction dates missing from DimDate:",
    len(missing_transaction_dates)
)

========== PHASE 2: CREATE DATE DIMENSION ==========
Minimum transaction date: 2024-06-01
Maximum transaction date: 2024-11-28

========== DATE DIMENSION SAMPLE ==========

,DateKey,FullDate,Year,MonthNumber,MonthName,Quarter,Day,DayName,DayOfWeek
0,20240601,2024-06-01,2024,6,June,Q2,1,Saturday,6
1,20240602,2024-06-02,2024,6,June,Q2,2,Sunday,7
2,20240603,2024-06-03,2024,6,June,Q2,3,Monday,1
3,20240604,2024-06-04,2024,6,June,Q2,4,Tuesday,2
4,20240605,2024-06-05,2024,6,June,Q2,5,Wednesday,3
5,20240606,2024-06-06,2024,6,June,Q2,6,Thursday,4
6,20240607,2024-06-07,2024,6,June,Q2,7,Friday,5
7,20240608,2024-06-08,2024,6,June,Q2,8,Saturday,6
8,20240609,2024-06-09,2024,6,June,Q2,9,Sunday,7
9,20240610,2024-06-10,2024,6,June,Q2,10,Monday,1
10,20240611,2024-06-11,2024,6,June,Q2,11,Tuesday,2
11,20240612,2024-06-12,2024,6,June,Q2,12,Wednesday,3
12,20240613,2024-06-13,2024,6,June,Q2,13,Thursday,4
13,20240614,2024-06-14,2024,6,June,Q2,14,Friday,5
14,20240615,2024-06-15,2024,6,June,Q2,15,Saturday,6

========== DATE DIMENSION END ==========

,DateKey,FullDate,Year,MonthNumber,MonthName,Quarter,Day,DayName,DayOfWeek
166,20241114,2024-11-14,2024,11,November,Q4,14,Thursday,4
167,20241115,2024-11-15,2024,11,November,Q4,15,Friday,5
168,20241116,2024-11-16,2024,11,November,Q4,16,Saturday,6
169,20241117,2024-11-17,2024,11,November,Q4,17,Sunday,7
170,20241118,2024-11-18,2024,11,November,Q4,18,Monday,1
171,20241119,2024-11-19,2024,11,November,Q4,19,Tuesday,2
172,20241120,2024-11-20,2024,11,November,Q4,20,Wednesday,3
173,20241121,2024-11-21,2024,11,November,Q4,21,Thursday,4
174,20241122,2024-11-22,2024,11,November,Q4,22,Friday,5
175,20241123,2024-11-23,2024,11,November,Q4,23,Saturday,6
176,20241124,2024-11-24,2024,11,November,Q4,24,Sunday,7
177,20241125,2024-11-25,2024,11,November,Q4,25,Monday,1
178,20241126,2024-11-26,2024,11,November,Q4,26,Tuesday,2
179,20241127,2024-11-27,2024,11,November,Q4,27,Wednesday,3
180,20241128,2024-11-28,2024,11,November,Q4,28,Thursday,4

========== DATE DIMENSION VALIDATION ==========
Total calendar dates: 181
Minimum DateKey: 20240601
Maximum DateKey: 20241128
Unique DateKeys: 181
Duplicate DateKeys: 0
Missing DateKeys: 0
Missing FullDate: 0
Years: [np.int32(2024)]
Months: 6
Quarters: ['Q2', 'Q3', 'Q4']

========== DATE COVERAGE CHECK ==========
Transaction dates missing from DimDate: 0

In [ ]:
print("========== PHASE 2: ADD DATEKEY TO FACT SALES ==========")

# Create a date-only column temporarily for joining with DimDate
fact_sales_etl["TransactionDate"] = (
    fact_sales_etl["Timestamp"].dt.normalize()
)

# Map each transaction date to the corresponding DateKey
fact_sales_etl = fact_sales_etl.merge(
    dim_date[["DateKey", "FullDate"]],
    left_on="TransactionDate",
    right_on="FullDate",
    how="left",
    validate="many_to_one"
)

# Remove temporary/join columns
fact_sales_etl.drop(
    columns=["TransactionDate", "FullDate"],
    inplace=True
)

# Reorder columns
fact_sales_etl = fact_sales_etl[
    [
        "SaleID",
        "SourceSaleID",
        "ProductID",
        "CustomerID",
        "DateKey",
        "SalesAmount",
        "Quantity",
        "Timestamp"
    ]
]

print("\n========== UPDATED FACT SALES ==========")

display(fact_sales_etl.head(20))

print("\n========== FACT SALES DATA TYPES ==========")

print(fact_sales_etl.dtypes)

print("\n========== DATEKEY VALIDATION ==========")

print("Missing DateKey:",
      fact_sales_etl["DateKey"].isna().sum())

print("Unique DateKeys used:",
      fact_sales_etl["DateKey"].nunique())

print("Minimum DateKey:",
      fact_sales_etl["DateKey"].min())

print("Maximum DateKey:",
      fact_sales_etl["DateKey"].max())

print("\n========== DATEKEY REFERENTIAL INTEGRITY ==========")

missing_datekeys = set(
    fact_sales_etl["DateKey"].dropna()
) - set(
    dim_date["DateKey"]
)

print(
    "DateKeys in FactSales missing from DimDate:",
    len(missing_datekeys)
)

print("\n========== FACT SALES ROW COUNT CHECK ==========")

print("FactSales rows:", len(fact_sales_etl))
print("Expected rows:", 9397)
print("Row count preserved:",
      len(fact_sales_etl) == 9397)

========== PHASE 2: ADD DATEKEY TO FACT SALES ==========

========== UPDATED FACT SALES ==========

,SaleID,SourceSaleID,ProductID,CustomerID,DateKey,SalesAmount,Quantity,Timestamp
0,1,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,0460,20240809,1639.10,18,2024-08-09 20:21:00
1,2,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,0198,20241128,186.11,42,2024-11-28 05:01:00
2,3,8666f277-cc58-4fde-9d58-697da9e040f2,1012,0524,20241013,1712.72,49,2024-10-13 00:36:00
3,5,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,0369,20240608,66.36,21,2024-06-08 19:58:00
4,6,d71733ac-4fc4-42e6-ae48-c2150c8a92ae,1016,0709,20241115,1705.51,31,2024-11-15 12:24:00
5,7,b7475afb-27f7-46fe-8bcd-c099c178d17f,1047,0929,20240828,1509.94,3,2024-08-28 05:43:00
6,9,427c33bb-dff7-4332-8d29-954728c713b1,1020,0983,20241022,1070.59,31,2024-10-22 15:17:00
7,10,812ad61f-2e80-4b95-ae02-a91976bd2baa,1006,0536,20240620,1097.00,2,2024-06-20 09:59:00
8,11,a18dadb3-b2e6-476e-b2fb-b4a477721bf0,1005,0164,20241115,683.83,38,2024-11-15 09:33:00
9,12,fb7031b8-6ea9-48f1-9a00-9bc178359f8d,1017,0955,20240707,1187.22,26,2024-07-07 00:55:00
10,13,16380106-881a-4b17-b7a6-cdb1cb7b0310,1046,0102,20240610,1660.55,37,2024-06-10 20:40:00
11,14,3b8b6be3-3531-4e99-bb88-f690abf80831,1039,0246,20241031,1285.76,12,2024-10-31 22:31:00
12,15,1c2ea051-0ea9-4464-9328-f005529e49b0,1044,0231,20241030,580.56,2,2024-10-30 09:54:00
13,16,385f4dc3-93d8-4aea-9448-9ae392f1c70f,1012,0266,20240922,1729.19,38,2024-09-22 19:51:00
14,17,65286b1d-53a6-4935-a98a-1cb1876e571e,1018,0558,20240928,1700.77,44,2024-09-28 12:04:00
15,18,a71af1cd-5827-45bc-9819-7b822084b056,1004,0267,20240729,1685.47,20,2024-07-29 14:48:00
16,19,fc2fbc9b-7dd9-47f9-8c88-f4657b809fda,1023,0647,20240817,960.80,37,2024-08-17 13:20:00
17,20,d5ffcbb0-4af7-471e-a978-8d26a139e065,1030,0099,20240820,1220.63,5,2024-08-20 12:26:00
18,21,0ca44dee-070d-4ba5-92f5-4294061c1b6a,1002,0152,20240912,415.25,29,2024-09-12 16:38:00
19,22,f97142ca-80a7-4ab5-8c96-7b0469fb88a5,1027,0036,20240909,1493.54,42,2024-09-09 02:48:00

========== FACT SALES DATA TYPES ==========
SaleID                   int64
SourceSaleID            object
ProductID                int64
CustomerID              object
DateKey                  int64
SalesAmount            float64
Quantity                 Int64
Timestamp       datetime64[ns]
dtype: object

========== DATEKEY VALIDATION ==========
Missing DateKey: 0
Unique DateKeys used: 181
Minimum DateKey: 20240601
Maximum DateKey: 20241128

========== DATEKEY REFERENTIAL INTEGRITY ==========
DateKeys in FactSales missing from DimDate: 0

========== FACT SALES ROW COUNT CHECK ==========
FactSales rows: 9397
Expected rows: 9397
Row count preserved: True

In [ ]:
print("========== PHASE 2: FACT SALES FOREIGN KEY VALIDATION ==========")

print("\n========== CUSTOMER FOREIGN KEY ==========")

fact_customer_ids = set(
    fact_sales_etl["CustomerID"].dropna()
)

dimension_customer_ids = set(
    customers_etl["CustomerID"].dropna()
)

missing_customer_ids = (
    fact_customer_ids - dimension_customer_ids
)

print("Unique CustomerIDs in FactSales:",
      len(fact_customer_ids))

print("Unique CustomerIDs in DimCustomer:",
      len(dimension_customer_ids))

print("CustomerIDs missing from DimCustomer:",
      len(missing_customer_ids))

if missing_customer_ids:
    print("Missing CustomerIDs:", sorted(missing_customer_ids))
else:
    print("Customer FK validation: PASS")


print("\n========== PRODUCT FOREIGN KEY ==========")

fact_product_ids = set(
    fact_sales_etl["ProductID"].dropna()
)

dimension_product_ids = set(
    products_etl["ProductID"].dropna()
)

missing_product_ids = (
    fact_product_ids - dimension_product_ids
)

print("Unique ProductIDs in FactSales:",
      len(fact_product_ids))

print("Unique ProductIDs in DimProduct:",
      len(dimension_product_ids))

print("ProductIDs missing from DimProduct:",
      len(missing_product_ids))

if missing_product_ids:
    print("Missing ProductIDs:", sorted(missing_product_ids))
else:
    print("Product FK validation: PASS")


print("\n========== DATE FOREIGN KEY ==========")

fact_datekeys = set(
    fact_sales_etl["DateKey"].dropna()
)

dimension_datekeys = set(
    dim_date["DateKey"].dropna()
)

missing_datekeys = (
    fact_datekeys - dimension_datekeys
)

print("Unique DateKeys in FactSales:",
      len(fact_datekeys))

print("Unique DateKeys in DimDate:",
      len(dimension_datekeys))

print("DateKeys missing from DimDate:",
      len(missing_datekeys))

if missing_datekeys:
    print("Missing DateKeys:", sorted(missing_datekeys))
else:
    print("Date FK validation: PASS")


print("\n========== OVERALL FOREIGN KEY STATUS ==========")

overall_fk_status = (
    len(missing_customer_ids) == 0 and
    len(missing_product_ids) == 0 and
    len(missing_datekeys) == 0
)

print(
    "FactSales foreign key validation:",
    "PASS" if overall_fk_status else "FAIL"
)

========== PHASE 2: FACT SALES FOREIGN KEY VALIDATION ==========

========== CUSTOMER FOREIGN KEY ==========
Unique CustomerIDs in FactSales: 1000
Unique CustomerIDs in DimCustomer: 1000
CustomerIDs missing from DimCustomer: 0
Customer FK validation: PASS

========== PRODUCT FOREIGN KEY ==========
Unique ProductIDs in FactSales: 50
Unique ProductIDs in DimProduct: 50
ProductIDs missing from DimProduct: 0
Product FK validation: PASS

========== DATE FOREIGN KEY ==========
Unique DateKeys in FactSales: 181
Unique DateKeys in DimDate: 181
DateKeys missing from DimDate: 0
Date FK validation: PASS

========== OVERALL FOREIGN KEY STATUS ==========
FactSales foreign key validation: PASS

In [ ]:
print("========== PHASE 2: STEP 17 — FINAL DIMCUSTOMER ==========")

dim_customer = customers_etl[
    [
        "CustomerID",
        "FirstName",
        "LastName",
        "Gender",
        "Region",
        "SSN"
    ]
].copy()

print("\n========== DIMCUSTOMER STRUCTURE ==========")

print("Rows:", len(dim_customer))
print("Columns:", len(dim_customer.columns))

print("\nColumns:")
print(dim_customer.columns.tolist())

print("\nData types:")
print(dim_customer.dtypes)

print("\n========== KEY VALIDATION ==========")

print("Unique CustomerIDs:", dim_customer["CustomerID"].nunique())
print("Duplicate CustomerIDs:",
      dim_customer["CustomerID"].duplicated().sum())

print("Missing CustomerIDs:",
      dim_customer["CustomerID"].isna().sum())

print("\n========== MISSING VALUES ==========")

print(
    dim_customer.isna().sum()
)

print("\n========== CUSTOMER DISTRIBUTION ==========")

print("\nGender:")
print(dim_customer["Gender"].value_counts(dropna=False))

print("\nRegion:")
print(dim_customer["Region"].value_counts(dropna=False))

print("\n========== SAMPLE DATA ==========")

print(dim_customer.head(10))

print("\n========== DIMCUSTOMER STATUS ==========")

dim_customer_status = (
    len(dim_customer) == 1000
    and dim_customer["CustomerID"].nunique() == 1000
    and dim_customer["CustomerID"].isna().sum() == 0
    and dim_customer["CustomerID"].duplicated().sum() == 0
)

print(
    "DimCustomer validation:",
    "PASS" if dim_customer_status else "FAIL"
)

========== PHASE 2: STEP 17 — FINAL DIMCUSTOMER ==========

========== DIMCUSTOMER STRUCTURE ==========
Rows: 1000
Columns: 6

Columns:
['CustomerID', 'FirstName', 'LastName', 'Gender', 'Region', 'SSN']

Data types:
CustomerID    string[python]
FirstName     string[python]
LastName      string[python]
Gender        string[python]
Region        string[python]
SSN           string[python]
dtype: object

========== KEY VALIDATION ==========
Unique CustomerIDs: 1000
Duplicate CustomerIDs: 0
Missing CustomerIDs: 0

========== MISSING VALUES ==========
CustomerID      0
FirstName       0
LastName      290
Gender          0
Region          0
SSN             0
dtype: int64

========== CUSTOMER DISTRIBUTION ==========

Gender:
Gender
Male      783
Female    217
Name: count, dtype: Int64

Region:
Region
New York      377
Texas         194
California    192
Ohio          175
Unknown        62
Name: count, dtype: Int64

========== SAMPLE DATA ==========
  CustomerID FirstName   LastName  Gender      Region        SSN
0       0001   Gregory     Miller    Male        Ohio  082573197
1       0002    Marvin       <NA>    Male  California  309625621
2       0003   Gregory      Smith    Male    New York  407071725
3       0004    Edward      Davis    Male        Ohio  948185740
4       0005  Reginald     Dawson    Male       Texas  975723056
5       0006  Virginia     Bryant  Female        Ohio  981727452
6       0007  Benjamin   Shepherd    Male        Ohio  048008736
7       0008    Robert     Pierce    Male    New York  009012352
8       0009    Samuel  Mcconnell    Male  California  007348687
9       0010     Jason       <NA>    Male    New York  785769341

========== DIMCUSTOMER STATUS ==========
DimCustomer validation: PASS

In [ ]:
print("========== PHASE 2: STEP 18 — FINAL DIMPRODUCT ==========")

dim_product = products_etl[
    [
        "ProductID",
        "ProductName",
        "Category"
    ]
].copy()

print("\n========== DIMPRODUCT STRUCTURE ==========")

print("Rows:", len(dim_product))
print("Columns:", len(dim_product.columns))

print("\nColumns:")
print(dim_product.columns.tolist())

print("\nData types:")
print(dim_product.dtypes)

print("\n========== KEY VALIDATION ==========")

print("Unique ProductIDs:",
      dim_product["ProductID"].nunique())

print("Duplicate ProductIDs:",
      dim_product["ProductID"].duplicated().sum())

print("Missing ProductIDs:",
      dim_product["ProductID"].isna().sum())

print("\n========== PRODUCT NAME VALIDATION ==========")

print("Missing ProductNames:",
      dim_product["ProductName"].isna().sum())

print("Unique ProductNames:",
      dim_product["ProductName"].nunique())

print("Duplicate ProductNames:",
      dim_product["ProductName"].duplicated().sum())

print("\n========== CATEGORY VALIDATION ==========")

print("Missing Categories:",
      dim_product["Category"].isna().sum())

print("Unique Categories:",
      dim_product["Category"].nunique())

print("\nCategory distribution:")
print(
    dim_product["Category"].value_counts()
)

print("\n========== PRODUCT ID RANGE ==========")

print("Minimum ProductID:",
      dim_product["ProductID"].min())

print("Maximum ProductID:",
      dim_product["ProductID"].max())

expected_product_ids = set(range(1000, 1050))

actual_product_ids = set(
    dim_product["ProductID"].dropna()
)

missing_expected_ids = (
    expected_product_ids - actual_product_ids
)

unexpected_ids = (
    actual_product_ids - expected_product_ids
)

print("Missing expected ProductIDs:",
      len(missing_expected_ids))

print("Unexpected ProductIDs:",
      len(unexpected_ids))

print("\n========== SAMPLE DATA ==========")

print(dim_product.head(10))

print("\n========== DIMPRODUCT STATUS ==========")

dim_product_status = (
    len(dim_product) == 50
    and dim_product["ProductID"].nunique() == 50
    and dim_product["ProductID"].isna().sum() == 0
    and dim_product["ProductID"].duplicated().sum() == 0
    and dim_product["ProductName"].isna().sum() == 0
    and dim_product["ProductName"].nunique() == 50
    and dim_product["Category"].isna().sum() == 0
    and dim_product["Category"].nunique() == 4
    and len(missing_expected_ids) == 0
    and len(unexpected_ids) == 0
)

print(
    "DimProduct validation:",
    "PASS" if dim_product_status else "FAIL"
)

========== PHASE 2: STEP 18 — FINAL DIMPRODUCT ==========

========== DIMPRODUCT STRUCTURE ==========
Rows: 50
Columns: 3

Columns:
['ProductID', 'ProductName', 'Category']

Data types:
ProductID               Int64
ProductName    string[python]
Category       string[python]
dtype: object

========== KEY VALIDATION ==========
Unique ProductIDs: 50
Duplicate ProductIDs: 0
Missing ProductIDs: 0

========== PRODUCT NAME VALIDATION ==========
Missing ProductNames: 0
Unique ProductNames: 50
Duplicate ProductNames: 0

========== CATEGORY VALIDATION ==========
Missing Categories: 0
Unique Categories: 4

Category distribution:
Category
Toys               20
Electronics        20
Furniture           5
Home Appliances     5
Name: count, dtype: Int64

========== PRODUCT ID RANGE ==========
Minimum ProductID: 1000
Maximum ProductID: 1049
Missing expected ProductIDs: 0
Unexpected ProductIDs: 0

========== SAMPLE DATA ==========
   ProductID      ProductName         Category
0       1000  Washing Machine  Home Appliances
1       1001     Refrigerator  Home Appliances
2       1002          Blender  Home Appliances
3       1003        Microwave  Home Appliances
4       1004   Vacuum Cleaner  Home Appliances
5       1005             Sofa        Furniture
6       1006            Table        Furniture
7       1007            Chair        Furniture
8       1008              Bed        Furniture
9       1009         Cupboard        Furniture

========== DIMPRODUCT STATUS ==========
DimProduct validation: PASS

In [ ]:
print("========== PHASE 2: STEP 19 — FINAL FACTSALES ==========")

fact_sales = fact_sales_etl[
    [
        "SaleID",
        "SourceSaleID",
        "ProductID",
        "CustomerID",
        "DateKey",
        "SalesAmount",
        "Quantity",
        "Timestamp"
    ]
].copy()

print("\n========== FACTSALES STRUCTURE ==========")

print("Rows:", len(fact_sales))
print("Columns:", len(fact_sales.columns))

print("\nColumns:")
print(fact_sales.columns.tolist())

print("\nData types:")
print(fact_sales.dtypes)

print("\n========== PRIMARY KEY VALIDATION ==========")

print("Unique SaleIDs:",
      fact_sales["SaleID"].nunique())

print("Duplicate SaleIDs:",
      fact_sales["SaleID"].duplicated().sum())

print("Missing SaleIDs:",
      fact_sales["SaleID"].isna().sum())

print("\n========== SOURCE SALE ID VALIDATION ==========")

print("Unique SourceSaleIDs:",
      fact_sales["SourceSaleID"].nunique())

print("Duplicate SourceSaleIDs:",
      fact_sales["SourceSaleID"].duplicated().sum())

print("Missing SourceSaleIDs:",
      fact_sales["SourceSaleID"].isna().sum())

print("\n========== FOREIGN KEY COLUMNS ==========")

print("Unique ProductIDs:",
      fact_sales["ProductID"].nunique())

print("Unique CustomerIDs:",
      fact_sales["CustomerID"].nunique())

print("Unique DateKeys:",
      fact_sales["DateKey"].nunique())

print("\n========== NULL VALIDATION ==========")

print(fact_sales.isna().sum())

print("\n========== FACTSALES RANGE ==========")

print("SaleID Min:", fact_sales["SaleID"].min())
print("SaleID Max:", fact_sales["SaleID"].max())

print("SalesAmount Min:", fact_sales["SalesAmount"].min())
print("SalesAmount Max:", fact_sales["SalesAmount"].max())

print("Quantity Min:", fact_sales["Quantity"].min())
print("Quantity Max:", fact_sales["Quantity"].max())

print("DateKey Min:", fact_sales["DateKey"].min())
print("DateKey Max:", fact_sales["DateKey"].max())

print("\n========== SAMPLE DATA ==========")

print(fact_sales.head(10))

print("\n========== FACTSALES STATUS ==========")

fact_sales_status = (
    len(fact_sales) == 9397
    and fact_sales["SaleID"].nunique() == 9397
    and fact_sales["SaleID"].isna().sum() == 0
    and fact_sales["SourceSaleID"].nunique() == 9397
    and fact_sales["SourceSaleID"].isna().sum() == 0
    and fact_sales["ProductID"].isna().sum() == 0
    and fact_sales["CustomerID"].isna().sum() == 0
    and fact_sales["DateKey"].isna().sum() == 0
    and fact_sales["SalesAmount"].isna().sum() == 0
    and fact_sales["Quantity"].isna().sum() == 0
    and fact_sales["Timestamp"].isna().sum() == 0
)

print(
    "FactSales validation:",
    "PASS" if fact_sales_status else "FAIL"
)

========== PHASE 2: STEP 19 — FINAL FACTSALES ==========

========== FACTSALES STRUCTURE ==========
Rows: 9397
Columns: 8

Columns:
['SaleID', 'SourceSaleID', 'ProductID', 'CustomerID', 'DateKey', 'SalesAmount', 'Quantity', 'Timestamp']

Data types:
SaleID                   int64
SourceSaleID            object
ProductID                int64
CustomerID              object
DateKey                  int64
SalesAmount            float64
Quantity                 Int64
Timestamp       datetime64[ns]
dtype: object

========== PRIMARY KEY VALIDATION ==========
Unique SaleIDs: 9397
Duplicate SaleIDs: 0
Missing SaleIDs: 0

========== SOURCE SALE ID VALIDATION ==========
Unique SourceSaleIDs: 9397
Duplicate SourceSaleIDs: 0
Missing SourceSaleIDs: 0

========== FOREIGN KEY COLUMNS ==========
Unique ProductIDs: 50
Unique CustomerIDs: 1000
Unique DateKeys: 181

========== NULL VALIDATION ==========
SaleID          0
SourceSaleID    0
ProductID       0
CustomerID      0
DateKey         0
SalesAmount     0
Quantity        0
Timestamp       0
dtype: int64

========== FACTSALES RANGE ==========
SaleID Min: 1
SaleID Max: 10000
SalesAmount Min: 50.18
SalesAmount Max: 79783.4
Quantity Min: 1
Quantity Max: 50
DateKey Min: 20240601
DateKey Max: 20241128

========== SAMPLE DATA ==========
   SaleID                          SourceSaleID  ProductID CustomerID  \
0       1  c0078cd1-3ddc-439a-b41d-7498e8e75e62       1020       0460
1       2  be8532af-16b7-432c-a13d-4c6e6836d12d       1029       0198
2       3  8666f277-cc58-4fde-9d58-697da9e040f2       1012       0524
3       5  d9a7f974-9572-48dd-aa36-3f96b280dfc7       1021       0369
4       6  d71733ac-4fc4-42e6-ae48-c2150c8a92ae       1016       0709
5       7  b7475afb-27f7-46fe-8bcd-c099c178d17f       1047       0929
6       9  427c33bb-dff7-4332-8d29-954728c713b1       1020       0983
7      10  812ad61f-2e80-4b95-ae02-a91976bd2baa       1006       0536
8      11  a18dadb3-b2e6-476e-b2fb-b4a477721bf0       1005       0164
9      12  fb7031b8-6ea9-48f1-9a00-9bc178359f8d       1017       0955

    DateKey  SalesAmount  Quantity           Timestamp
0  20240809      1639.10        18 2024-08-09 20:21:00
1  20241128       186.11        42 2024-11-28 05:01:00
2  20241013      1712.72        49 2024-10-13 00:36:00
3  20240608        66.36        21 2024-06-08 19:58:00
4  20241115      1705.51        31 2024-11-15 12:24:00
5  20240828      1509.94         3 2024-08-28 05:43:00
6  20241022      1070.59        31 2024-10-22 15:17:00
7  20240620      1097.00         2 2024-06-20 09:59:00
8  20241115       683.83        38 2024-11-15 09:33:00
9  20240707      1187.22        26 2024-07-07 00:55:00

========== FACTSALES STATUS ==========
FactSales validation: PASS

In [ ]:
print("========== PHASE 2: STEP 20 — FINAL WAREHOUSE VALIDATION ==========")

# ============================================================
# 1. ROW COUNT VALIDATION
# ============================================================

print("\n========== ROW COUNT VALIDATION ==========")

print("DimCustomer rows:", len(dim_customer))
print("DimProduct rows:", len(dim_product))
print("DimDate rows:", len(dim_date))
print("FactSales rows:", len(fact_sales))

row_count_status = (
    len(dim_customer) == 1000
    and len(dim_product) == 50
    and len(dim_date) == 181
    and len(fact_sales) == 9397
)

print(
    "Row count validation:",
    "PASS" if row_count_status else "FAIL"
)


# ============================================================
# 2. PRIMARY KEY VALIDATION
# ============================================================

print("\n========== PRIMARY KEY VALIDATION ==========")

customer_pk_valid = (
    dim_customer["CustomerID"].notna().all()
    and dim_customer["CustomerID"].is_unique
)

product_pk_valid = (
    dim_product["ProductID"].notna().all()
    and dim_product["ProductID"].is_unique
)

date_pk_valid = (
    dim_date["DateKey"].notna().all()
    and dim_date["DateKey"].is_unique
)

fact_pk_valid = (
    fact_sales["SaleID"].notna().all()
    and fact_sales["SaleID"].is_unique
)

print(
    "DimCustomer CustomerID:",
    "PASS" if customer_pk_valid else "FAIL"
)

print(
    "DimProduct ProductID:",
    "PASS" if product_pk_valid else "FAIL"
)

print(
    "DimDate DateKey:",
    "PASS" if date_pk_valid else "FAIL"
)

print(
    "FactSales SaleID:",
    "PASS" if fact_pk_valid else "FAIL"
)


# ============================================================
# 3. FOREIGN KEY VALIDATION
# ============================================================

print("\n========== FOREIGN KEY VALIDATION ==========")

customer_fk_missing = (
    set(fact_sales["CustomerID"])
    - set(dim_customer["CustomerID"])
)

product_fk_missing = (
    set(fact_sales["ProductID"])
    - set(dim_product["ProductID"])
)

date_fk_missing = (
    set(fact_sales["DateKey"])
    - set(dim_date["DateKey"])
)

print(
    "FactSales → DimCustomer missing keys:",
    len(customer_fk_missing)
)

print(
    "FactSales → DimProduct missing keys:",
    len(product_fk_missing)
)

print(
    "FactSales → DimDate missing keys:",
    len(date_fk_missing)
)

foreign_key_status = (
    len(customer_fk_missing) == 0
    and len(product_fk_missing) == 0
    and len(date_fk_missing) == 0
)

print(
    "Foreign key validation:",
    "PASS" if foreign_key_status else "FAIL"
)


# ============================================================
# 4. NULL VALIDATION
# ============================================================

print("\n========== NULL VALIDATION ==========")

print("\nDimCustomer:")
print(dim_customer.isna().sum())

print("\nDimProduct:")
print(dim_product.isna().sum())

print("\nDimDate:")
print(dim_date.isna().sum())

print("\nFactSales:")
print(fact_sales.isna().sum())


# FactSales must have no NULLs
fact_null_status = (
    fact_sales.isna().sum().sum() == 0
)

print(
    "\nFactSales NULL validation:",
    "PASS" if fact_null_status else "FAIL"
)


# ============================================================
# 5. FACT SALES MEASURE VALIDATION
# ============================================================

print("\n========== FACT SALES MEASURE VALIDATION ==========")

negative_sales = (
    (fact_sales["SalesAmount"] < 0).sum()
)

zero_sales = (
    (fact_sales["SalesAmount"] == 0).sum()
)

negative_quantity = (
    (fact_sales["Quantity"] < 0).sum()
)

zero_quantity = (
    (fact_sales["Quantity"] == 0).sum()
)

print("Negative SalesAmount:", negative_sales)
print("Zero SalesAmount:", zero_sales)
print("Negative Quantity:", negative_quantity)
print("Zero Quantity:", zero_quantity)

measure_status = (
    negative_sales == 0
    and zero_sales == 0
    and negative_quantity == 0
    and zero_quantity == 0
)

print(
    "Measure validation:",
    "PASS" if measure_status else "FAIL"
)


# ============================================================
# 6. DATE CONSISTENCY VALIDATION
# ============================================================

print("\n========== DATE CONSISTENCY VALIDATION ==========")

fact_dates = set(
    fact_sales["Timestamp"].dt.normalize()
)

dimension_dates = set(
    dim_date["FullDate"]
)

missing_dimension_dates = (
    fact_dates - dimension_dates
)

print(
    "Transaction dates in FactSales:",
    len(fact_dates)
)

print(
    "Dates in DimDate:",
    len(dimension_dates)
)

print(
    "Transaction dates missing from DimDate:",
    len(missing_dimension_dates)
)

date_consistency_status = (
    len(missing_dimension_dates) == 0
)

print(
    "Date consistency:",
    "PASS" if date_consistency_status else "FAIL"
)


# ============================================================
# 7. OVERALL WAREHOUSE STATUS
# ============================================================

print("\n========== OVERALL WAREHOUSE STATUS ==========")

overall_warehouse_status = (
    row_count_status
    and customer_pk_valid
    and product_pk_valid
    and date_pk_valid
    and fact_pk_valid
    and foreign_key_status
    and fact_null_status
    and measure_status
    and date_consistency_status
)

print(
    "Final warehouse validation:",
    "PASS" if overall_warehouse_status else "FAIL"
)

========== PHASE 2: STEP 20 — FINAL WAREHOUSE VALIDATION ==========

========== ROW COUNT VALIDATION ==========
DimCustomer rows: 1000
DimProduct rows: 50
DimDate rows: 181
FactSales rows: 9397
Row count validation: PASS

========== PRIMARY KEY VALIDATION ==========
DimCustomer CustomerID: PASS
DimProduct ProductID: PASS
DimDate DateKey: PASS
FactSales SaleID: PASS

========== FOREIGN KEY VALIDATION ==========
FactSales → DimCustomer missing keys: 0
FactSales → DimProduct missing keys: 0
FactSales → DimDate missing keys: 0
Foreign key validation: PASS

========== NULL VALIDATION ==========

DimCustomer:
CustomerID      0
FirstName       0
LastName      290
Gender          0
Region          0
SSN             0
dtype: int64

DimProduct:
ProductID      0
ProductName    0
Category       0
dtype: int64

DimDate:
DateKey        0
FullDate       0
Year           0
MonthNumber    0
MonthName      0
Quarter        0
Day            0
DayName        0
DayOfWeek      0
dtype: int64

FactSales:
SaleID          0
SourceSaleID    0
ProductID       0
CustomerID      0
DateKey         0
SalesAmount     0
Quantity        0
Timestamp       0
dtype: int64

FactSales NULL validation: PASS

========== FACT SALES MEASURE VALIDATION ==========
Negative SalesAmount: 0
Zero SalesAmount: 0
Negative Quantity: 0
Zero Quantity: 0
Measure validation: PASS

========== DATE CONSISTENCY VALIDATION ==========
Transaction dates in FactSales: 181
Dates in DimDate: 181
Transaction dates missing from DimDate: 0
Date consistency: PASS

========== OVERALL WAREHOUSE STATUS ==========
Final warehouse validation: PASS

In [ ]:
print("========== PHASE 2: STEP 21 — MYSQL-READY TABLES ==========")

# ============================================================
# 1. DIM CUSTOMER
# ============================================================

dim_customer_mysql = dim_customer[
    [
        "CustomerID",
        "FirstName",
        "LastName",
        "Gender",
        "Region",
        "SSN"
    ]
].copy()


# ============================================================
# 2. DIM PRODUCT
# ============================================================

dim_product_mysql = dim_product[
    [
        "ProductID",
        "ProductName",
        "Category"
    ]
].copy()


# ============================================================
# 3. DIM DATE
# ============================================================

dim_date_mysql = dim_date[
    [
        "DateKey",
        "FullDate",
        "Year",
        "MonthNumber",
        "MonthName",
        "Quarter",
        "Day",
        "DayName",
        "DayOfWeek"
    ]
].copy()


# ============================================================
# 4. FACT SALES
# ============================================================

fact_sales_mysql = fact_sales[
    [
        "SaleID",
        "SourceSaleID",
        "ProductID",
        "CustomerID",
        "DateKey",
        "SalesAmount",
        "Quantity",
        "Timestamp"
    ]
].copy()


# ============================================================
# 5. TABLE STRUCTURE
# ============================================================

print("\n========== TABLE STRUCTURES ==========")

print("\nDimCustomer:")
print(dim_customer_mysql.shape)
print(dim_customer_mysql.columns.tolist())

print("\nDimProduct:")
print(dim_product_mysql.shape)
print(dim_product_mysql.columns.tolist())

print("\nDimDate:")
print(dim_date_mysql.shape)
print(dim_date_mysql.columns.tolist())

print("\nFactSales:")
print(fact_sales_mysql.shape)
print(fact_sales_mysql.columns.tolist())


# ============================================================
# 6. MYSQL-READY ROW COUNTS
# ============================================================

print("\n========== ROW COUNTS ==========")

print("DimCustomer:", len(dim_customer_mysql))
print("DimProduct:", len(dim_product_mysql))
print("DimDate:", len(dim_date_mysql))
print("FactSales:", len(fact_sales_mysql))


# ============================================================
# 7. FINAL MYSQL-READY NULL CHECK
# ============================================================

print("\n========== NULL CHECK ==========")

print("DimCustomer NULLs:",
      dim_customer_mysql.isna().sum().sum())

print("DimProduct NULLs:",
      dim_product_mysql.isna().sum().sum())

print("DimDate NULLs:",
      dim_date_mysql.isna().sum().sum())

print("FactSales NULLs:",
      fact_sales_mysql.isna().sum().sum())


# ============================================================
# 8. SAMPLE DATA
# ============================================================

print("\n========== SAMPLE DATA ==========")

print("\nDimCustomer:")
print(dim_customer_mysql.head(3))

print("\nDimProduct:")
print(dim_product_mysql.head(3))

print("\nDimDate:")
print(dim_date_mysql.head(3))

print("\nFactSales:")
print(fact_sales_mysql.head(3))


# ============================================================
# 9. MYSQL PREPARATION STATUS
# ============================================================

mysql_prep_status = (
    dim_customer_mysql.shape == (1000, 6)
    and dim_product_mysql.shape == (50, 3)
    and dim_date_mysql.shape == (181, 9)
    and fact_sales_mysql.shape == (9397, 8)
    and dim_customer_mysql["CustomerID"].is_unique
    and dim_product_mysql["ProductID"].is_unique
    and dim_date_mysql["DateKey"].is_unique
    and fact_sales_mysql["SaleID"].is_unique
)

print("\n========== MYSQL PREPARATION STATUS ==========")

print(
    "MySQL table preparation:",
    "PASS" if mysql_prep_status else "FAIL"
)

========== PHASE 2: STEP 21 — MYSQL-READY TABLES ==========

========== TABLE STRUCTURES ==========

DimCustomer:
(1000, 6)
['CustomerID', 'FirstName', 'LastName', 'Gender', 'Region', 'SSN']

DimProduct:
(50, 3)
['ProductID', 'ProductName', 'Category']

DimDate:
(181, 9)
['DateKey', 'FullDate', 'Year', 'MonthNumber', 'MonthName', 'Quarter', 'Day', 'DayName', 'DayOfWeek']

FactSales:
(9397, 8)
['SaleID', 'SourceSaleID', 'ProductID', 'CustomerID', 'DateKey', 'SalesAmount', 'Quantity', 'Timestamp']

========== ROW COUNTS ==========
DimCustomer: 1000
DimProduct: 50
DimDate: 181
FactSales: 9397

========== NULL CHECK ==========
DimCustomer NULLs: 290
DimProduct NULLs: 0
DimDate NULLs: 0
FactSales NULLs: 0

========== SAMPLE DATA ==========

DimCustomer:
  CustomerID FirstName LastName Gender      Region        SSN
0       0001   Gregory   Miller   Male        Ohio  082573197
1       0002    Marvin     <NA>   Male  California  309625621
2       0003   Gregory    Smith   Male    New York  407071725

DimProduct:
   ProductID      ProductName         Category
0       1000  Washing Machine  Home Appliances
1       1001     Refrigerator  Home Appliances
2       1002          Blender  Home Appliances

DimDate:
    DateKey   FullDate  Year  MonthNumber MonthName Quarter  Day   DayName  \
0  20240601 2024-06-01  2024            6      June      Q2    1  Saturday
1  20240602 2024-06-02  2024            6      June      Q2    2    Sunday
2  20240603 2024-06-03  2024            6      June      Q2    3    Monday

   DayOfWeek
0          6
1          7
2          1

FactSales:
   SaleID                          SourceSaleID  ProductID CustomerID  \
0       1  c0078cd1-3ddc-439a-b41d-7498e8e75e62       1020       0460
1       2  be8532af-16b7-432c-a13d-4c6e6836d12d       1029       0198
2       3  8666f277-cc58-4fde-9d58-697da9e040f2       1012       0524

    DateKey  SalesAmount  Quantity           Timestamp
0  20240809      1639.10        18 2024-08-09 20:21:00
1  20241128       186.11        42 2024-11-28 05:01:00
2  20241013      1712.72        49 2024-10-13 00:36:00

========== MYSQL PREPARATION STATUS ==========
MySQL table preparation: PASS

In [ ]:
print("========== PHASE 2: STEP 22 — MYSQL DATA TYPE MAPPING ==========")

mysql_schema = {
    "DimCustomer": {
        "CustomerID": "VARCHAR(4) PRIMARY KEY",
        "FirstName": "VARCHAR(100) NOT NULL",
        "LastName": "VARCHAR(100) NULL",
        "Gender": "VARCHAR(20) NOT NULL",
        "Region": "VARCHAR(50) NOT NULL",
        "SSN": "CHAR(9) NOT NULL"
    },

    "DimProduct": {
        "ProductID": "INT PRIMARY KEY",
        "ProductName": "VARCHAR(100) NOT NULL",
        "Category": "VARCHAR(50) NOT NULL"
    },

    "DimDate": {
        "DateKey": "INT PRIMARY KEY",
        "FullDate": "DATE NOT NULL",
        "Year": "INT NOT NULL",
        "MonthNumber": "INT NOT NULL",
        "MonthName": "VARCHAR(20) NOT NULL",
        "Quarter": "VARCHAR(2) NOT NULL",
        "Day": "INT NOT NULL",
        "DayName": "VARCHAR(20) NOT NULL",
        "DayOfWeek": "INT NOT NULL"
    },

    "FactSales": {
        "SaleID": "INT PRIMARY KEY",
        "SourceSaleID": "VARCHAR(36) NOT NULL UNIQUE",
        "ProductID": "INT NOT NULL",
        "CustomerID": "VARCHAR(4) NOT NULL",
        "DateKey": "INT NOT NULL",
        "SalesAmount": "DECIMAL(10,2) NOT NULL",
        "Quantity": "INT NOT NULL",
        "Timestamp": "DATETIME NOT NULL"
    }
}


# ============================================================
# DISPLAY SCHEMA
# ============================================================

for table_name, columns in mysql_schema.items():

    print(f"\n========== {table_name.upper()} ==========")

    for column_name, mysql_type in columns.items():
        print(f"{column_name:<15} -> {mysql_type}")


# ============================================================
# CHECK IMPORTANT DESIGN DECISIONS
# ============================================================

print("\n========== IMPORTANT DESIGN CHECKS ==========")

print(
    "CustomerID type:",
    mysql_schema["DimCustomer"]["CustomerID"]
)

print(
    "FactSales CustomerID type:",
    mysql_schema["FactSales"]["CustomerID"]
)

print(
    "SourceSaleID type:",
    mysql_schema["FactSales"]["SourceSaleID"]
)

print(
    "SalesAmount type:",
    mysql_schema["FactSales"]["SalesAmount"]
)

print(
    "Quantity type:",
    mysql_schema["FactSales"]["Quantity"]
)


# ============================================================
# VALIDATE CUSTOMER ID FORMAT BEFORE MYSQL
# ============================================================

customer_id_valid = (
    dim_customer_mysql["CustomerID"]
    .str.fullmatch(r"\d{4}")
    .all()
)

sales_customer_id_valid = (
    fact_sales_mysql["CustomerID"]
    .str.fullmatch(r"\d{4}")
    .all()
)

print("\n========== CUSTOMER ID FORMAT CHECK ==========")

print(
    "DimCustomer 4-digit CustomerID:",
    "PASS" if customer_id_valid else "FAIL"
)

print(
    "FactSales 4-digit CustomerID:",
    "PASS" if sales_customer_id_valid else "FAIL"
)


# ============================================================
# SOURCE UUID VALIDATION
# ============================================================

source_uuid_valid = (
    fact_sales_mysql["SourceSaleID"]
    .str.fullmatch(
        r"[0-9a-fA-F]{8}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{12}"
    )
    .all()
)

print(
    "SourceSaleID UUID format:",
    "PASS" if source_uuid_valid else "FAIL"
)


# ============================================================
# OVERALL STATUS
# ============================================================

mysql_schema_status = (
    customer_id_valid
    and sales_customer_id_valid
    and source_uuid_valid
)

print("\n========== MYSQL DATA TYPE MAPPING STATUS ==========")

print(
    "MySQL schema mapping:",
    "PASS" if mysql_schema_status else "FAIL"
)

========== PHASE 2: STEP 22 — MYSQL DATA TYPE MAPPING ==========

========== DIMCUSTOMER ==========
CustomerID      -> VARCHAR(4) PRIMARY KEY
FirstName       -> VARCHAR(100) NOT NULL
LastName        -> VARCHAR(100) NULL
Gender          -> VARCHAR(20) NOT NULL
Region          -> VARCHAR(50) NOT NULL
SSN             -> CHAR(9) NOT NULL

========== DIMPRODUCT ==========
ProductID       -> INT PRIMARY KEY
ProductName     -> VARCHAR(100) NOT NULL
Category        -> VARCHAR(50) NOT NULL

========== DIMDATE ==========
DateKey         -> INT PRIMARY KEY
FullDate        -> DATE NOT NULL
Year            -> INT NOT NULL
MonthNumber     -> INT NOT NULL
MonthName       -> VARCHAR(20) NOT NULL
Quarter         -> VARCHAR(2) NOT NULL
Day             -> INT NOT NULL
DayName         -> VARCHAR(20) NOT NULL
DayOfWeek       -> INT NOT NULL

========== FACTSALES ==========
SaleID          -> INT PRIMARY KEY
SourceSaleID    -> VARCHAR(36) NOT NULL UNIQUE
ProductID       -> INT NOT NULL
CustomerID      -> VARCHAR(4) NOT NULL
DateKey         -> INT NOT NULL
SalesAmount     -> DECIMAL(10,2) NOT NULL
Quantity        -> INT NOT NULL
Timestamp       -> DATETIME NOT NULL

========== IMPORTANT DESIGN CHECKS ==========
CustomerID type: VARCHAR(4) PRIMARY KEY
FactSales CustomerID type: VARCHAR(4) NOT NULL
SourceSaleID type: VARCHAR(36) NOT NULL UNIQUE
SalesAmount type: DECIMAL(10,2) NOT NULL
Quantity type: INT NOT NULL

========== CUSTOMER ID FORMAT CHECK ==========
DimCustomer 4-digit CustomerID: PASS
FactSales 4-digit CustomerID: PASS
SourceSaleID UUID format: PASS

========== MYSQL DATA TYPE MAPPING STATUS ==========
MySQL schema mapping: PASS

In [ ]:
print("========== PHASE 2: STEP 23 — MYSQL CREATE TABLE DDL ==========")

mysql_ddl = """

CREATE DATABASE IF NOT EXISTS retail_sales_dw;

USE retail_sales_dw;


-- ============================================================
-- DIM CUSTOMER
-- ============================================================

CREATE TABLE IF NOT EXISTS DimCustomer (
    CustomerID VARCHAR(4) PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NULL,
    Gender VARCHAR(20) NOT NULL,
    Region VARCHAR(50) NOT NULL,
    SSN CHAR(9) NOT NULL
);


-- ============================================================
-- DIM PRODUCT
-- ============================================================

CREATE TABLE IF NOT EXISTS DimProduct (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL,
    Category VARCHAR(50) NOT NULL
);


-- ============================================================
-- DIM DATE
-- ============================================================

CREATE TABLE IF NOT EXISTS DimDate (
    DateKey INT PRIMARY KEY,
    FullDate DATE NOT NULL,
    Year INT NOT NULL,
    MonthNumber INT NOT NULL,
    MonthName VARCHAR(20) NOT NULL,
    Quarter VARCHAR(2) NOT NULL,
    Day INT NOT NULL,
    DayName VARCHAR(20) NOT NULL,
    DayOfWeek INT NOT NULL
);


-- ============================================================
-- FACT SALES
-- ============================================================

CREATE TABLE IF NOT EXISTS FactSales (
    SaleID INT PRIMARY KEY,
    SourceSaleID VARCHAR(36) NOT NULL UNIQUE,
    ProductID INT NOT NULL,
    CustomerID VARCHAR(4) NOT NULL,
    DateKey INT NOT NULL,
    SalesAmount DECIMAL(10,2) NOT NULL,
    Quantity INT NOT NULL,
    Timestamp DATETIME NOT NULL,

    CONSTRAINT fk_factsales_customer
        FOREIGN KEY (CustomerID)
        REFERENCES DimCustomer(CustomerID),

    CONSTRAINT fk_factsales_product
        FOREIGN KEY (ProductID)
        REFERENCES DimProduct(ProductID),

    CONSTRAINT fk_factsales_date
        FOREIGN KEY (DateKey)
        REFERENCES DimDate(DateKey)
);

"""

print(mysql_ddl)


# ============================================================
# BASIC DDL DESIGN VALIDATION
# ============================================================

required_tables = [
    "DimCustomer",
    "DimProduct",
    "DimDate",
    "FactSales"
]

required_foreign_keys = [
    "fk_factsales_customer",
    "fk_factsales_product",
    "fk_factsales_date"
]

print("\n========== DDL DESIGN CHECK ==========")

for table in required_tables:
    print(f"{table}: INCLUDED")

print("\nForeign Keys:")

for fk in required_foreign_keys:
    print(f"{fk}: INCLUDED")


# ============================================================
# IMPORTANT COLUMN CHECKS
# ============================================================

ddl_checks = [
    "CustomerID VARCHAR(4)",
    "SourceSaleID VARCHAR(36)",
    "SalesAmount DECIMAL(10,2)",
    "Quantity INT",
    "DateKey INT",
    "FOREIGN KEY (CustomerID)",
    "FOREIGN KEY (ProductID)",
    "FOREIGN KEY (DateKey)"
]

print("\n========== KEY DDL DEFINITIONS ==========")

for check in ddl_checks:
    print(
        check,
        ":",
        "FOUND" if check in mysql_ddl else "MISSING"
    )


ddl_status = all(
    check in mysql_ddl
    for check in ddl_checks
)

print("\n========== MYSQL DDL STATUS ==========")

print(
    "CREATE TABLE DDL validation:",
    "PASS" if ddl_status else "FAIL"
)

========== PHASE 2: STEP 23 — MYSQL CREATE TABLE DDL ==========


CREATE DATABASE IF NOT EXISTS retail_sales_dw;

USE retail_sales_dw;


-- ============================================================
-- DIM CUSTOMER
-- ============================================================

CREATE TABLE IF NOT EXISTS DimCustomer (
    CustomerID VARCHAR(4) PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NULL,
    Gender VARCHAR(20) NOT NULL,
    Region VARCHAR(50) NOT NULL,
    SSN CHAR(9) NOT NULL
);


-- ============================================================
-- DIM PRODUCT
-- ============================================================

CREATE TABLE IF NOT EXISTS DimProduct (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL,
    Category VARCHAR(50) NOT NULL
);


-- ============================================================
-- DIM DATE
-- ============================================================

CREATE TABLE IF NOT EXISTS DimDate (
    DateKey INT PRIMARY KEY,
    FullDate DATE NOT NULL,
    Year INT NOT NULL,
    MonthNumber INT NOT NULL,
    MonthName VARCHAR(20) NOT NULL,
    Quarter VARCHAR(2) NOT NULL,
    Day INT NOT NULL,
    DayName VARCHAR(20) NOT NULL,
    DayOfWeek INT NOT NULL
);


-- ============================================================
-- FACT SALES
-- ============================================================

CREATE TABLE IF NOT EXISTS FactSales (
    SaleID INT PRIMARY KEY,
    SourceSaleID VARCHAR(36) NOT NULL UNIQUE,
    ProductID INT NOT NULL,
    CustomerID VARCHAR(4) NOT NULL,
    DateKey INT NOT NULL,
    SalesAmount DECIMAL(10,2) NOT NULL,
    Quantity INT NOT NULL,
    Timestamp DATETIME NOT NULL,

    CONSTRAINT fk_factsales_customer
        FOREIGN KEY (CustomerID)
        REFERENCES DimCustomer(CustomerID),

    CONSTRAINT fk_factsales_product
        FOREIGN KEY (ProductID)
        REFERENCES DimProduct(ProductID),

    CONSTRAINT fk_factsales_date
        FOREIGN KEY (DateKey)
        REFERENCES DimDate(DateKey)
);



========== DDL DESIGN CHECK ==========
DimCustomer: INCLUDED
DimProduct: INCLUDED
DimDate: INCLUDED
FactSales: INCLUDED

Foreign Keys:
fk_factsales_customer: INCLUDED
fk_factsales_product: INCLUDED
fk_factsales_date: INCLUDED

========== KEY DDL DEFINITIONS ==========
CustomerID VARCHAR(4) : FOUND
SourceSaleID VARCHAR(36) : FOUND
SalesAmount DECIMAL(10,2) : FOUND
Quantity INT : FOUND
DateKey INT : FOUND
FOREIGN KEY (CustomerID) : FOUND
FOREIGN KEY (ProductID) : FOUND
FOREIGN KEY (DateKey) : FOUND

========== MYSQL DDL STATUS ==========
CREATE TABLE DDL validation: PASS

In [ ]:
print("========== PHASE 2: STEP 24 — EXPORT MYSQL FILES ==========")

import os

# ============================================================
# OUTPUT DIRECTORY
# ============================================================

output_dir = "/content/retail_sales_mysql"

os.makedirs(output_dir, exist_ok=True)


# ============================================================
# 1. EXPORT DIM CUSTOMER
# ============================================================

dim_customer_mysql.to_csv(
    f"{output_dir}/DimCustomer.csv",
    index=False
)


# ============================================================
# 2. EXPORT DIM PRODUCT
# ============================================================

dim_product_mysql.to_csv(
    f"{output_dir}/DimProduct.csv",
    index=False
)


# ============================================================
# 3. EXPORT DIM DATE
# ============================================================

dim_date_mysql.to_csv(
    f"{output_dir}/DimDate.csv",
    index=False
)


# ============================================================
# 4. EXPORT FACT SALES
# ============================================================

fact_sales_mysql.to_csv(
    f"{output_dir}/FactSales.csv",
    index=False
)


# ============================================================
# 5. EXPORT MYSQL DDL SCRIPT
# ============================================================

with open(
    f"{output_dir}/retail_sales_dw.sql",
    "w",
    encoding="utf-8"
) as file:

    file.write(mysql_ddl)


# ============================================================
# 6. CHECK CREATED FILES
# ============================================================

print("\n========== EXPORTED FILES ==========")

for filename in sorted(os.listdir(output_dir)):

    filepath = os.path.join(output_dir, filename)

    size_kb = os.path.getsize(filepath) / 1024

    print(
        f"{filename:<25} "
        f"{size_kb:.2f} KB"
    )


# ============================================================
# 7. VERIFY CSV ROW COUNTS
# ============================================================

print("\n========== CSV ROW COUNT VALIDATION ==========")

exported_customer = pd.read_csv(
    f"{output_dir}/DimCustomer.csv",
    dtype={"CustomerID": "string"}
)

exported_product = pd.read_csv(
    f"{output_dir}/DimProduct.csv"
)

exported_date = pd.read_csv(
    f"{output_dir}/DimDate.csv"
)

exported_fact = pd.read_csv(
    f"{output_dir}/FactSales.csv",
    dtype={
        "CustomerID": "string",
        "SourceSaleID": "string"
    }
)

print("DimCustomer CSV rows:", len(exported_customer))
print("DimProduct CSV rows:", len(exported_product))
print("DimDate CSV rows:", len(exported_date))
print("FactSales CSV rows:", len(exported_fact))


# ============================================================
# 8. CUSTOMER ID LEADING ZERO CHECK
# ============================================================

print("\n========== CUSTOMER ID LEADING ZERO CHECK ==========")

print(
    "First CustomerID:",
    exported_customer["CustomerID"].iloc[0]
)

print(
    "First 10 CustomerIDs:"
)

print(
    exported_customer["CustomerID"].head(10).tolist()
)

customer_id_csv_valid = (
    exported_customer["CustomerID"]
    .str.fullmatch(r"\d{4}")
    .all()
)

print(
    "CustomerID 4-digit format:",
    "PASS" if customer_id_csv_valid else "FAIL"
)


# ============================================================
# 9. SOURCE UUID CHECK
# ============================================================

source_uuid_csv_valid = (
    exported_fact["SourceSaleID"]
    .str.fullmatch(
        r"[0-9a-fA-F]{8}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{4}-"
        r"[0-9a-fA-F]{12}"
    )
    .all()
)

print(
    "SourceSaleID UUID format:",
    "PASS" if source_uuid_csv_valid else "FAIL"
)


# ============================================================
# 10. FINAL EXPORT STATUS
# ============================================================

export_status = (
    len(exported_customer) == 1000
    and len(exported_product) == 50
    and len(exported_date) == 181
    and len(exported_fact) == 9397
    and customer_id_csv_valid
    and source_uuid_csv_valid
)

print("\n========== MYSQL EXPORT STATUS ==========")

print(
    "MySQL export validation:",
    "PASS" if export_status else "FAIL"
)

========== PHASE 2: STEP 24 — EXPORT MYSQL FILES ==========

========== EXPORTED FILES ==========
DimCustomer.csv           39.87 KB
DimDate.csv               9.00 KB
DimProduct.csv            1.23 KB
FactSales.csv             836.00 KB
retail_sales_dw.sql       1.93 KB

========== CSV ROW COUNT VALIDATION ==========
DimCustomer CSV rows: 1000
DimProduct CSV rows: 50
DimDate CSV rows: 181
FactSales CSV rows: 9397

========== CUSTOMER ID LEADING ZERO CHECK ==========
First CustomerID: 0001
First 10 CustomerIDs:
['0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010']
CustomerID 4-digit format: PASS
SourceSaleID UUID format: PASS

========== MYSQL EXPORT STATUS ==========
MySQL export validation: PASS

In [ ]:
print("========== PHASE 2: STEP 25 — CREATE MYSQL IMPORT PACKAGE ==========")

import os
import zipfile

output_dir = "/content/retail_sales_mysql"

zip_path = "/content/retail_sales_mysql_import.zip"

# ============================================================
# CREATE ZIP PACKAGE
# ============================================================

with zipfile.ZipFile(
    zip_path,
    mode="w",
    compression=zipfile.ZIP_DEFLATED
) as zip_file:

    for filename in sorted(os.listdir(output_dir)):

        filepath = os.path.join(output_dir, filename)

        zip_file.write(
            filepath,
            arcname=filename
        )


# ============================================================
# VERIFY ZIP CONTENTS
# ============================================================

print("\n========== ZIP CONTENTS ==========")

with zipfile.ZipFile(zip_path, "r") as zip_file:

    files_inside = zip_file.namelist()

    for filename in files_inside:
        print(filename)


# ============================================================
# FILE COUNT
# ============================================================

print("\n========== PACKAGE VALIDATION ==========")

expected_files = {
    "DimCustomer.csv",
    "DimProduct.csv",
    "DimDate.csv",
    "FactSales.csv",
    "retail_sales_dw.sql"
}

actual_files = set(files_inside)

missing_files = expected_files - actual_files
unexpected_files = actual_files - expected_files

print("Expected files:", len(expected_files))
print("Files in package:", len(actual_files))
print("Missing files:", len(missing_files))
print("Unexpected files:", len(unexpected_files))

if missing_files:
    print("Missing:", sorted(missing_files))

if unexpected_files:
    print("Unexpected:", sorted(unexpected_files))


# ============================================================
# ZIP SIZE
# ============================================================

zip_size_kb = os.path.getsize(zip_path) / 1024

print("\nZIP package size:",
      f"{zip_size_kb:.2f} KB")


# ============================================================
# FINAL STATUS
# ============================================================

package_status = (
    actual_files == expected_files
)

print("\n========== MYSQL IMPORT PACKAGE STATUS ==========")

print(
    "MySQL import package:",
    "PASS" if package_status else "FAIL"
)

========== PHASE 2: STEP 25 — CREATE MYSQL IMPORT PACKAGE ==========

========== ZIP CONTENTS ==========
DimCustomer.csv
DimDate.csv
DimProduct.csv
FactSales.csv
retail_sales_dw.sql

========== PACKAGE VALIDATION ==========
Expected files: 5
Files in package: 5
Missing files: 0
Unexpected files: 0

ZIP package size: 406.73 KB

========== MYSQL IMPORT PACKAGE STATUS ==========
MySQL import package: PASS